"""
Gauntlet Audit Templates - v1.

Provides vertical-specific audit templates for generating
compliance-ready reports from DecisionReceipts.

Templates are designed for:
- Compliance audits (GDPR, HIPAA, SOX, PCI-DSS)
- Security assessments (OWASP, NIST, ISO 27001)
- Legal reviews (eDiscovery, litigation hold)
- Financial audits (SOC 2, internal controls)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from aragora.gauntlet.receipt import DecisionReceipt


class TemplateCategory(Enum):
    """Categories of audit templates."""

    COMPLIANCE = "compliance"
    SECURITY = "security"
    LEGAL = "legal"
    FINANCIAL = "financial"
    OPERATIONAL = "operational"
    CUSTOM = "custom"


class TemplateFormat(Enum):
    """Output formats for templates."""

    MARKDOWN = "markdown"
    HTML = "html"
    JSON = "json"
    PDF = "pdf"  # Requires external rendering
    TEXT = "text"


@dataclass
class TemplateSection:
    """A section within an audit template."""

    id: str
    title: str
    description: str
    required: bool = True
    receipt_fields: List[str] = field(default_factory=list)
    custom_renderer: Optional[str] = None  # Function name for custom rendering


@dataclass
class AuditTemplate:
    """
    Audit template for generating compliance reports.

    Templates define:
    - Required sections and their order
    - Field mappings from DecisionReceipt
    - Compliance-specific formatting
    - Regulatory language and disclaimers
    """

    id: str
    name: str
    category: TemplateCategory
    description: str
    version: str = "1.0.0"

    # Sections
    sections: List[TemplateSection] = field(default_factory=list)

    # Regulatory info
    regulations: List[str] = field(default_factory=list)
    disclaimer: str = ""

    # Rendering options
    supported_formats: List[TemplateFormat] = field(
        default_factory=lambda: [TemplateFormat.MARKDOWN, TemplateFormat.HTML]
    )
    default_format: TemplateFormat = TemplateFormat.MARKDOWN

    # Metadata
    created_at: str = ""
    updated_at: str = ""
    author: str = "Aragora"

    def __post_init__(self):
        if not self.created_at:
            self.created_at = datetime.now().isoformat()
        if not self.updated_at:
            self.updated_at = self.created_at

    def render(
        self,
        receipt: "DecisionReceipt",
        format: Optional[TemplateFormat] = None,
    ) -> str:
        """
        Render the template with a DecisionReceipt.

        Args:
            receipt: The DecisionReceipt to render
            format: Output format (defaults to template default)

        Returns:
            Rendered report string
        """
        fmt = format or self.default_format

        if fmt == TemplateFormat.MARKDOWN:
            return self._render_markdown(receipt)
        elif fmt == TemplateFormat.HTML:
            return self._render_html(receipt)
        elif fmt == TemplateFormat.JSON:
            return self._render_json(receipt)
        elif fmt == TemplateFormat.TEXT:
            return self._render_text(receipt)
        else:
            raise ValueError(f"Unsupported format: {fmt}")

    def _render_markdown(self, receipt: "DecisionReceipt") -> str:
        """Render as Markdown."""
        lines = [
            f"# {self.name}",
            "",
            f"**Template:** {self.id} v{self.version}",
            f"**Category:** {self.category.value.title()}",
            f"**Generated:** {datetime.now().isoformat()}",
            "",
        ]

        if self.regulations:
            lines.append(f"**Applicable Regulations:** {', '.join(self.regulations)}")
            lines.append("")

        lines.append("---")
        lines.append("")

        # Render each section
        for section in self.sections:
            lines.append(f"## {section.title}")
            lines.append("")
            lines.append(section.description)
            lines.append("")

            # Render section content
            content = self._get_section_content(receipt, section)
            lines.extend(content)
            lines.append("")

        # Disclaimer
        if self.disclaimer:
            lines.append("---")
            lines.append("")
            lines.append("### Disclaimer")
            lines.append("")
            lines.append(f"*{self.disclaimer}*")
            lines.append("")

        # Footer
        lines.append("---")
        lines.append("")
        lines.append(f"*Generated by Aragora Gauntlet - {self.name} Template*")

        return "\n".join(lines)

    def _render_html(self, receipt: "DecisionReceipt") -> str:
        """Render as HTML."""
        from html import escape

        sections_html = ""
        for section in self.sections:
            content = self._get_section_content(receipt, section)
            content_html = "<br>".join(escape(line) for line in content)
            sections_html += f"""
            <div class="section">
                <h2>{escape(section.title)}</h2>
                <p class="description">{escape(section.description)}</p>
                <div class="content">{content_html}</div>
            </div>
            """

        regulations_html = ""
        if self.regulations:
            regulations_html = f"<p><strong>Applicable Regulations:</strong> {escape(', '.join(self.regulations))}</p>"

        disclaimer_html = ""
        if self.disclaimer:
            disclaimer_html = f"""
            <div class="disclaimer">
                <h3>Disclaimer</h3>
                <p><em>{escape(self.disclaimer)}</em></p>
            </div>
            """

        return f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{escape(self.name)}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; }}
        h1 {{ color: #1a1a1a; border-bottom: 2px solid #eee; padding-bottom: 10px; }}
        h2 {{ color: #333; margin-top: 24px; }}
        .meta {{ font-size: 13px; color: #666; margin: 10px 0; }}
        .section {{ margin: 24px 0; padding: 16px; background: #f8f9fa; border-radius: 8px; }}
        .description {{ font-style: italic; color: #555; }}
        .content {{ margin-top: 12px; }}
        .disclaimer {{ margin-top: 24px; padding: 16px; background: #fff3cd; border-radius: 8px; }}
        .footer {{ margin-top: 24px; font-size: 12px; color: #888; text-align: center; }}
    </style>
</head>
<body>
    <h1>{escape(self.name)}</h1>
    <div class="meta">
        <strong>Template:</strong> {escape(self.id)} v{escape(self.version)}<br>
        <strong>Category:</strong> {escape(self.category.value.title())}<br>
        <strong>Generated:</strong> {datetime.now().isoformat()}
    </div>
    {regulations_html}
    {sections_html}
    {disclaimer_html}
    <div class="footer">
        Generated by Aragora Gauntlet - {escape(self.name)} Template
    </div>
</body>
</html>
"""

    def _render_json(self, receipt: "DecisionReceipt") -> str:
        """Render as JSON."""
        import json

        sections_data: Dict[str, Any] = {}
        for section in self.sections:
            content = self._get_section_content(receipt, section)
            sections_data[section.id] = {
                "title": section.title,
                "description": section.description,
                "content": content,
            }

        data: Dict[str, Any] = {
            "template": {
                "id": self.id,
                "name": self.name,
                "version": self.version,
                "category": self.category.value,
            },
            "generated_at": datetime.now().isoformat(),
            "regulations": self.regulations,
            "sections": sections_data,
            "receipt": receipt.to_dict(),
        }

        if self.disclaimer:
            data["disclaimer"] = self.disclaimer

        return json.dumps(data, indent=2)

    def _render_text(self, receipt: "DecisionReceipt") -> str:
        """Render as plain text."""
        lines = [
            self.name.upper(),
            "=" * len(self.name),
            "",
            f"Template: {self.id} v{self.version}",
            f"Category: {self.category.value.title()}",
            f"Generated: {datetime.now().isoformat()}",
            "",
        ]

        if self.regulations:
            lines.append(f"Applicable Regulations: {', '.join(self.regulations)}")
            lines.append("")

        lines.append("-" * 60)
        lines.append("")

        for section in self.sections:
            lines.append(section.title.upper())
            lines.append("-" * len(section.title))
            lines.append(section.description)
            lines.append("")
            content = self._get_section_content(receipt, section)
            lines.extend(content)
            lines.append("")
            lines.append("")

        if self.disclaimer:
            lines.append("-" * 60)
            lines.append("DISCLAIMER")
            lines.append(self.disclaimer)
            lines.append("")

        return "\n".join(lines)

    def _get_section_content(
        self,
        receipt: "DecisionReceipt",
        section: TemplateSection,
    ) -> List[str]:
        """Get content for a section from receipt fields."""
        lines = []

        for field_name in section.receipt_fields:
            value = getattr(receipt, field_name, None)
            if value is None:
                continue

            # Format based on type
            if isinstance(value, dict):
                lines.append(f"**{field_name.replace('_', ' ').title()}:**")
                for k, v in value.items():
                    lines.append(f"  - {k}: {v}")
            elif isinstance(value, list):
                lines.append(f"**{field_name.replace('_', ' ').title()}:**")
                for item in value[:10]:  # Limit to 10 items
                    if isinstance(item, dict):
                        lines.append(f"  - {item.get('title', item.get('id', str(item)))}")
                    else:
                        lines.append(f"  - {item}")
            elif isinstance(value, float):
                lines.append(f"**{field_name.replace('_', ' ').title()}:** {value:.1%}")
            else:
                lines.append(f"**{field_name.replace('_', ' ').title()}:** {value}")

        return lines

    def to_dict(self) -> Dict[str, Any]:
        """Convert template to dictionary."""
        return {
            "id": self.id,
            "name": self.name,
            "category": self.category.value,
            "description": self.description,
            "version": self.version,
            "sections": [
                {
                    "id": s.id,
                    "title": s.title,
                    "description": s.description,
                    "required": s.required,
                    "receipt_fields": s.receipt_fields,
                }
                for s in self.sections
            ],
            "regulations": self.regulations,
            "disclaimer": self.disclaimer,
            "supported_formats": [f.value for f in self.supported_formats],
            "default_format": self.default_format.value,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "author": self.author,
        }


# =============================================================================
# Pre-built Templates
# =============================================================================

COMPLIANCE_TEMPLATE = AuditTemplate(
    id="compliance-standard",
    name="Compliance Audit Report",
    category=TemplateCategory.COMPLIANCE,
    description="Standard compliance audit report suitable for regulatory review.",
    regulations=["GDPR", "CCPA", "HIPAA", "SOX"],
    sections=[
        TemplateSection(
            id="executive-summary",
            title="Executive Summary",
            description="High-level overview of the validation results.",
            receipt_fields=["verdict", "confidence", "robustness_score", "verdict_reasoning"],
        ),
        TemplateSection(
            id="risk-assessment",
            title="Risk Assessment",
            description="Quantified risk analysis by severity level.",
            receipt_fields=["risk_summary", "vulnerabilities_found"],
        ),
        TemplateSection(
            id="validation-coverage",
            title="Validation Coverage",
            description="Scope and depth of the validation process.",
            receipt_fields=["attacks_attempted", "attacks_successful", "probes_run"],
        ),
        TemplateSection(
            id="critical-findings",
            title="Critical Findings",
            description="Detailed analysis of high-severity issues requiring immediate attention.",
            receipt_fields=["vulnerability_details"],
        ),
        TemplateSection(
            id="consensus-analysis",
            title="Multi-Agent Consensus",
            description="Analysis of agent agreement and dissenting opinions.",
            receipt_fields=["dissenting_views", "consensus_proof"],
        ),
        TemplateSection(
            id="audit-trail",
            title="Audit Trail",
            description="Complete provenance chain for traceability.",
            receipt_fields=["provenance_chain"],
        ),
        TemplateSection(
            id="integrity-verification",
            title="Integrity Verification",
            description="Cryptographic verification of report integrity.",
            receipt_fields=["receipt_id", "input_hash", "artifact_hash"],
        ),
    ],
    disclaimer=(
        "This report is generated automatically and should be reviewed by qualified "
        "compliance personnel before making regulatory decisions. The findings reflect "
        "the state of the system at the time of validation and may not capture all risks."
    ),
)

SECURITY_TEMPLATE = AuditTemplate(
    id="security-assessment",
    name="Security Assessment Report",
    category=TemplateCategory.SECURITY,
    description="Technical security assessment following industry frameworks.",
    regulations=["OWASP Top 10", "NIST CSF", "ISO 27001", "CIS Controls"],
    sections=[
        TemplateSection(
            id="threat-summary",
            title="Threat Summary",
            description="Overview of identified threats and attack vectors.",
            receipt_fields=["verdict", "confidence", "attacks_attempted", "attacks_successful"],
        ),
        TemplateSection(
            id="vulnerability-analysis",
            title="Vulnerability Analysis",
            description="Technical breakdown of discovered vulnerabilities.",
            receipt_fields=["risk_summary", "vulnerability_details"],
        ),
        TemplateSection(
            id="attack-surface",
            title="Attack Surface Coverage",
            description="Analysis of tested attack vectors and probing methods.",
            receipt_fields=["probes_run", "attacks_attempted"],
        ),
        TemplateSection(
            id="robustness-metrics",
            title="Robustness Metrics",
            description="Quantitative security posture measurements.",
            receipt_fields=["robustness_score", "confidence"],
        ),
        TemplateSection(
            id="remediation",
            title="Remediation Recommendations",
            description="Prioritized list of security improvements.",
            receipt_fields=["vulnerability_details", "verdict_reasoning"],
        ),
        TemplateSection(
            id="evidence-chain",
            title="Evidence Chain",
            description="Technical evidence supporting findings.",
            receipt_fields=["provenance_chain", "input_hash"],
        ),
    ],
    disclaimer=(
        "This security assessment is point-in-time and may not reflect current "
        "vulnerabilities. Findings should be validated by qualified security "
        "professionals before remediation. No warranty of completeness is implied."
    ),
)

LEGAL_TEMPLATE = AuditTemplate(
    id="legal-review",
    name="Legal Review Documentation",
    category=TemplateCategory.LEGAL,
    description="Documentation suitable for legal proceedings and eDiscovery.",
    regulations=["FRCP", "eDiscovery Guidelines"],
    sections=[
        TemplateSection(
            id="matter-summary",
            title="Matter Summary",
            description="Summary of the validation matter and scope.",
            receipt_fields=["receipt_id", "gauntlet_id", "timestamp"],
        ),
        TemplateSection(
            id="determination",
            title="Determination",
            description="Final determination with supporting rationale.",
            receipt_fields=["verdict", "confidence", "verdict_reasoning"],
        ),
        TemplateSection(
            id="dissent-record",
            title="Record of Dissent",
            description="Documentation of dissenting opinions for completeness.",
            receipt_fields=["dissenting_views"],
        ),
        TemplateSection(
            id="chain-of-custody",
            title="Chain of Custody",
            description="Complete provenance chain establishing evidence handling.",
            receipt_fields=["provenance_chain", "input_hash", "artifact_hash"],
        ),
        TemplateSection(
            id="integrity-attestation",
            title="Integrity Attestation",
            description="Cryptographic attestation of document integrity.",
            receipt_fields=["artifact_hash", "input_hash"],
        ),
    ],
    disclaimer=(
        "This document is provided for informational purposes and should be reviewed "
        "by qualified legal counsel. It does not constitute legal advice. The automated "
        "nature of this analysis should be considered when evaluating findings."
    ),
)

FINANCIAL_TEMPLATE = AuditTemplate(
    id="financial-controls",
    name="Financial Controls Assessment",
    category=TemplateCategory.FINANCIAL,
    description="Assessment report for financial control systems (SOC 2, internal audit).",
    regulations=["SOC 2 Type II", "SOX Section 404", "COSO Framework"],
    sections=[
        TemplateSection(
            id="control-summary",
            title="Control Assessment Summary",
            description="High-level assessment of control effectiveness.",
            receipt_fields=["verdict", "confidence", "robustness_score"],
        ),
        TemplateSection(
            id="risk-identification",
            title="Risk Identification",
            description="Identified risks to financial controls by severity.",
            receipt_fields=["risk_summary", "vulnerabilities_found"],
        ),
        TemplateSection(
            id="control-testing",
            title="Control Testing Results",
            description="Results of control testing procedures.",
            receipt_fields=["attacks_attempted", "attacks_successful", "probes_run"],
        ),
        TemplateSection(
            id="deficiencies",
            title="Control Deficiencies",
            description="Identified control deficiencies requiring remediation.",
            receipt_fields=["vulnerability_details"],
        ),
        TemplateSection(
            id="management-response",
            title="Management Response",
            description="Space for management remediation plans.",
            receipt_fields=["verdict_reasoning"],
        ),
        TemplateSection(
            id="evidence-support",
            title="Supporting Evidence",
            description="Evidence supporting the assessment conclusions.",
            receipt_fields=["provenance_chain", "consensus_proof"],
        ),
    ],
    disclaimer=(
        "This assessment is intended to support internal control evaluation and "
        "should not be relied upon as a substitute for formal SOC 2 or SOX audits. "
        "Conclusions should be validated by qualified auditors."
    ),
)

# Operational template for DevOps/SRE teams
OPERATIONAL_TEMPLATE = AuditTemplate(
    id="operational-review",
    name="Operational Review Report",
    category=TemplateCategory.OPERATIONAL,
    description="Technical operational review for DevOps and SRE teams.",
    sections=[
        TemplateSection(
            id="summary",
            title="Validation Summary",
            description="Quick overview for operational decision-making.",
            receipt_fields=["verdict", "confidence", "robustness_score"],
        ),
        TemplateSection(
            id="issue-breakdown",
            title="Issue Breakdown",
            description="Issues categorized by severity for prioritization.",
            receipt_fields=["risk_summary", "vulnerabilities_found"],
        ),
        TemplateSection(
            id="coverage-metrics",
            title="Coverage Metrics",
            description="Validation coverage statistics.",
            receipt_fields=["attacks_attempted", "attacks_successful", "probes_run"],
        ),
        TemplateSection(
            id="action-items",
            title="Action Items",
            description="Prioritized action items for remediation.",
            receipt_fields=["vulnerability_details"],
        ),
        TemplateSection(
            id="traceability",
            title="Traceability",
            description="Identifiers for tracking and correlation.",
            receipt_fields=["receipt_id", "gauntlet_id", "timestamp"],
        ),
    ],
    disclaimer="",
)

# =============================================================================
# Template Registry
# =============================================================================

_TEMPLATE_REGISTRY: Dict[str, AuditTemplate] = {
    "compliance-standard": COMPLIANCE_TEMPLATE,
    "security-assessment": SECURITY_TEMPLATE,
    "legal-review": LEGAL_TEMPLATE,
    "financial-controls": FINANCIAL_TEMPLATE,
    "operational-review": OPERATIONAL_TEMPLATE,
}


def get_template(template_id: str) -> Optional[AuditTemplate]:
    """
    Get a template by ID.

    Args:
        template_id: Template identifier

    Returns:
        AuditTemplate or None if not found
    """
    return _TEMPLATE_REGISTRY.get(template_id)


def list_templates(category: Optional[TemplateCategory] = None) -> List[AuditTemplate]:
    """
    List all available templates.

    Args:
        category: Optional category filter

    Returns:
        List of AuditTemplate objects
    """
    templates = list(_TEMPLATE_REGISTRY.values())
    if category:
        templates = [t for t in templates if t.category == category]
    return templates


def register_template(template: AuditTemplate) -> None:
    """
    Register a custom template.

    Args:
        template: AuditTemplate to register
    """
    _TEMPLATE_REGISTRY[template.id] = template


def create_custom_template(
    id: str,
    name: str,
    sections: List[Dict[str, Any]],
    category: TemplateCategory = TemplateCategory.CUSTOM,
    description: str = "",
    regulations: Optional[List[str]] = None,
    disclaimer: str = "",
) -> AuditTemplate:
    """
    Create a custom audit template.

    Args:
        id: Unique template identifier
        name: Human-readable name
        sections: List of section definitions
        category: Template category
        description: Template description
        regulations: Applicable regulations
        disclaimer: Template disclaimer

    Returns:
        New AuditTemplate instance
    """
    template_sections = [
        TemplateSection(
            id=s.get("id", f"section-{i}"),
            title=s.get("title", f"Section {i+1}"),
            description=s.get("description", ""),
            required=s.get("required", True),
            receipt_fields=s.get("receipt_fields", []),
        )
        for i, s in enumerate(sections)
    ]

    return AuditTemplate(
        id=id,
        name=name,
        category=category,
        description=description,
        sections=template_sections,
        regulations=regulations or [],
        disclaimer=disclaimer,
    )


__all__ = [
    # Classes
    "AuditTemplate",
    "TemplateSection",
    "TemplateCategory",
    "TemplateFormat",
    # Pre-built templates
    "COMPLIANCE_TEMPLATE",
    "SECURITY_TEMPLATE",
    "LEGAL_TEMPLATE",
    "FINANCIAL_TEMPLATE",
    "OPERATIONAL_TEMPLATE",
    # Functions
    "get_template",
    "list_templates",
    "register_template",
    "create_custom_template",
]
