"""
Aragora Python SDK

Official Python client for the Aragora multi-agent debate platform.

Usage::

    from aragora import AragoraClient, Debate, DebateCreateRequest

    client = AragoraClient(api_key="your-key")
    debate = client.debates.create(DebateCreateRequest(task="Evaluate options"))

All generated Pydantic types are re-exported here for convenient access.
"""

from .client import AragoraAsyncClient, AragoraClient
from .exceptions import (
    AragoraError,
    AuthenticationError,
    AuthorizationError,
    ConnectionError,
    NotFoundError,
    RateLimitError,
    ServerError,
    TimeoutError,
    ValidationError,
)
from .generated_types import (
    # --- Enums ---
    BudgetAction,
    BudgetPeriod,
    BudgetStatus,
    Code,
    Consensus,
    DebateStatus,
    Event,
    PatternType,
    ReviewType,
    Role,
    Status,
    Status2,
    TrendingCategory,
    Type,
    Type1,
    # --- Core debate types ---
    Agent,
    AutoSelectConfig,
    Calibration,
    Consensus1,
    ConsensusResult,
    Debate,
    DebateCreateRequest,
    DebateCreateResponse,
    Error,
    HealthCheck,
    Message,
    OAuthProvider,
    OAuthProviders,
    PaginatedResponse,
    Relationship,
    Round,
    StandardSuccessResponse,
    # --- Workspace types ---
    Workspace,
    WorkspaceList,
    # --- Retention types ---
    RetentionPolicy,
    RetentionPolicyList,
    # --- Workflow types ---
    ExecutionList,
    StepDefinition,
    TransitionRule,
    Workflow,
    WorkflowList,
    WorkflowTemplate,
    WorkflowTemplateList,
    WorkflowUpdate,
    # --- Gauntlet & receipt types ---
    DecisionReceipt,
    ReceiptList,
    RiskHeatmap,
    HeatmapList,
    # --- Pattern types ---
    PatternTemplate,
    PatternTemplateList,
    # --- Checkpoint types ---
    CheckpointList,
    CheckpointMetadata,
    RestoreResult,
    # --- Explainability types ---
    Counterfactual,
    DecisionExplanation,
    Factor,
    ProvenanceItem,
    # --- Control plane types ---
    ControlPlaneAgent,
    ControlPlaneAgentList,
    ControlPlaneHealth,
    ControlPlaneMetrics,
    ControlPlaneQueue,
    ControlPlaneQueueJob,
    ControlPlaneStats,
    ControlPlaneTask,
    ControlPlaneTaskClaimResponse,
    ControlPlaneTaskCreated,
    # --- Codebase / vulnerability types ---
    CodebaseCVEResponse,
    CodebaseDependencyAnalysisRequest,
    CodebaseDependencyAnalysisResponse,
    CodebaseDependencyScanRequest,
    CodebaseDependencyScanResponse,
    CodebaseDuplicateListResponse,
    CodebaseFileMetricsResponse,
    CodebaseHotspot,
    CodebaseHotspotListResponse,
    CodebaseLicenseCheckRequest,
    CodebaseLicenseCheckResponse,
    CodebaseMetricsHistoryResponse,
    CodebaseMetricsReportResponse,
    CodebaseMetricsStartResponse,
    CodebasePackageVulnerabilityResponse,
    CodebaseSBOMRequest,
    CodebaseSBOMResponse,
    CodebaseScanListResponse,
    CodebaseScanResult,
    CodebaseScanResultResponse,
    CodebaseScanStartResponse,
    CodebaseScanSummary,
    CodebaseSecretsScanListResponse,
    CodebaseSecretsScanRequest,
    CodebaseSecretsScanResultResponse,
    CodebaseSecretsScanStartResponse,
    CodebaseSecretsListResponse,
    CodebaseVulnerabilityListResponse,
    DependencyInfo,
    VulnerabilityFinding,
    VulnerabilityReference,
    # --- Decision / deliberation types ---
    DecisionList,
    DecisionRequest,
    DecisionResult,
    DecisionStatus,
    DecisionSummary,
    DeliberationQueuedResponse,
    DeliberationRecord,
    DeliberationRequest,
    DeliberationStatus,
    DeliberationSyncResponse,
    # --- GitHub code review types ---
    ChangedFile,
    Comment,
    GitHubPRDetails,
    GitHubPRDetailsResponse,
    GitHubPRReviewListResponse,
    GitHubPRReviewResult,
    GitHubPRReviewStatusResponse,
    GitHubPRReviewTriggerRequest,
    GitHubPRReviewTriggerResponse,
    GitHubPRSubmitReviewRequest,
    GitHubPRSubmitReviewResponse,
    GitHubReviewComment,
    # --- Cost management types ---
    CostAlert,
    CostAlertsResponse,
    CostBreakdownItem,
    CostBreakdownResponse,
    CostBudgetRequest,
    CostBudgetResponse,
    CostDailyItem,
    CostDismissAlertResponse,
    CostSummaryResponse,
    CostTimelineResponse,
    # --- Shared inbox types ---
    RoutingRule,
    RoutingRuleCreateRequest,
    RoutingRuleDeleteResponse,
    RoutingRuleListResponse,
    RoutingRuleResponse,
    RoutingRuleTestRequest,
    RoutingRuleTestResponse,
    RoutingRuleUpdateRequest,
    SharedInbox,
    SharedInboxAssignRequest,
    SharedInboxCreateRequest,
    SharedInboxListResponse,
    SharedInboxMessage,
    SharedInboxMessageListResponse,
    SharedInboxMessageResponse,
    SharedInboxResponse,
    SharedInboxStatusRequest,
    SharedInboxTagRequest,
    # --- Budget types ---
    Budget,
    BudgetAlert,
    BudgetAlertListResponse,
    BudgetCheckRequest,
    BudgetCheckResponse,
    BudgetCreateRequest,
    BudgetListResponse,
    BudgetOverrideRequest,
    BudgetOverrideResponse,
    BudgetSummary,
    BudgetThreshold,
    BudgetUpdateRequest,
    # --- Analytics / stats types ---
    ByAgent,
    ByTier,
    DisagreementStats,
    EarlyStopStats,
    MemoryStats,
    RankingStats,
    RoleRotationStats,
    # --- Knowledge types ---
    KnowledgeNode,
    KnowledgeQueryResult,
    KnowledgeStoreResult,
    # --- Agent registration types ---
    AgentRegistration,
    PolicyEvaluation,
    TaskStatus,
    # --- Flip & insight types ---
    FlipsRecent,
    FlipsSummary,
    Insight,
    InsightsDetailed,
    InsightsRecent,
    PositionFlip,
    # --- Moments types ---
    DebateMoment,
    MomentsByType,
    MomentsSummary,
    MomentsTimeline,
    MomentsTrending,
    TopDebate,
)

__version__ = "0.1.0"
__all__ = [
    # --- Client ---
    "AragoraClient",
    "AragoraAsyncClient",
    # --- Exceptions ---
    "AragoraError",
    "AuthenticationError",
    "AuthorizationError",
    "ConnectionError",
    "NotFoundError",
    "RateLimitError",
    "ServerError",
    "TimeoutError",
    "ValidationError",
    # --- Enums ---
    "BudgetAction",
    "BudgetPeriod",
    "BudgetStatus",
    "Code",
    "Consensus",
    "DebateStatus",
    "Event",
    "PatternType",
    "ReviewType",
    "Role",
    "Status",
    "Status2",
    "TrendingCategory",
    "Type",
    "Type1",
    # --- Core debate types ---
    "Agent",
    "AutoSelectConfig",
    "Calibration",
    "Consensus1",
    "ConsensusResult",
    "Debate",
    "DebateCreateRequest",
    "DebateCreateResponse",
    "Error",
    "HealthCheck",
    "Message",
    "OAuthProvider",
    "OAuthProviders",
    "PaginatedResponse",
    "Relationship",
    "Round",
    "StandardSuccessResponse",
    # --- Workspace types ---
    "Workspace",
    "WorkspaceList",
    # --- Retention types ---
    "RetentionPolicy",
    "RetentionPolicyList",
    # --- Workflow types ---
    "ExecutionList",
    "StepDefinition",
    "TransitionRule",
    "Workflow",
    "WorkflowList",
    "WorkflowTemplate",
    "WorkflowTemplateList",
    "WorkflowUpdate",
    # --- Gauntlet & receipt types ---
    "DecisionReceipt",
    "ReceiptList",
    "RiskHeatmap",
    "HeatmapList",
    # --- Pattern types ---
    "PatternTemplate",
    "PatternTemplateList",
    # --- Checkpoint types ---
    "CheckpointList",
    "CheckpointMetadata",
    "RestoreResult",
    # --- Explainability types ---
    "Counterfactual",
    "DecisionExplanation",
    "Factor",
    "ProvenanceItem",
    # --- Control plane types ---
    "ControlPlaneAgent",
    "ControlPlaneAgentList",
    "ControlPlaneHealth",
    "ControlPlaneMetrics",
    "ControlPlaneQueue",
    "ControlPlaneQueueJob",
    "ControlPlaneStats",
    "ControlPlaneTask",
    "ControlPlaneTaskClaimResponse",
    "ControlPlaneTaskCreated",
    # --- Codebase / vulnerability types ---
    "CodebaseCVEResponse",
    "CodebaseDependencyAnalysisRequest",
    "CodebaseDependencyAnalysisResponse",
    "CodebaseDependencyScanRequest",
    "CodebaseDependencyScanResponse",
    "CodebaseDuplicateListResponse",
    "CodebaseFileMetricsResponse",
    "CodebaseHotspot",
    "CodebaseHotspotListResponse",
    "CodebaseLicenseCheckRequest",
    "CodebaseLicenseCheckResponse",
    "CodebaseMetricsHistoryResponse",
    "CodebaseMetricsReportResponse",
    "CodebaseMetricsStartResponse",
    "CodebasePackageVulnerabilityResponse",
    "CodebaseSBOMRequest",
    "CodebaseSBOMResponse",
    "CodebaseScanListResponse",
    "CodebaseScanResult",
    "CodebaseScanResultResponse",
    "CodebaseScanStartResponse",
    "CodebaseScanSummary",
    "CodebaseSecretsScanListResponse",
    "CodebaseSecretsScanRequest",
    "CodebaseSecretsScanResultResponse",
    "CodebaseSecretsScanStartResponse",
    "CodebaseSecretsListResponse",
    "CodebaseVulnerabilityListResponse",
    "DependencyInfo",
    "VulnerabilityFinding",
    "VulnerabilityReference",
    # --- Decision / deliberation types ---
    "DecisionList",
    "DecisionRequest",
    "DecisionResult",
    "DecisionStatus",
    "DecisionSummary",
    "DeliberationQueuedResponse",
    "DeliberationRecord",
    "DeliberationRequest",
    "DeliberationStatus",
    "DeliberationSyncResponse",
    # --- GitHub code review types ---
    "ChangedFile",
    "Comment",
    "GitHubPRDetails",
    "GitHubPRDetailsResponse",
    "GitHubPRReviewListResponse",
    "GitHubPRReviewResult",
    "GitHubPRReviewStatusResponse",
    "GitHubPRReviewTriggerRequest",
    "GitHubPRReviewTriggerResponse",
    "GitHubPRSubmitReviewRequest",
    "GitHubPRSubmitReviewResponse",
    "GitHubReviewComment",
    # --- Cost management types ---
    "CostAlert",
    "CostAlertsResponse",
    "CostBreakdownItem",
    "CostBreakdownResponse",
    "CostBudgetRequest",
    "CostBudgetResponse",
    "CostDailyItem",
    "CostDismissAlertResponse",
    "CostSummaryResponse",
    "CostTimelineResponse",
    # --- Shared inbox types ---
    "RoutingRule",
    "RoutingRuleCreateRequest",
    "RoutingRuleDeleteResponse",
    "RoutingRuleListResponse",
    "RoutingRuleResponse",
    "RoutingRuleTestRequest",
    "RoutingRuleTestResponse",
    "RoutingRuleUpdateRequest",
    "SharedInbox",
    "SharedInboxAssignRequest",
    "SharedInboxCreateRequest",
    "SharedInboxListResponse",
    "SharedInboxMessage",
    "SharedInboxMessageListResponse",
    "SharedInboxMessageResponse",
    "SharedInboxResponse",
    "SharedInboxStatusRequest",
    "SharedInboxTagRequest",
    # --- Budget types ---
    "Budget",
    "BudgetAlert",
    "BudgetAlertListResponse",
    "BudgetCheckRequest",
    "BudgetCheckResponse",
    "BudgetCreateRequest",
    "BudgetListResponse",
    "BudgetOverrideRequest",
    "BudgetOverrideResponse",
    "BudgetSummary",
    "BudgetThreshold",
    "BudgetUpdateRequest",
    # --- Analytics / stats types ---
    "ByAgent",
    "ByTier",
    "DisagreementStats",
    "EarlyStopStats",
    "MemoryStats",
    "RankingStats",
    "RoleRotationStats",
    # --- Knowledge types ---
    "KnowledgeNode",
    "KnowledgeQueryResult",
    "KnowledgeStoreResult",
    # --- Agent registration types ---
    "AgentRegistration",
    "PolicyEvaluation",
    "TaskStatus",
    # --- Flip & insight types ---
    "FlipsRecent",
    "FlipsSummary",
    "Insight",
    "InsightsDetailed",
    "InsightsRecent",
    "PositionFlip",
    # --- Moments types ---
    "DebateMoment",
    "MomentsByType",
    "MomentsSummary",
    "MomentsTimeline",
    "MomentsTrending",
    "TopDebate",
]
