# Aragora AI Code Review - GitHub Actions Workflow
#
# Add this file to your repository at: .github/workflows/aragora-review.yml
#
# Prerequisites:
#   1. Add at least one API key as a GitHub Secret:
#      - ANTHROPIC_API_KEY (recommended)
#      - OPENAI_API_KEY
#   2. Ensure GITHUB_TOKEN has permission to comment on PRs (default for most repos)
#
# For full setup instructions, see: docs/GITHUB_ACTION_SETUP.md

name: Aragora AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

# Cancel in-progress reviews when a new commit is pushed
concurrency:
  group: aragora-review-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    name: AI Code Review
    runs-on: ubuntu-latest
    # Skip drafts and bot PRs
    if: github.event.pull_request.draft == false && github.actor != 'dependabot[bot]'

    steps:
      - name: Run Aragora Review
        id: review
        uses: an0mium/aragora@main
        with:
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          agents: 'anthropic-api,openai-api'
          rounds: '2'
          focus: 'security,performance,quality'
          post-comment: 'true'
          fail-on-critical: 'false'

      - name: Review Summary
        if: always()
        run: |
          echo "### Review Results" >> $GITHUB_STEP_SUMMARY
          echo "- Unanimous issues: ${{ steps.review.outputs.unanimous-count }}" >> $GITHUB_STEP_SUMMARY
          echo "- Critical issues: ${{ steps.review.outputs.critical-count }}" >> $GITHUB_STEP_SUMMARY
          echo "- High issues: ${{ steps.review.outputs.high-count }}" >> $GITHUB_STEP_SUMMARY
          echo "- Medium issues: ${{ steps.review.outputs.medium-count }}" >> $GITHUB_STEP_SUMMARY
          echo "- Low issues: ${{ steps.review.outputs.low-count }}" >> $GITHUB_STEP_SUMMARY
          echo "- Total issues: ${{ steps.review.outputs.total-count }}" >> $GITHUB_STEP_SUMMARY
          echo "- Risk areas: ${{ steps.review.outputs.risk-areas-count }}" >> $GITHUB_STEP_SUMMARY
          echo "- Split opinions: ${{ steps.review.outputs.split-opinions-count }}" >> $GITHUB_STEP_SUMMARY
          echo "- Agreement score: ${{ steps.review.outputs.agreement-score }}" >> $GITHUB_STEP_SUMMARY
