name: 'Aragora AI Code Review'
description: 'Multi-agent AI red team code review for pull requests'
author: 'Aragora'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  agents:
    description: 'Comma-separated list of agents (anthropic-api,openai-api)'
    required: false
    default: 'anthropic-api,openai-api'
  rounds:
    description: 'Number of debate rounds'
    required: false
    default: '2'
  focus:
    description: 'Focus areas (security,performance,quality)'
    required: false
    default: 'security,performance,quality'
  anthropic-api-key:
    description: 'Anthropic API key for Claude'
    required: false
  openai-api-key:
    description: 'OpenAI API key for GPT'
    required: false
  openrouter-api-key:
    description: 'OpenRouter API key (fallback provider)'
    required: false
  post-comment:
    description: 'Post review as PR comment'
    required: false
    default: 'true'
  fail-on-critical:
    description: 'Fail workflow if critical issues found'
    required: false
    default: 'false'
  max-diff-size:
    description: 'Maximum diff size in bytes'
    required: false
    default: '50000'
  failure-threshold:
    description: 'Fail workflow if total issues exceed this count (0 = disabled)'
    required: false
    default: '0'
  output-format:
    description: 'Additional output format besides PR comment (sarif, json, none)'
    required: false
    default: 'none'
  sarif-upload:
    description: 'Upload SARIF to GitHub Security tab'
    required: false
    default: 'false'

outputs:
  review-path:
    description: 'Path to the generated review file'
    value: ${{ steps.review.outputs.review_path }}
  review-generated:
    description: 'Whether a review comment was generated'
    value: ${{ steps.review.outputs.review_generated }}
  review-json-path:
    description: 'Path to the generated JSON review file'
    value: ${{ steps.review.outputs.review_json_path }}
  review-log-path:
    description: 'Path to the review log file'
    value: ${{ steps.review.outputs.review_log_path }}
  unanimous-count:
    description: 'Number of unanimous issues found'
    value: ${{ steps.review.outputs.unanimous_count }}
  critical-count:
    description: 'Number of critical issues found'
    value: ${{ steps.review.outputs.critical_count }}
  high-count:
    description: 'Number of high severity issues found'
    value: ${{ steps.review.outputs.high_count }}
  medium-count:
    description: 'Number of medium severity issues found'
    value: ${{ steps.review.outputs.medium_count }}
  low-count:
    description: 'Number of low severity issues found'
    value: ${{ steps.review.outputs.low_count }}
  total-count:
    description: 'Total number of severity-tagged issues (critical+high+medium+low)'
    value: ${{ steps.review.outputs.total_count }}
  risk-areas-count:
    description: 'Number of risk areas noted'
    value: ${{ steps.review.outputs.risk_areas_count }}
  split-opinions-count:
    description: 'Number of split-opinion items (agent disagreement)'
    value: ${{ steps.review.outputs.split_opinions_count }}
  agreement-score:
    description: 'Agent agreement score (0-1)'
    value: ${{ steps.review.outputs.agreement_score }}
  sarif-path:
    description: 'Path to SARIF output file (if generated)'
    value: ${{ steps.review.outputs.sarif_path }}

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install Aragora
      shell: bash
      run: |
        pip install --upgrade pip
        pip install aragora

    - name: Get PR diff
      id: diff
      shell: bash
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        gh pr diff $PR_NUMBER > pr.diff

        # Truncate if needed
        DIFF_SIZE=$(wc -c < pr.diff)
        MAX_SIZE=${{ inputs.max-diff-size }}
        if [ "$DIFF_SIZE" -gt "$MAX_SIZE" ]; then
          head -c $MAX_SIZE pr.diff > pr_truncated.diff
          echo -e "\n[... diff truncated ...]" >> pr_truncated.diff
          mv pr_truncated.diff pr.diff
        fi

        echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Run Aragora review
      id: review
      shell: bash
      run: |
        mkdir -p ./aragora-artifacts

        # Run review with github format for PR comment
        aragora review \
          --diff-file pr.diff \
          --output-format github \
          --output-dir ./aragora-artifacts \
          --agents "${{ inputs.agents }}" \
          --rounds ${{ inputs.rounds }} \
          --focus "${{ inputs.focus }}" \
          > ./aragora-artifacts/comment.md 2> ./aragora-artifacts/review.log || true

        # Also generate JSON output for structured data extraction
        aragora review \
          --diff-file pr.diff \
          --output-format json \
          --output-dir ./aragora-artifacts \
          --agents "${{ inputs.agents }}" \
          --rounds ${{ inputs.rounds }} \
          --focus "${{ inputs.focus }}" \
          > /dev/null 2>> ./aragora-artifacts/review.log || true

        # Generate SARIF output if requested
        if [ "${{ inputs.output-format }}" = "sarif" ]; then
          aragora review \
            --diff-file pr.diff \
            --output-format json \
            --output-dir ./aragora-artifacts \
            --agents "${{ inputs.agents }}" \
            --rounds ${{ inputs.rounds }} \
            --focus "${{ inputs.focus }}" \
            --sarif ./aragora-artifacts/review.sarif \
            > /dev/null 2>> ./aragora-artifacts/review.log || true

          if [ -f "./aragora-artifacts/review.sarif" ]; then
            echo "sarif_path=./aragora-artifacts/review.sarif" >> $GITHUB_OUTPUT
          else
            echo "sarif_path=" >> $GITHUB_OUTPUT
          fi
        else
          echo "sarif_path=" >> $GITHUB_OUTPUT
        fi

        if [ -f "./aragora-artifacts/comment.md" ] && [ -s "./aragora-artifacts/comment.md" ]; then
          echo "review_path=./aragora-artifacts/comment.md" >> $GITHUB_OUTPUT
          echo "review_generated=true" >> $GITHUB_OUTPUT
        else
          echo "review_generated=false" >> $GITHUB_OUTPUT
        fi

        # Action-level metadata and extracted counts from JSON output
        echo "review_log_path=./aragora-artifacts/review.log" >> $GITHUB_OUTPUT

        python3 - <<'PY' >> "$GITHUB_OUTPUT"
import json
from pathlib import Path

path = Path("./aragora-artifacts/review.json")
if path.is_file():
    print("review_json_path=./aragora-artifacts/review.json")
    try:
        data = json.loads(path.read_text())
    except Exception:
        data = {}
else:
    print("review_json_path=")
    data = {}

def count_list(key: str) -> int:
    value = data.get(key, [])
    return len(value) if isinstance(value, list) else 0

unanimous = count_list("unanimous_critiques")
critical = count_list("critical_issues")
high = count_list("high_issues")
medium = count_list("medium_issues")
low = count_list("low_issues")
risk_areas = count_list("risk_areas")
split_opinions = count_list("split_opinions")
total = critical + high + medium + low

agreement = data.get("agreement_score", 0) or 0
try:
    agreement = float(agreement)
except Exception:
    agreement = 0

print(f"unanimous_count={unanimous}")
print(f"critical_count={critical}")
print(f"high_count={high}")
print(f"medium_count={medium}")
print(f"low_count={low}")
print(f"total_count={total}")
print(f"risk_areas_count={risk_areas}")
print(f"split_opinions_count={split_opinions}")
print(f"agreement_score={agreement}")
PY
      env:
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
        OPENAI_API_KEY: ${{ inputs.openai-api-key }}
        OPENROUTER_API_KEY: ${{ inputs.openrouter-api-key }}

    - name: Post PR comment
      if: inputs.post-comment == 'true' && steps.review.outputs.review_generated == 'true'
      shell: bash
      run: |
        gh pr comment ${{ steps.diff.outputs.pr_number }} --body-file ./aragora-artifacts/comment.md
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Upload SARIF
      if: inputs.sarif-upload == 'true' && steps.review.outputs.sarif_path != ''
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.review.outputs.sarif_path }}

    - name: Check for critical issues
      if: inputs.fail-on-critical == 'true' && steps.review.outputs.critical_count != '0'
      shell: bash
      run: |
        echo "::error::Critical issues found in code review"
        exit 1

    - name: Check failure threshold
      if: inputs.failure-threshold != '0'
      shell: bash
      run: |
        TOTAL=${{ steps.review.outputs.total_count }}
        THRESHOLD=${{ inputs.failure-threshold }}
        if [ "$TOTAL" -ge "$THRESHOLD" ]; then
          echo "::error::Issue count ($TOTAL) exceeds threshold ($THRESHOLD)"
          exit 1
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: aragora-review-${{ steps.diff.outputs.pr_number }}
        path: ./aragora-artifacts/
        retention-days: 30
