name: 'Aragora AI Code Review'
description: 'Multi-agent AI red team code review for pull requests'
author: 'Aragora'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  agents:
    description: 'Comma-separated list of agents (anthropic-api,openai-api)'
    required: false
    default: 'anthropic-api,openai-api'
  rounds:
    description: 'Number of debate rounds'
    required: false
    default: '2'
  focus:
    description: 'Focus areas (security,performance,quality)'
    required: false
    default: 'security,performance,quality'
  anthropic-api-key:
    description: 'Anthropic API key for Claude'
    required: false
  openai-api-key:
    description: 'OpenAI API key for GPT'
    required: false
  openrouter-api-key:
    description: 'OpenRouter API key (fallback provider)'
    required: false
  post-comment:
    description: 'Post review as PR comment'
    required: false
    default: 'true'
  fail-on-critical:
    description: 'Fail workflow if critical issues found'
    required: false
    default: 'false'
  max-diff-size:
    description: 'Maximum diff size in bytes'
    required: false
    default: '50000'

outputs:
  review-path:
    description: 'Path to the generated review file'
    value: ${{ steps.review.outputs.review_path }}
  unanimous-count:
    description: 'Number of unanimous issues found'
    value: ${{ steps.review.outputs.unanimous_count }}
  critical-count:
    description: 'Number of critical issues found'
    value: ${{ steps.review.outputs.critical_count }}
  agreement-score:
    description: 'Agent agreement score (0-1)'
    value: ${{ steps.review.outputs.agreement_score }}

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install Aragora
      shell: bash
      run: |
        pip install --upgrade pip
        pip install aragora

    - name: Get PR diff
      id: diff
      shell: bash
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        gh pr diff $PR_NUMBER > pr.diff

        # Truncate if needed
        DIFF_SIZE=$(wc -c < pr.diff)
        MAX_SIZE=${{ inputs.max-diff-size }}
        if [ "$DIFF_SIZE" -gt "$MAX_SIZE" ]; then
          head -c $MAX_SIZE pr.diff > pr_truncated.diff
          echo -e "\n[... diff truncated ...]" >> pr_truncated.diff
          mv pr_truncated.diff pr.diff
        fi

        echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Run Aragora review
      id: review
      shell: bash
      run: |
        mkdir -p ./aragora-artifacts

        aragora review \
          --diff-file pr.diff \
          --output-format github \
          --output-dir ./aragora-artifacts \
          --agents "${{ inputs.agents }}" \
          --rounds ${{ inputs.rounds }} \
          --focus "${{ inputs.focus }}" \
          > ./aragora-artifacts/comment.md 2> ./aragora-artifacts/review.log || true

        if [ -f "./aragora-artifacts/comment.md" ] && [ -s "./aragora-artifacts/comment.md" ]; then
          echo "review_path=./aragora-artifacts/comment.md" >> $GITHUB_OUTPUT
          echo "review_generated=true" >> $GITHUB_OUTPUT
        else
          echo "review_generated=false" >> $GITHUB_OUTPUT
        fi

        echo "unanimous_count=0" >> $GITHUB_OUTPUT
        echo "critical_count=0" >> $GITHUB_OUTPUT
        echo "agreement_score=0" >> $GITHUB_OUTPUT
      env:
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
        OPENAI_API_KEY: ${{ inputs.openai-api-key }}
        OPENROUTER_API_KEY: ${{ inputs.openrouter-api-key }}

    - name: Post PR comment
      if: inputs.post-comment == 'true' && steps.review.outputs.review_generated == 'true'
      shell: bash
      run: |
        gh pr comment ${{ steps.diff.outputs.pr_number }} --body-file ./aragora-artifacts/comment.md
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Check for critical issues
      if: inputs.fail-on-critical == 'true' && steps.review.outputs.critical_count != '0'
      shell: bash
      run: |
        echo "::error::Critical issues found in code review"
        exit 1

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: aragora-review-${{ steps.diff.outputs.pr_number }}
        path: ./aragora-artifacts/
        retention-days: 30
