"""
Accounting Connectors.

Integrations for accounting and financial services:
- QuickBooks Online (QBO)
- Plaid bank connectivity
- Gusto payroll
"""

from aragora.connectors.accounting.qbo import (
    QuickBooksConnector,
    QBOCredentials,
    QBOEnvironment,
    QBOCustomer,
    QBOTransaction,
    QBOAccount,
    TransactionType,
    get_mock_customers,
    get_mock_transactions,
)
from aragora.connectors.accounting.plaid import (
    PlaidConnector,
    PlaidCredentials,
    PlaidEnvironment,
    PlaidError,
    BankAccount,
    BankTransaction,
    AccountType,
    TransactionCategory,
    CategoryMapping,
    get_mock_accounts,
    get_mock_transactions as get_mock_bank_transactions,
)
from aragora.connectors.accounting.gusto import (
    GustoConnector,
    GustoCredentials,
    Employee,
    EmploymentType,
    PayType,
    PayrollRun,
    PayrollItem,
    PayrollStatus,
    JournalEntry,
    get_mock_employees,
    get_mock_payroll_run,
)
from aragora.connectors.accounting.xero import (
    XeroConnector,
    XeroCredentials,
    XeroContact,
    Invoice as XeroInvoice,
    Account as XeroAccount,
    BankTransaction as XeroBankTransaction,
    Payment as XeroPayment,
    ManualJournal,
    LineItem as XeroLineItem,
    JournalLine,
    Address as XeroAddress,
    XeroError,
    InvoiceType,
    InvoiceStatus,
    ContactStatus,
    AccountType as XeroAccountType,
    BankTransactionType,
    PaymentStatus as XeroPaymentStatus,
    get_mock_invoice as get_mock_xero_invoice,
    get_mock_contact as get_mock_xero_contact,
)

__all__ = [
    # QBO
    "QuickBooksConnector",
    "QBOCredentials",
    "QBOEnvironment",
    "QBOCustomer",
    "QBOTransaction",
    "QBOAccount",
    "TransactionType",
    "get_mock_customers",
    "get_mock_transactions",
    # Plaid
    "PlaidConnector",
    "PlaidCredentials",
    "PlaidEnvironment",
    "PlaidError",
    "BankAccount",
    "BankTransaction",
    "AccountType",
    "TransactionCategory",
    "CategoryMapping",
    "get_mock_accounts",
    "get_mock_bank_transactions",
    # Gusto
    "GustoConnector",
    "GustoCredentials",
    "Employee",
    "EmploymentType",
    "PayType",
    "PayrollRun",
    "PayrollItem",
    "PayrollStatus",
    "JournalEntry",
    "get_mock_employees",
    "get_mock_payroll_run",
    # Xero
    "XeroConnector",
    "XeroCredentials",
    "XeroContact",
    "XeroInvoice",
    "XeroAccount",
    "XeroBankTransaction",
    "XeroPayment",
    "ManualJournal",
    "XeroLineItem",
    "JournalLine",
    "XeroAddress",
    "XeroError",
    "InvoiceType",
    "InvoiceStatus",
    "ContactStatus",
    "XeroAccountType",
    "BankTransactionType",
    "XeroPaymentStatus",
    "get_mock_xero_invoice",
    "get_mock_xero_contact",
]
