"""
OpenAPI stability classification for Aragora endpoints.

Stability is derived from a manifest generated via SDK parity audits.
Endpoints not listed default to experimental.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import cast
from collections.abc import Iterable

STABILITY_VALUES = {"stable", "beta", "experimental", "internal", "deprecated"}
DEFAULT_STABILITY = "experimental"

_MANIFEST_PATH = Path(__file__).with_name("stability_manifest.json")
_CACHE: StabilityIndex | None = None


@dataclass(frozen=True)
class StabilityIndex:
    stable: set[tuple[str, str]]
    beta: set[tuple[str, str]]
    internal: set[tuple[str, str]]


def _normalize_path(path: str) -> str:
    path = path.split("?", 1)[0]
    if (
        path.startswith("/api/")
        and not path.startswith("/api/v1/")
        and not path.startswith("/api/v2/")
    ):
        path = path.replace("/api/", "/api/v1/", 1)
    return re.sub(r"{[^}]+}", "{param}", path)


def _parse_manifest_entries(entries: Iterable[str]) -> set[tuple[str, str]]:
    parsed: set[tuple[str, str]] = set()
    for entry in entries:
        if not isinstance(entry, str) or " " not in entry:
            continue
        method, path = entry.split(" ", 1)
        parsed.add((method.upper(), _normalize_path(path)))
    return parsed


def _load_manifest() -> StabilityIndex:
    data: dict[str, object] = {}
    if _MANIFEST_PATH.exists():
        try:
            data = json.loads(_MANIFEST_PATH.read_text())
        except (json.JSONDecodeError, OSError):
            data = {}
    # Manifest entries are expected to be lists of strings (e.g. "GET /api/v1/foo")
    stable_entries = data.get("stable", []) if isinstance(data, dict) else []
    beta_entries = data.get("beta", []) if isinstance(data, dict) else []
    internal_entries = data.get("internal", []) if isinstance(data, dict) else []

    stable = _parse_manifest_entries(
        cast(list[str], stable_entries) if isinstance(stable_entries, list) else []
    )
    beta = _parse_manifest_entries(
        cast(list[str], beta_entries) if isinstance(beta_entries, list) else []
    )
    internal = _parse_manifest_entries(
        cast(list[str], internal_entries) if isinstance(internal_entries, list) else []
    )
    return StabilityIndex(stable=stable, beta=beta, internal=internal)


def _get_index() -> StabilityIndex:
    global _CACHE
    if _CACHE is None:
        _CACHE = _load_manifest()
    return _CACHE


def resolve_stability(method: str, path: str, operation: dict[str, object]) -> str:
    """Resolve stability for a single OpenAPI operation."""
    if operation.get("deprecated") is True:
        return "deprecated"
    if operation.get("x-autogenerated") is True:
        return DEFAULT_STABILITY
    index = _get_index()
    key = (method.upper(), _normalize_path(path))
    if key in index.stable:
        return "stable"
    if key in index.beta:
        return "beta"
    if key in index.internal:
        return "internal"
    return DEFAULT_STABILITY


__all__ = [
    "DEFAULT_STABILITY",
    "STABILITY_VALUES",
    "resolve_stability",
]
