name: Bug Report
description: Report a bug in Aragora
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug. Please fill in the details below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run `aragora ask "..." --agents ...`
        2. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Output / Logs
      description: Paste any error messages or relevant logs.
      render: shell

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Aragora is affected?
      options:
        - CLI (aragora command)
        - Debate Engine
        - Gauntlet / Code Review
        - Server / API
        - Python SDK
        - TypeScript SDK
        - Connectors (Slack, Teams, etc.)
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Aragora Version
      description: Output of `aragora --version` or `pip show aragora`
      placeholder: "2.7.2"
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python Version
      placeholder: "3.11.11"

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
        - Docker
        - Other
