name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Suggest an improvement to Aragora. We prioritize features that improve decision integrity for real-world use cases.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? What use case is unmet?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this work? Include CLI commands, API shape, or code examples if applicable.
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Debate Engine
        - Gauntlet / Code Review
        - CLI
        - Server / API
        - SDK (Python or TypeScript)
        - Connectors / Integrations
        - Enterprise (Auth, RBAC, Compliance)
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any workarounds or alternative approaches you've considered.
