name: Security Vulnerability
description: Report a security issue (use private disclosure for critical vulnerabilities)
title: "[Security]: "
labels: ["security"]
body:
  - type: markdown
    attributes:
      value: |
        **For critical or high-severity vulnerabilities**, please use
        GitHub's private vulnerability reporting instead of this public form.

        This template is for lower-severity security issues, hardening
        suggestions, or security-adjacent bugs that are safe to discuss publicly.

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: |
        How severe is this issue? If Critical or High, consider using private disclosure instead.
      options:
        - Low (informational, hardening suggestion)
        - Medium (limited impact, requires specific conditions)
        - High (significant impact -- prefer private disclosure)
        - Critical (immediate risk -- use private disclosure instead)
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Vulnerability Type
      options:
        - Authentication bypass
        - Authorization / privilege escalation
        - Injection (SQL, command, template)
        - Cross-site scripting (XSS)
        - Information disclosure
        - Denial of service
        - Insecure default configuration
        - Dependency vulnerability
        - Cryptographic weakness
        - Other
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      options:
        - Authentication (OIDC, SAML, API keys)
        - Authorization (RBAC, permissions)
        - API Server
        - WebSocket Server
        - Database / Storage
        - Encryption / Key Management
        - Connectors / Integrations
        - Dependencies
        - Configuration
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the vulnerability. Do NOT include working exploits for high/critical issues.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: |
        How can this be reproduced? For low/medium severity only.
        Do not include exploit code for high/critical issues.

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: What is the potential impact if exploited?
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have a suggestion for how to fix or mitigate this?

  - type: input
    id: version
    attributes:
      label: Aragora Version
      placeholder: "e.g., 2.8.0 or git commit hash"

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: This is a low/medium severity issue safe for public discussion
          required: true
        - label: I have NOT included working exploit code for high/critical issues
          required: true
