"""Regression coverage for free-function registered OpenAPI routes."""

import ast
from pathlib import Path

from aragora.server.openapi import generate_openapi_schema
from aragora.server.openapi.endpoints.wired_registrations import (
    WIRED_REGISTRATION_ENDPOINTS,
)
from aragora.server.openapi_impl import _is_source_backed_registration


_ROOT = Path(__file__).parents[3]
_REGISTRARS = {
    "aragora/server/handlers/admin/credits.py": "register_credits_admin_routes",
    "aragora/server/handlers/inbox_command.py": "register_routes",
    "aragora/server/handlers/features/integrations.py": "register_integration_routes",
    "aragora/server/handlers/payments/plans.py": "register_payment_routes",
    "aragora/server/handlers/costs/routes.py": "register_routes",
}


def _literal_registrar_operations(source: str, function_name: str) -> set[tuple[str, str]]:
    tree = ast.parse((_ROOT / source).read_text())
    function = next(
        node
        for node in tree.body
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name == function_name
    )
    operations: set[tuple[str, str]] = set()
    for node in ast.walk(function):
        if not isinstance(node, ast.Call) or not isinstance(node.func, ast.Attribute):
            continue
        if not node.func.attr.startswith("add_") or not node.args:
            continue
        path = node.args[0]
        if isinstance(path, ast.Constant) and isinstance(path.value, str):
            operations.add((path.value, node.func.attr.removeprefix("add_")))
    return operations


def test_wired_registration_routes_survive_fresh_generation() -> None:
    paths = generate_openapi_schema()["paths"]

    assert len(WIRED_REGISTRATION_ENDPOINTS) == 57
    assert (
        sum(
            method in {"delete", "get", "patch", "post", "put"}
            for methods in WIRED_REGISTRATION_ENDPOINTS.values()
            for method in methods
        )
        == 68
    )
    for path, expected_methods in WIRED_REGISTRATION_ENDPOINTS.items():
        assert path in paths
        for method in expected_methods:
            if method.startswith("x-"):
                continue
            assert method in paths[path], f"{method.upper()} {path} missing from generated spec"


def test_wired_registration_metadata_is_explicit() -> None:
    for path, methods in WIRED_REGISTRATION_ENDPOINTS.items():
        for method, operation in methods.items():
            if method.startswith("x-"):
                continue
            assert operation["x-method-inferred"] is False
            assert operation["x-autogenerated"] is True
            assert operation["x-wired-registration"] is True
            assert operation["summary"] == f"{method.upper()} {path}"
            assert "Served route registered by" in operation["description"]


def test_unversioned_only_email_routes_do_not_gain_v1_aliases() -> None:
    paths = generate_openapi_schema()["paths"]

    assert "/api/email/daily-digest" in paths
    assert "/api/email/sender-profile" in paths
    assert "/api/v1/email/daily-digest" not in paths
    assert "/api/v1/email/sender-profile" not in paths


def test_canonical_wired_routes_do_not_inherit_legacy_metadata() -> None:
    paths = generate_openapi_schema()["paths"]

    canonical_operations = (
        ("/api/v1/inbox/actions", "post"),
        ("/api/v1/payments/authorize", "post"),
        ("/api/v1/costs/recommendations/{recommendation_id}", "get"),
    )
    for path, method in canonical_operations:
        operation = paths[path][method]
        assert operation.get("deprecated") is not True
        assert operation["x-aragora-stability"] != "deprecated"
        assert operation["summary"] != f"{method.upper()} {path.replace('/api/v1/', '/api/')}"


def test_inbox_quick_action_response_matches_runtime_shape() -> None:
    response_schema = generate_openapi_schema()["paths"]["/api/v1/inbox/actions"]["post"][
        "responses"
    ]["200"]["content"]["application/json"]["schema"]

    assert response_schema["required"] == ["success", "action", "processed", "results"]
    assert response_schema["properties"] == {
        "success": {"type": "boolean"},
        "action": {"type": "string"},
        "processed": {"type": "integer"},
        "results": {
            "type": "array",
            "items": {"type": "object", "additionalProperties": True},
        },
    }


def test_cost_recommendation_mutations_are_exported() -> None:
    paths = generate_openapi_schema()["paths"]

    for version_prefix in ("/api/", "/api/v1/"):
        for action in ("apply", "dismiss"):
            path = f"{version_prefix}costs/recommendations/{{recommendation_id}}/{action}"
            assert "post" in paths[path]


def test_wired_declarations_match_all_registrar_sources() -> None:
    for source, function_name in _REGISTRARS.items():
        registered = _literal_registrar_operations(source, function_name)
        declared = {
            (path, method)
            for path, methods in WIRED_REGISTRATION_ENDPOINTS.items()
            for method, operation in methods.items()
            if not method.startswith("x-")
            and f"registered by {source}." in operation["description"]
        }
        assert declared
        assert declared <= registered, (
            f"{source} has unserved declarations: {declared - registered}"
        )


def test_payment_webhooks_match_runtime_bearer_auth() -> None:
    paths = generate_openapi_schema()["paths"]

    for path in (
        "/api/payments/webhook/authnet",
        "/api/v1/payments/webhook/authnet",
        "/api/payments/webhook/stripe",
        "/api/v1/payments/webhook/stripe",
    ):
        assert paths[path]["post"]["security"] == [{"bearerAuth": []}]


def test_wired_operations_do_not_share_mutable_schema_objects() -> None:
    charge = WIRED_REGISTRATION_ENDPOINTS["/api/payments/charge"]["post"]
    refund = WIRED_REGISTRATION_ENDPOINTS["/api/payments/refund"]["post"]
    charge_response = charge["responses"]["200"]["content"]["application/json"]["schema"]
    charge_request = charge["requestBody"]["content"]["application/json"]["schema"]
    refund_response = refund["responses"]["200"]["content"]["application/json"]["schema"]

    assert charge_response is not charge_request
    assert charge_response is not refund_response


def test_source_backed_bypass_is_limited_to_canonical_wired_paths() -> None:
    marked = {"get": {"x-wired-registration": True}}

    assert _is_source_backed_registration("/api/admin/credits/{org_id}", marked)
    assert not _is_source_backed_registration("/api/unrelated", marked)
