from __future__ import annotations

import asyncio

from aragora.server.handlers.auth.handler import AuthHandler
from aragora.server.openapi import generate_openapi_schema


def test_admin_mfa_compliance_routes_are_curated() -> None:
    schema = generate_openapi_schema()
    paths = schema["paths"]

    expected = {
        "/api/admin/mfa/compliance": None,
        "/api/v1/admin/mfa/compliance": "getAdminMfaCompliance",
    }

    for path, operation_id in expected.items():
        operation = paths[path]["get"]
        assert operation["summary"] == "Get admin MFA compliance report"
        assert operation["tags"] == ["Admin", "MFA", "Compliance"]
        assert operation.get("x-autogenerated") is not True
        if operation_id is None:
            assert "operationId" not in operation
            assert operation.get("deprecated") is True
        else:
            assert operation["operationId"] == operation_id

        schema_properties = operation["responses"]["200"]["content"]["application/json"]["schema"][
            "properties"
        ]
        assert "total_admins" in schema_properties
        assert "compliance_pct" in schema_properties


def test_admin_mfa_compliance_routes_match_auth_handler_dispatch() -> None:
    handler = AuthHandler()

    assert handler.can_handle("/api/admin/mfa/compliance")
    assert handler.can_handle("/api/v1/admin/mfa/compliance")
    assert not handler.can_handle("/api/admin/mfa-compliance")
    assert not handler.can_handle("/api/v1/admin/mfa-compliance")

    sentinel = object()
    handler._handle_mfa_compliance = lambda request_handler: sentinel  # type: ignore[method-assign]

    result = asyncio.run(handler.handle("/api/v1/admin/mfa/compliance", {}, object(), "GET"))
    assert result is sentinel
