"""Regression coverage for free-function registered OpenAPI routes."""

from aragora.server.openapi import generate_openapi_schema
from aragora.server.openapi.endpoints.wired_registrations import (
    WIRED_REGISTRATION_ENDPOINTS,
)


def test_wired_registration_routes_survive_fresh_generation() -> None:
    paths = generate_openapi_schema()["paths"]

    assert len(WIRED_REGISTRATION_ENDPOINTS) == 39
    assert (
        sum(
            method in {"delete", "get", "patch", "post", "put"}
            for methods in WIRED_REGISTRATION_ENDPOINTS.values()
            for method in methods
        )
        == 50
    )
    for path, expected_methods in WIRED_REGISTRATION_ENDPOINTS.items():
        assert path in paths
        for method in expected_methods:
            if method.startswith("x-"):
                continue
            assert method in paths[path], f"{method.upper()} {path} missing from generated spec"


def test_wired_registration_metadata_is_explicit() -> None:
    for path, methods in WIRED_REGISTRATION_ENDPOINTS.items():
        for method, operation in methods.items():
            if method.startswith("x-"):
                continue
            assert operation["x-method-inferred"] is False
            assert operation["x-autogenerated"] is True
            assert operation["x-wired-registration"] is True
            assert operation["summary"] == f"{method.upper()} {path}"
            assert "Served route registered by" in operation["description"]


def test_unversioned_only_email_routes_do_not_gain_v1_aliases() -> None:
    paths = generate_openapi_schema()["paths"]

    assert "/api/email/daily-digest" in paths
    assert "/api/email/sender-profile" in paths
    assert "/api/v1/email/daily-digest" not in paths
    assert "/api/v1/email/sender-profile" not in paths
