#!/usr/bin/env bash
# Aragora Quickstart Installer
# Usage: curl -sSL https://get.aragora.ai | bash
# Or: bash deploy/quickstart.sh [--offline] [--port 8080]
set -euo pipefail

# Colors (degrade gracefully if no tput)
if [ -t 1 ] && command -v tput &>/dev/null && [ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]; then
    RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
    BLUE='\033[0;34m'; BOLD='\033[1m'; NC='\033[0m'
else
    RED='' GREEN='' YELLOW='' BLUE='' BOLD='' NC=''
fi
info()  { echo -e "${BLUE}[info]${NC}  $*"; }
ok()    { echo -e "${GREEN}[ok]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[warn]${NC}  $*"; }
fatal() { echo -e "${RED}[error]${NC} $*" >&2; exit 1; }

# Defaults
API_PORT=8080; WS_PORT=8765; OFFLINE=false
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" 2>/dev/null && pwd || pwd)"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --offline)    OFFLINE=true; shift ;;
        --port)       API_PORT="$2"; shift 2 ;;
        --ws-port)    WS_PORT="$2"; shift 2 ;;
        -h|--help)    echo "Usage: $(basename "$0") [--offline] [--port PORT] [--ws-port PORT]"; exit 0 ;;
        *)            fatal "Unknown option: $1 (use --help)" ;;
    esac
done

echo ""
echo -e "${BOLD}  Aragora Quickstart${NC}"
echo -e "${BOLD}  ==================${NC}"
echo ""

# Detect environment
HAS_COMPOSE=false; HAS_PYTHON=false; PYTHON_CMD=""
if command -v docker &>/dev/null && docker info &>/dev/null 2>&1; then
    docker compose version &>/dev/null 2>&1 && HAS_COMPOSE=true
fi
for cmd in python3 python; do
    if command -v "$cmd" &>/dev/null; then
        py_ver="$("$cmd" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")' 2>/dev/null || echo "0.0")"
        py_major="${py_ver%%.*}"; py_minor="${py_ver##*.}"
        if [ "$py_major" -ge 3 ] && [ "$py_minor" -ge 10 ] 2>/dev/null; then
            HAS_PYTHON=true; PYTHON_CMD="$cmd"; break
        fi
    fi
done

if [ "$HAS_COMPOSE" = true ]; then
    ok "Docker + Compose detected"; DEPLOY_MODE="docker"
elif [ "$HAS_PYTHON" = true ]; then
    ok "$PYTHON_CMD $py_ver detected"; DEPLOY_MODE="python"
else
    fatal "No runtime found. Install Docker (https://docs.docker.com/get-docker/) or Python 3.10+ (https://python.org/downloads/)"
fi

# Wait for health endpoint, return 0 on success
wait_healthy() {
    local url="http://localhost:${API_PORT}/healthz" max="$1" elapsed=0
    info "Waiting for health check..."
    while [ "$elapsed" -lt "$max" ]; do
        curl -sf "$url" >/dev/null 2>&1 && echo "" && ok "Aragora is healthy" && return 0
        sleep 3; elapsed=$((elapsed + 3)); echo -n "."
    done
    echo ""; warn "Health check not responding yet -- server may still be starting."; return 1
}

# === Docker Compose deployment ===
deploy_docker() {
    local compose_file="" work_dir=""
    if [ -f "$SCRIPT_DIR/docker-compose.yml" ]; then
        compose_file="$SCRIPT_DIR/docker-compose.yml"; work_dir="$SCRIPT_DIR"
    elif [ -f "$SCRIPT_DIR/../deploy/docker-compose.yml" ]; then
        compose_file="$(cd "$SCRIPT_DIR/../deploy" && pwd)/docker-compose.yml"
        work_dir="$(cd "$SCRIPT_DIR/../deploy" && pwd)"
    else
        work_dir="${HOME}/.aragora"; compose_file="${work_dir}/docker-compose.yml"
        mkdir -p "$work_dir"
        info "Downloading docker-compose.yml..."
        curl -sSfL "https://raw.githubusercontent.com/an0mium/aragora/main/deploy/docker-compose.yml" \
            -o "$compose_file" || fatal "Download failed"
    fi
    ok "Compose file: $compose_file"

    # Generate .env idempotently
    local env_file="${work_dir}/.env"
    if [ ! -f "$env_file" ]; then
        local token; token="$(openssl rand -hex 24 2>/dev/null || echo "qs-$(date +%s)")"
        cat > "$env_file" <<EOF
# Generated by quickstart.sh $(date -u +%Y-%m-%dT%H:%M:%SZ)
ARAGORA_API_TOKEN=${token}
ARAGORA_ENV=development
ARAGORA_ALLOWED_ORIGINS=*
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
OPENAI_API_KEY=${OPENAI_API_KEY:-}
OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
MISTRAL_API_KEY=${MISTRAL_API_KEY:-}
EOF
        ok "Created $env_file"
    else
        ok "Using existing $env_file"
    fi

    if [ "$OFFLINE" = true ]; then
        grep -q "^ARAGORA_OFFLINE=" "$env_file" 2>/dev/null || printf '\nARAGORA_OFFLINE=1\nDEMO_MODE=1\n' >> "$env_file"
        ok "Offline/demo mode enabled"
    fi

    info "Starting containers (port ${API_PORT})..."
    docker compose -f "$compose_file" --env-file "$env_file" up -d --remove-orphans 2>&1 \
        | while IFS= read -r line; do echo "  $line"; done

    wait_healthy 60 || warn "Logs: docker compose -f $compose_file logs -f backend"

    echo ""
    echo -e "${GREEN}${BOLD}  Aragora is running!${NC}"
    echo ""
    echo "  API:       http://localhost:${API_PORT}"
    echo "  WebSocket: ws://localhost:${WS_PORT}/ws"
    echo "  Health:    http://localhost:${API_PORT}/healthz"
    echo "  Frontend:  http://localhost:3000"
    echo ""
    echo -e "${BOLD}Commands:${NC}"
    echo "  Logs:    docker compose -f $compose_file logs -f"
    echo "  Stop:    docker compose -f $compose_file down"
    echo "  Restart: docker compose -f $compose_file restart"
    echo ""
    echo -e "${BOLD}Config:${NC}  $env_file"
    [ "$OFFLINE" = true ] && echo -e "${YELLOW}Running in offline demo mode.${NC}" \
                          || echo -e "${YELLOW}Add an API key to $env_file for live debates.${NC}"
    echo ""
}

# === Python deployment ===
deploy_python() {
    local base="${HOME}/.aragora" venv_dir="${HOME}/.aragora/venv"
    local pid_file="${base}/aragora.pid"
    mkdir -p "$base"

    # Stop previous instance
    if [ -f "$pid_file" ]; then
        local old_pid; old_pid="$(cat "$pid_file" 2>/dev/null || echo "")"
        if [ -n "$old_pid" ] && kill -0 "$old_pid" 2>/dev/null; then
            info "Stopping previous instance (PID $old_pid)..."
            kill "$old_pid" 2>/dev/null || true; sleep 2
        fi
        rm -f "$pid_file"
    fi

    # Create or reuse venv
    if [ ! -f "$venv_dir/bin/activate" ]; then
        info "Creating virtual environment..."
        "$PYTHON_CMD" -m venv "$venv_dir"
    fi
    ok "venv: $venv_dir"

    info "Installing aragora..."
    "$venv_dir/bin/pip" install --quiet --upgrade pip 2>&1 | tail -1
    "$venv_dir/bin/pip" install --quiet aragora 2>&1 | tail -1
    ok "Installed aragora"

    local serve_args=("--api-port" "$API_PORT" "--ws-port" "$WS_PORT")
    [ "$OFFLINE" = true ] && serve_args+=("--offline") && ok "Offline/demo mode enabled"

    info "Starting aragora serve on port ${API_PORT}..."
    nohup "$venv_dir/bin/aragora" serve "${serve_args[@]}" > "${base}/server.log" 2>&1 &
    echo "$!" > "$pid_file"

    wait_healthy 30 || warn "Check ${base}/server.log for details"

    echo ""
    echo -e "${GREEN}${BOLD}  Aragora is running!${NC}"
    echo ""
    echo "  API:       http://localhost:${API_PORT}"
    echo "  WebSocket: ws://localhost:${WS_PORT}/ws"
    echo "  Health:    http://localhost:${API_PORT}/healthz"
    echo "  Logs:      ${base}/server.log"
    echo ""
    echo -e "${BOLD}Stop:${NC}  kill \$(cat ${pid_file})"
    echo ""
}

# Main
case "$DEPLOY_MODE" in
    docker) deploy_docker ;;
    python) deploy_python ;;
esac
