"""
Advertising Platform Connectors.

Integrations for online advertising platforms:
- Google Ads (Search, Display, Shopping, YouTube)
- Meta Ads (Facebook, Instagram)
- LinkedIn Ads (B2B advertising)
- Microsoft Ads (Bing search ads)
- Twitter/X Ads (Promoted tweets, video ads)
- TikTok Ads (Video advertising)
"""

from aragora.connectors.advertising.google_ads import (
    GoogleAdsConnector,
    GoogleAdsCredentials,
    Campaign as GoogleCampaign,
    AdGroup as GoogleAdGroup,
    Ad as GoogleAd,
    Keyword as GoogleKeyword,
    CampaignMetrics,
    SearchTermMetrics,
    GoogleAdsError,
    CampaignStatus as GoogleCampaignStatus,
    CampaignType as GoogleCampaignType,
    AdGroupStatus as GoogleAdGroupStatus,
    AdStatus as GoogleAdStatus,
    KeywordMatchType as GoogleKeywordMatchType,
    BiddingStrategyType,
    get_mock_campaign as get_mock_google_campaign,
    get_mock_metrics as get_mock_google_metrics,
)
from aragora.connectors.advertising.meta_ads import (
    MetaAdsConnector,
    MetaAdsCredentials,
    AdAccount,
    Campaign as MetaCampaign,
    AdSet,
    Ad as MetaAd,
    AdCreative,
    AdInsights,
    CustomAudience,
    MetaAdsError,
    CampaignStatus as MetaCampaignStatus,
    CampaignObjective,
    AdSetStatus,
    AdStatus as MetaAdStatus,
    OptimizationGoal as MetaOptimizationGoal,
    BillingEvent as MetaBillingEvent,
    Placement as MetaPlacement,
)
from aragora.connectors.advertising.linkedin_ads import (
    LinkedInAdsConnector,
    LinkedInAdsCredentials,
    CampaignGroup,
    Campaign as LinkedInCampaign,
    Creative,
    AdAnalytics,
    LeadGenForm,
    Lead,
    AudienceSegment,
    LinkedInAdsError,
    CampaignStatus as LinkedInCampaignStatus,
    CampaignType as LinkedInCampaignType,
    ObjectiveType,
    AdFormat,
    BidStrategy,
    get_mock_campaign as get_mock_linkedin_campaign,
    get_mock_analytics as get_mock_linkedin_analytics,
)
from aragora.connectors.advertising.microsoft_ads import (
    MicrosoftAdsConnector,
    MicrosoftAdsCredentials,
    Campaign as MicrosoftCampaign,
    AdGroup as MicrosoftAdGroup,
    ResponsiveSearchAd,
    Keyword as MicrosoftKeyword,
    CampaignPerformance,
    AudienceList,
    ConversionGoal,
    NegativeKeyword,
    MicrosoftAdsError,
    CampaignStatus as MicrosoftCampaignStatus,
    CampaignType as MicrosoftCampaignType,
    BudgetType,
    BiddingScheme,
    AdGroupStatus as MicrosoftAdGroupStatus,
    AdStatus as MicrosoftAdStatus,
    AdType as MicrosoftAdType,
    KeywordMatchType as MicrosoftKeywordMatchType,
    KeywordStatus,
    get_mock_campaign as get_mock_microsoft_campaign,
    get_mock_performance as get_mock_microsoft_performance,
)
from aragora.connectors.advertising.twitter_ads import (
    TwitterAdsConnector,
    TwitterAdsCredentials,
    Campaign as TwitterCampaign,
    LineItem as TwitterLineItem,
    PromotedTweet,
    FundingInstrument,
    CampaignAnalytics as TwitterCampaignAnalytics,
    TailoredAudience,
    TwitterAdsError,
    CampaignStatus as TwitterCampaignStatus,
    CampaignObjective as TwitterCampaignObjective,
    LineItemType,
    PlacementType,
    get_mock_campaign as get_mock_twitter_campaign,
    get_mock_analytics as get_mock_twitter_analytics,
)
from aragora.connectors.advertising.tiktok_ads import (
    TikTokAdsConnector,
    TikTokAdsCredentials,
    Campaign as TikTokCampaign,
    AdGroup as TikTokAdGroup,
    Ad as TikTokAd,
    AdGroupMetrics as TikTokAdGroupMetrics,
    CustomAudience as TikTokCustomAudience,
    Pixel as TikTokPixel,
    TikTokAdsError,
    CampaignStatus as TikTokCampaignStatus,
    CampaignObjective as TikTokCampaignObjective,
    AdGroupStatus as TikTokAdGroupStatus,
    OptimizationGoal as TikTokOptimizationGoal,
    PlacementType as TikTokPlacementType,
    BillingEvent as TikTokBillingEvent,
    get_mock_campaign as get_mock_tiktok_campaign,
    get_mock_metrics as get_mock_tiktok_metrics,
)

__all__ = [
    # Google Ads
    "GoogleAdsConnector",
    "GoogleAdsCredentials",
    "GoogleCampaign",
    "GoogleAdGroup",
    "GoogleAd",
    "GoogleKeyword",
    "CampaignMetrics",
    "SearchTermMetrics",
    "GoogleAdsError",
    "GoogleCampaignStatus",
    "GoogleCampaignType",
    "GoogleAdGroupStatus",
    "GoogleAdStatus",
    "GoogleKeywordMatchType",
    "BiddingStrategyType",
    "get_mock_google_campaign",
    "get_mock_google_metrics",
    # Meta Ads
    "MetaAdsConnector",
    "MetaAdsCredentials",
    "AdAccount",
    "MetaCampaign",
    "AdSet",
    "MetaAd",
    "AdCreative",
    "AdInsights",
    "CustomAudience",
    "MetaAdsError",
    "MetaCampaignStatus",
    "CampaignObjective",
    "AdSetStatus",
    "MetaAdStatus",
    "MetaOptimizationGoal",
    "MetaBillingEvent",
    "MetaPlacement",
    # LinkedIn Ads
    "LinkedInAdsConnector",
    "LinkedInAdsCredentials",
    "CampaignGroup",
    "LinkedInCampaign",
    "Creative",
    "AdAnalytics",
    "LeadGenForm",
    "Lead",
    "AudienceSegment",
    "LinkedInAdsError",
    "LinkedInCampaignStatus",
    "LinkedInCampaignType",
    "ObjectiveType",
    "AdFormat",
    "BidStrategy",
    "get_mock_linkedin_campaign",
    "get_mock_linkedin_analytics",
    # Microsoft Ads
    "MicrosoftAdsConnector",
    "MicrosoftAdsCredentials",
    "MicrosoftCampaign",
    "MicrosoftAdGroup",
    "ResponsiveSearchAd",
    "MicrosoftKeyword",
    "CampaignPerformance",
    "AudienceList",
    "ConversionGoal",
    "NegativeKeyword",
    "MicrosoftAdsError",
    "MicrosoftCampaignStatus",
    "MicrosoftCampaignType",
    "BudgetType",
    "BiddingScheme",
    "MicrosoftAdGroupStatus",
    "MicrosoftAdStatus",
    "MicrosoftAdType",
    "MicrosoftKeywordMatchType",
    "KeywordStatus",
    "get_mock_microsoft_campaign",
    "get_mock_microsoft_performance",
    # Twitter/X Ads
    "TwitterAdsConnector",
    "TwitterAdsCredentials",
    "TwitterCampaign",
    "TwitterLineItem",
    "PromotedTweet",
    "FundingInstrument",
    "TwitterCampaignAnalytics",
    "TailoredAudience",
    "TwitterAdsError",
    "TwitterCampaignStatus",
    "TwitterCampaignObjective",
    "LineItemType",
    "PlacementType",
    "get_mock_twitter_campaign",
    "get_mock_twitter_analytics",
    # TikTok Ads
    "TikTokAdsConnector",
    "TikTokAdsCredentials",
    "TikTokCampaign",
    "TikTokAdGroup",
    "TikTokAd",
    "TikTokAdGroupMetrics",
    "TikTokCustomAudience",
    "TikTokPixel",
    "TikTokAdsError",
    "TikTokCampaignStatus",
    "TikTokCampaignObjective",
    "TikTokAdGroupStatus",
    "TikTokOptimizationGoal",
    "TikTokPlacementType",
    "TikTokBillingEvent",
    "get_mock_tiktok_campaign",
    "get_mock_tiktok_metrics",
]
