"""
Advertising Platform Connectors.

Integrations for online advertising platforms:
- Google Ads (Search, Display, Shopping, YouTube)
- Meta Ads (Facebook, Instagram)
- LinkedIn Ads (B2B advertising)
- Microsoft Ads (Bing search ads)
- Twitter/X Ads - planned
- TikTok Ads - planned
"""

from aragora.connectors.advertising.google_ads import (
    GoogleAdsConnector,
    GoogleAdsCredentials,
    Campaign as GoogleCampaign,
    AdGroup as GoogleAdGroup,
    Ad as GoogleAd,
    Keyword as GoogleKeyword,
    CampaignMetrics,
    AdGroupMetrics,
    KeywordMetrics,
    SearchTermReport,
    GoogleAdsError,
    CampaignStatus as GoogleCampaignStatus,
    CampaignType as GoogleCampaignType,
    AdGroupStatus as GoogleAdGroupStatus,
    AdStatus as GoogleAdStatus,
    AdType as GoogleAdType,
    KeywordMatchType as GoogleKeywordMatchType,
    BiddingStrategy,
    get_mock_campaign as get_mock_google_campaign,
    get_mock_metrics as get_mock_google_metrics,
)
from aragora.connectors.advertising.meta_ads import (
    MetaAdsConnector,
    MetaAdsCredentials,
    Campaign as MetaCampaign,
    AdSet,
    Ad as MetaAd,
    AdCreative,
    AdInsights,
    CustomAudience,
    LookalikeAudience,
    MetaAdsError,
    CampaignStatus as MetaCampaignStatus,
    CampaignObjective,
    AdSetStatus,
    AdSetOptimizationGoal,
    AdSetBillingEvent,
    AdStatus as MetaAdStatus,
    InsightLevel,
    DatePreset,
    get_mock_campaign as get_mock_meta_campaign,
    get_mock_insights as get_mock_meta_insights,
)
from aragora.connectors.advertising.linkedin_ads import (
    LinkedInAdsConnector,
    LinkedInAdsCredentials,
    CampaignGroup,
    Campaign as LinkedInCampaign,
    Creative,
    AdAnalytics,
    LeadGenForm,
    Lead,
    AudienceSegment,
    LinkedInAdsError,
    CampaignStatus as LinkedInCampaignStatus,
    CampaignType as LinkedInCampaignType,
    ObjectiveType,
    AdFormat,
    BidStrategy,
    get_mock_campaign as get_mock_linkedin_campaign,
    get_mock_analytics as get_mock_linkedin_analytics,
)
from aragora.connectors.advertising.microsoft_ads import (
    MicrosoftAdsConnector,
    MicrosoftAdsCredentials,
    Campaign as MicrosoftCampaign,
    AdGroup as MicrosoftAdGroup,
    ResponsiveSearchAd,
    Keyword as MicrosoftKeyword,
    CampaignPerformance,
    AudienceList,
    ConversionGoal,
    NegativeKeyword,
    MicrosoftAdsError,
    CampaignStatus as MicrosoftCampaignStatus,
    CampaignType as MicrosoftCampaignType,
    BudgetType,
    BiddingScheme,
    AdGroupStatus as MicrosoftAdGroupStatus,
    AdStatus as MicrosoftAdStatus,
    AdType as MicrosoftAdType,
    KeywordMatchType as MicrosoftKeywordMatchType,
    KeywordStatus,
    get_mock_campaign as get_mock_microsoft_campaign,
    get_mock_performance as get_mock_microsoft_performance,
)

__all__ = [
    # Google Ads
    "GoogleAdsConnector",
    "GoogleAdsCredentials",
    "GoogleCampaign",
    "GoogleAdGroup",
    "GoogleAd",
    "GoogleKeyword",
    "CampaignMetrics",
    "AdGroupMetrics",
    "KeywordMetrics",
    "SearchTermReport",
    "GoogleAdsError",
    "GoogleCampaignStatus",
    "GoogleCampaignType",
    "GoogleAdGroupStatus",
    "GoogleAdStatus",
    "GoogleAdType",
    "GoogleKeywordMatchType",
    "BiddingStrategy",
    "get_mock_google_campaign",
    "get_mock_google_metrics",
    # Meta Ads
    "MetaAdsConnector",
    "MetaAdsCredentials",
    "MetaCampaign",
    "AdSet",
    "MetaAd",
    "AdCreative",
    "AdInsights",
    "CustomAudience",
    "LookalikeAudience",
    "MetaAdsError",
    "MetaCampaignStatus",
    "CampaignObjective",
    "AdSetStatus",
    "AdSetOptimizationGoal",
    "AdSetBillingEvent",
    "MetaAdStatus",
    "InsightLevel",
    "DatePreset",
    "get_mock_meta_campaign",
    "get_mock_meta_insights",
    # LinkedIn Ads
    "LinkedInAdsConnector",
    "LinkedInAdsCredentials",
    "CampaignGroup",
    "LinkedInCampaign",
    "Creative",
    "AdAnalytics",
    "LeadGenForm",
    "Lead",
    "AudienceSegment",
    "LinkedInAdsError",
    "LinkedInCampaignStatus",
    "LinkedInCampaignType",
    "ObjectiveType",
    "AdFormat",
    "BidStrategy",
    "get_mock_linkedin_campaign",
    "get_mock_linkedin_analytics",
    # Microsoft Ads
    "MicrosoftAdsConnector",
    "MicrosoftAdsCredentials",
    "MicrosoftCampaign",
    "MicrosoftAdGroup",
    "ResponsiveSearchAd",
    "MicrosoftKeyword",
    "CampaignPerformance",
    "AudienceList",
    "ConversionGoal",
    "NegativeKeyword",
    "MicrosoftAdsError",
    "MicrosoftCampaignStatus",
    "MicrosoftCampaignType",
    "BudgetType",
    "BiddingScheme",
    "MicrosoftAdGroupStatus",
    "MicrosoftAdStatus",
    "MicrosoftAdType",
    "MicrosoftKeywordMatchType",
    "KeywordStatus",
    "get_mock_microsoft_campaign",
    "get_mock_microsoft_performance",
]
