#!/usr/bin/env python3
"""
Aragora CLI - Command line interface for Aragora.

Usage:
    aragora setup          # Interactive setup wizard
    aragora serve          # Start the server
    aragora ask QUESTION   # Run a quick debate
    aragora gauntlet FILE  # Run security gauntlet
"""

from __future__ import annotations

import argparse
import os
import secrets
import subprocess
import sys
from pathlib import Path


def cmd_setup(args: argparse.Namespace) -> int:
    """Interactive setup wizard for Aragora."""
    print("=" * 60)
    print("  Welcome to Aragora Setup")
    print("  Control plane for multi-agent robust decisionmaking")
    print("=" * 60)
    print()

    env_path = Path(".env")
    if env_path.exists() and not args.force:
        print(f"Configuration file already exists: {env_path}")
        response = input("Overwrite? [y/N]: ").strip().lower()
        if response != "y":
            print("Aborted.")
            return 1

    config = {}

    # API Keys
    print("\n[1/4] AI Provider API Keys")
    print("At least one API key is required for debate functionality.\n")

    anthropic_key = input("Anthropic API Key (recommended): ").strip()
    if anthropic_key:
        config["ANTHROPIC_API_KEY"] = anthropic_key

    openai_key = input("OpenAI API Key (optional): ").strip()
    if openai_key:
        config["OPENAI_API_KEY"] = openai_key

    openrouter_key = input("OpenRouter API Key (optional, for fallback): ").strip()
    if openrouter_key:
        config["OPENROUTER_API_KEY"] = openrouter_key

    if not anthropic_key and not openai_key:
        print("\nWarning: No API keys provided. You'll need to add at least one later.")

    # Database
    print("\n[2/4] Database Configuration")
    use_postgres = input("Use PostgreSQL? (recommended for production) [Y/n]: ").strip().lower()

    if use_postgres != "n":
        pg_password = input("PostgreSQL password [aragora]: ").strip() or "aragora"
        config["POSTGRES_PASSWORD"] = pg_password
        config["DATABASE_URL"] = f"postgresql://aragora:{pg_password}@db:5432/aragora"
        print("PostgreSQL will be configured with docker-compose.")
    else:
        print("Using SQLite (not recommended for production).")

    # Security
    print("\n[3/4] Security Configuration")
    generate_secret = input("Generate random secret key? [Y/n]: ").strip().lower()
    if generate_secret != "n":
        config["ARAGORA_SECRET_KEY"] = secrets.token_urlsafe(32)
        print("Secret key generated.")
    else:
        secret_key = input("Enter secret key: ").strip()
        if secret_key:
            config["ARAGORA_SECRET_KEY"] = secret_key

    # Server settings
    print("\n[4/4] Server Configuration")
    api_port = input("API port [8080]: ").strip() or "8080"
    config["ARAGORA_API_PORT"] = api_port

    ws_port = input("WebSocket port [8765]: ").strip() or "8765"
    config["ARAGORA_WS_PORT"] = ws_port

    # Generate .env file
    print("\n" + "=" * 60)
    print("Configuration Summary:")
    print("=" * 60)

    env_content = "# Aragora Configuration\n# Generated by 'aragora setup'\n\n"
    for key, value in config.items():
        # Mask sensitive values in summary
        if "KEY" in key or "SECRET" in key or "PASSWORD" in key:
            display_value = value[:4] + "..." if len(value) > 4 else "***"
        else:
            display_value = value
        print(f"  {key}={display_value}")
        env_content += f"{key}={value}\n"

    print()
    confirm = input("Save configuration? [Y/n]: ").strip().lower()
    if confirm == "n":
        print("Aborted.")
        return 1

    env_path.write_text(env_content)
    print(f"\nConfiguration saved to {env_path}")

    # Next steps
    print("\n" + "=" * 60)
    print("Next Steps:")
    print("=" * 60)
    print()
    print("1. Start with Docker Compose:")
    print("   docker compose up -d")
    print()
    print("2. Or run locally:")
    print("   python -m aragora.server.unified_server")
    print()
    print("3. Access the API:")
    print(f"   http://localhost:{api_port}/api/health")
    print()
    print("4. Run a test debate:")
    print("   aragora ask 'Should we use microservices?' --demo")
    print()

    return 0


def cmd_serve(args: argparse.Namespace) -> int:
    """Start the Aragora server."""
    cmd = [
        sys.executable,
        "-m",
        "aragora.server.unified_server",
        "--host",
        args.host,
        "--port",
        str(args.api_port),
        "--ws-port",
        str(args.ws_port),
    ]

    if args.reload:
        # Use watchfiles for auto-reload in development
        cmd = ["watchfiles", "--filter", "python", " ".join(cmd)]

    print(f"Starting Aragora server on {args.host}:{args.api_port}...")
    return subprocess.run(cmd).returncode


def cmd_ask(args: argparse.Namespace) -> int:
    """Run a quick debate."""
    from aragora.debate.quick import quick_debate

    result = quick_debate(
        task=args.question,
        rounds=args.rounds,
        demo=args.demo,
    )

    print(f"\nConsensus: {result.get('consensus', 'No consensus')}")
    if result.get("decision"):
        print(f"Decision: {result['decision']}")

    return 0


def main() -> int:
    """Main entry point for Aragora CLI."""
    parser = argparse.ArgumentParser(
        prog="aragora",
        description="Aragora - Control plane for multi-agent robust decisionmaking",
    )
    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # Setup command
    setup_parser = subparsers.add_parser("setup", help="Interactive setup wizard")
    setup_parser.add_argument(
        "--force", "-f", action="store_true", help="Overwrite existing configuration"
    )

    # Serve command
    serve_parser = subparsers.add_parser("serve", help="Start the Aragora server")
    serve_parser.add_argument(
        "--host",
        default=os.environ.get("ARAGORA_HOST", "127.0.0.1"),
        help="Host to bind to (default: 127.0.0.1)",
    )
    serve_parser.add_argument(
        "--api-port",
        type=int,
        default=int(os.environ.get("ARAGORA_API_PORT", "8080")),
        help="API port (default: 8080)",
    )
    serve_parser.add_argument(
        "--ws-port",
        type=int,
        default=int(os.environ.get("ARAGORA_WS_PORT", "8765")),
        help="WebSocket port (default: 8765)",
    )
    serve_parser.add_argument(
        "--reload",
        action="store_true",
        help="Enable auto-reload for development",
    )

    # Ask command
    ask_parser = subparsers.add_parser("ask", help="Run a quick debate")
    ask_parser.add_argument("question", help="The question to debate")
    ask_parser.add_argument("--rounds", "-r", type=int, default=3, help="Number of debate rounds")
    ask_parser.add_argument("--demo", action="store_true", help="Use demo mode (mock agents)")

    args = parser.parse_args()

    if args.command is None:
        parser.print_help()
        return 1

    commands = {
        "setup": cmd_setup,
        "serve": cmd_serve,
        "ask": cmd_ask,
    }

    handler = commands.get(args.command)
    if handler:
        return handler(args)

    parser.print_help()
    return 1


if __name__ == "__main__":
    sys.exit(main())
