"""
Aragora Server Middleware Package.

Provides composable middleware decorators for common cross-cutting concerns:
- Authentication (require_auth, optional_auth)
- Rate limiting (rate_limit, RateLimiter)
- Caching (cache, ttl_cache)

Usage:
    from aragora.server.middleware import require_auth, rate_limit, cache

    @require_auth
    @rate_limit(requests_per_minute=30)
    @cache(ttl_seconds=300)
    def get_leaderboard(self, handler):
        ...

Middleware can be stacked in any order, but recommended order is:
1. Authentication (first - reject unauthorized requests early)
2. Rate limiting (second - prevent abuse before expensive operations)
3. Caching (last - serve cached responses when available)
"""

from .auth import (
    require_auth,
    require_auth_or_localhost,
    optional_auth,
    extract_token,
    validate_token,
    extract_client_ip,
    AuthContext,
)
from .rate_limit import (
    rate_limit,
    RateLimiter,
    get_rate_limiter,
    cleanup_rate_limiters,
    TierRateLimiter,
    get_tier_rate_limiter,
    check_tier_rate_limit,
    TIER_RATE_LIMITS,
)
from .cache import (
    cache,
    ttl_cache,
    clear_cache,
    invalidate_cache,
    get_cache_stats,
    CacheConfig,
    CACHE_INVALIDATION_MAP,
)
from .request_logging import (
    REQUEST_ID_HEADER,
    RequestContext,
    generate_request_id,
    hash_token,
    sanitize_headers,
    sanitize_params,
    log_request,
    log_response,
    request_logging,
    get_current_request_id,
    set_current_request_id,
)
from .auth_v2 import (
    User,
    Workspace,
    APIKey,
    require_user,
    require_admin,
    require_plan,
    get_current_user,
    authenticate_request,
    SupabaseAuthValidator,
    get_jwt_validator,
)
from .tenancy import (
    PLAN_LIMITS,
    get_plan_limits,
    WorkspaceManager,
    get_workspace_manager,
    require_workspace,
    check_limit,
    tenant_scoped,
    scope_query,
    ensure_workspace_access,
)
from .exception_handler import (
    EXCEPTION_STATUS_MAP,
    map_exception_to_status,
    generate_trace_id,
    ErrorResponse,
    build_error_response,
    ExceptionHandler,
    async_exception_handler,
    handle_exceptions,
    async_handle_exceptions,
    is_client_error,
    is_server_error,
    is_retryable,
    is_authentication_error,
)
from .structured_logging import (
    configure_structured_logging,
    get_logger,
    log_context,
    set_log_context,
    clear_log_context,
    get_log_context,
    redact_sensitive,
    RequestLoggingMiddleware,
    JsonFormatter,
    TextFormatter,
    LogContext,
    setup_logging,
)
from .tracing import (
    TRACE_ID_HEADER,
    SPAN_ID_HEADER,
    PARENT_SPAN_HEADER,
    generate_trace_id as generate_new_trace_id,
    generate_span_id,
    get_trace_id,
    get_span_id,
    get_parent_span_id,
    set_trace_id,
    set_span_id,
    Span,
    trace_context,
    traced,
    TracingMiddleware,
    trace_websocket_event,
    extract_websocket_trace,
    add_trace_to_error,
)
from .tier_enforcement import (
    QuotaExceededError,
    check_org_quota,
    increment_org_usage,
    require_quota,
    get_quota_status,
)
from .timeout import (
    RequestTimeoutConfig,
    RequestTimeoutError,
    get_timeout_config,
    configure_timeout,
    with_timeout,
    async_with_timeout,
    timeout_context,
    get_timeout_stats,
    shutdown_executor,
)
from .token_revocation import (
    RevocationEntry,
    InMemoryRevocationStore,
    RedisRevocationStore,
    get_revocation_store,
    hash_token as hash_token_for_revocation,
    revoke_token,
    is_token_revoked,
    unrevoke_token,
    get_revocation_stats,
)
from .audit_logger import (
    AuditEvent,
    AuditLogger,
    AuditSeverity,
    AuditCategory,
    AuditBackend,
    FileAuditBackend,
    MemoryAuditBackend,
    get_audit_logger,
    set_audit_logger,
    set_audit_context,
    clear_audit_context,
    audit_event,
    audit_action,
    audit_auth_login,
    audit_auth_logout,
    audit_token_revoked,
    audit_access_denied,
    audit_data_modified,
    audit_config_changed,
    audit_security_event,
)

__all__ = [
    # Auth
    "require_auth",
    "require_auth_or_localhost",
    "optional_auth",
    "extract_token",
    "validate_token",
    "extract_client_ip",
    "AuthContext",
    # Rate limiting
    "rate_limit",
    "RateLimiter",
    "get_rate_limiter",
    "cleanup_rate_limiters",
    "TierRateLimiter",
    "get_tier_rate_limiter",
    "check_tier_rate_limit",
    "TIER_RATE_LIMITS",
    # Caching
    "cache",
    "ttl_cache",
    "clear_cache",
    "invalidate_cache",
    "get_cache_stats",
    "CacheConfig",
    "CACHE_INVALIDATION_MAP",
    # Request logging
    "REQUEST_ID_HEADER",
    "RequestContext",
    "generate_request_id",
    "hash_token",
    "sanitize_headers",
    "sanitize_params",
    "log_request",
    "log_response",
    "request_logging",
    "get_current_request_id",
    "set_current_request_id",
    # User Auth (Supabase)
    "User",
    "Workspace",
    "APIKey",
    "require_user",
    "require_admin",
    "require_plan",
    "get_current_user",
    "authenticate_request",
    "SupabaseAuthValidator",
    "get_jwt_validator",
    # Multi-tenancy
    "PLAN_LIMITS",
    "get_plan_limits",
    "WorkspaceManager",
    "get_workspace_manager",
    "require_workspace",
    "check_limit",
    "tenant_scoped",
    "scope_query",
    "ensure_workspace_access",
    # Exception handling
    "EXCEPTION_STATUS_MAP",
    "map_exception_to_status",
    "generate_trace_id",
    "ErrorResponse",
    "build_error_response",
    "ExceptionHandler",
    "async_exception_handler",
    "handle_exceptions",
    "async_handle_exceptions",
    "is_client_error",
    "is_server_error",
    "is_retryable",
    "is_authentication_error",
    # Structured logging
    "configure_structured_logging",
    "get_logger",
    "log_context",
    "set_log_context",
    "clear_log_context",
    "get_log_context",
    "redact_sensitive",
    "RequestLoggingMiddleware",
    "JsonFormatter",
    "TextFormatter",
    "LogContext",
    "setup_logging",
    # Distributed tracing
    "TRACE_ID_HEADER",
    "SPAN_ID_HEADER",
    "PARENT_SPAN_HEADER",
    "generate_new_trace_id",
    "generate_span_id",
    "get_trace_id",
    "get_span_id",
    "get_parent_span_id",
    "set_trace_id",
    "set_span_id",
    "Span",
    "trace_context",
    "traced",
    "TracingMiddleware",
    "trace_websocket_event",
    "extract_websocket_trace",
    "add_trace_to_error",
    # Tier enforcement
    "QuotaExceededError",
    "check_org_quota",
    "increment_org_usage",
    "require_quota",
    "get_quota_status",
    # Request timeout
    "RequestTimeoutConfig",
    "RequestTimeoutError",
    "get_timeout_config",
    "configure_timeout",
    "with_timeout",
    "async_with_timeout",
    "timeout_context",
    "get_timeout_stats",
    "shutdown_executor",
    # Token revocation
    "RevocationEntry",
    "InMemoryRevocationStore",
    "RedisRevocationStore",
    "get_revocation_store",
    "hash_token_for_revocation",
    "revoke_token",
    "is_token_revoked",
    "unrevoke_token",
    "get_revocation_stats",
    # Audit logging
    "AuditEvent",
    "AuditLogger",
    "AuditSeverity",
    "AuditCategory",
    "AuditBackend",
    "FileAuditBackend",
    "MemoryAuditBackend",
    "get_audit_logger",
    "set_audit_logger",
    "set_audit_context",
    "clear_audit_context",
    "audit_event",
    "audit_action",
    "audit_auth_login",
    "audit_auth_logout",
    "audit_token_revoked",
    "audit_access_denied",
    "audit_data_modified",
    "audit_config_changed",
    "audit_security_event",
]
