"""
Aragora Setup Wizard - Interactive configuration tool.

Guides users through initial setup including:
- API key configuration
- Integration setup (optional)
- .env file generation
- Connectivity testing
"""

from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Any, Optional


def _prompt(message: str, default: Optional[str] = None, secret: bool = False) -> str:
    """Prompt user for input with optional default and secret mode."""
    suffix = f" [{default}]" if default else ""
    try:
        if secret:
            import getpass

            value = getpass.getpass(f"{message}{suffix}: ")
        else:
            value = input(f"{message}{suffix}: ")
        return value.strip() or (default or "")
    except (EOFError, KeyboardInterrupt):
        print("\nSetup cancelled.")
        sys.exit(0)


def _confirm(message: str, default: bool = True) -> bool:
    """Ask for yes/no confirmation."""
    suffix = " [Y/n]" if default else " [y/N]"
    try:
        response = input(f"{message}{suffix}: ").strip().lower()
        if not response:
            return default
        return response in ("y", "yes")
    except (EOFError, KeyboardInterrupt):
        print("\nSetup cancelled.")
        sys.exit(0)


def _print_header(text: str) -> None:
    """Print a section header."""
    print(f"\n{'='*60}")
    print(f"  {text}")
    print(f"{'='*60}\n")


def _print_step(step: int, total: int, text: str) -> None:
    """Print a step indicator."""
    print(f"\n[{step}/{total}] {text}")
    print("-" * 40)


def _test_api_key(provider: str, key: str) -> tuple[bool, str]:
    """Test an API key by making a minimal request."""
    if not key:
        return False, "No key provided"

    try:
        if provider == "anthropic":
            import httpx

            response = httpx.post(
                "https://api.anthropic.com/v1/messages",
                headers={
                    "x-api-key": key,
                    "anthropic-version": "2023-06-01",
                    "content-type": "application/json",
                },
                json={
                    "model": "claude-3-haiku-20240307",
                    "max_tokens": 1,
                    "messages": [{"role": "user", "content": "Hi"}],
                },
                timeout=10.0,
            )
            if response.status_code == 200:
                return True, "Valid"
            elif response.status_code == 401:
                return False, "Invalid key"
            else:
                return False, f"Error: {response.status_code}"

        elif provider == "openai":
            import httpx

            response = httpx.get(
                "https://api.openai.com/v1/models",
                headers={"Authorization": f"Bearer {key}"},
                timeout=10.0,
            )
            if response.status_code == 200:
                return True, "Valid"
            elif response.status_code == 401:
                return False, "Invalid key"
            else:
                return False, f"Error: {response.status_code}"

        elif provider == "openrouter":
            import httpx

            response = httpx.get(
                "https://openrouter.ai/api/v1/models",
                headers={"Authorization": f"Bearer {key}"},
                timeout=10.0,
            )
            if response.status_code == 200:
                return True, "Valid"
            elif response.status_code == 401:
                return False, "Invalid key"
            else:
                return False, f"Error: {response.status_code}"

        else:
            return True, "Stored (not validated)"

    except ImportError:
        return True, "Stored (httpx not installed for validation)"
    except Exception as e:
        return False, f"Connection error: {str(e)[:50]}"


def _generate_env_content(config: dict[str, Any]) -> str:
    """Generate .env file content from config."""
    lines = [
        "# Aragora Configuration",
        "# Generated by aragora setup",
        "",
        "# =============================================================================",
        "# API Keys (at least one required)",
        "# =============================================================================",
        "",
    ]

    # Required keys
    if config.get("anthropic_key"):
        lines.append(f"ANTHROPIC_API_KEY={config['anthropic_key']}")
    else:
        lines.append("# ANTHROPIC_API_KEY=your-key-here")

    if config.get("openai_key"):
        lines.append(f"OPENAI_API_KEY={config['openai_key']}")
    else:
        lines.append("# OPENAI_API_KEY=your-key-here")

    lines.append("")

    # Optional provider keys
    lines.append("# Optional provider keys")
    if config.get("openrouter_key"):
        lines.append(f"OPENROUTER_API_KEY={config['openrouter_key']}")
    else:
        lines.append("# OPENROUTER_API_KEY=your-key-here  # Fallback on rate limits")

    if config.get("mistral_key"):
        lines.append(f"MISTRAL_API_KEY={config['mistral_key']}")
    if config.get("gemini_key"):
        lines.append(f"GEMINI_API_KEY={config['gemini_key']}")
    if config.get("xai_key"):
        lines.append(f"XAI_API_KEY={config['xai_key']}")

    lines.append("")

    # Server configuration
    lines.extend(
        [
            "# =============================================================================",
            "# Server Configuration",
            "# =============================================================================",
            "",
            f"ARAGORA_HTTP_PORT={config.get('http_port', 8080)}",
            f"ARAGORA_WS_PORT={config.get('ws_port', 8765)}",
            "",
        ]
    )

    # Database configuration
    if config.get("database_mode") == "postgres":
        lines.extend(
            [
                "# Database (PostgreSQL)",
                f"DATABASE_URL={config.get('database_url', 'postgresql://localhost:5432/aragora')}",
                "",
            ]
        )
    else:
        lines.extend(
            [
                "# Database (SQLite - default)",
                "# DATABASE_URL=sqlite:///aragora.db",
                "",
            ]
        )

    # Redis configuration
    if config.get("redis_url"):
        lines.extend(
            [
                "# Redis (optional - for caching/sessions)",
                f"REDIS_URL={config['redis_url']}",
                "",
            ]
        )

    # Security
    if config.get("encryption_key"):
        lines.extend(
            [
                "# Security",
                f"ARAGORA_ENCRYPTION_KEY={config['encryption_key']}",
                "",
            ]
        )

    # Integrations
    if any(config.get(k) for k in ["slack_token", "github_token", "telegram_token"]):
        lines.extend(
            [
                "# =============================================================================",
                "# Integrations",
                "# =============================================================================",
                "",
            ]
        )
        if config.get("slack_token"):
            lines.append(f"SLACK_BOT_TOKEN={config['slack_token']}")
        if config.get("github_token"):
            lines.append(f"GITHUB_TOKEN={config['github_token']}")
        if config.get("telegram_token"):
            lines.append(f"TELEGRAM_BOT_TOKEN={config['telegram_token']}")
        lines.append("")

    return "\n".join(lines)


def run_setup(
    output_path: Optional[str] = None,
    minimal: bool = False,
    skip_test: bool = False,
    non_interactive: bool = False,
) -> dict[str, Any]:
    """Run the interactive setup wizard.

    Args:
        output_path: Path to write .env file (default: current directory)
        minimal: Only configure essential settings
        skip_test: Skip API key validation
        non_interactive: Use defaults without prompting

    Returns:
        Configuration dictionary
    """
    config: dict[str, Any] = {}

    _print_header("Aragora Setup Wizard")
    print("This wizard will help you configure Aragora.")
    print("Press Ctrl+C at any time to cancel.\n")

    total_steps = 3 if minimal else 5

    # Step 1: API Keys
    _print_step(1, total_steps, "API Keys Configuration")
    print("Aragora requires at least one AI provider API key.\n")

    # Anthropic
    existing_anthropic = os.environ.get("ANTHROPIC_API_KEY", "")
    if existing_anthropic:
        print(f"  Found existing ANTHROPIC_API_KEY: {existing_anthropic[:8]}...")
        if not non_interactive and _confirm("  Use existing key?"):
            config["anthropic_key"] = existing_anthropic
        else:
            config["anthropic_key"] = (
                _prompt("  Anthropic API Key", secret=True) if not non_interactive else ""
            )
    else:
        config["anthropic_key"] = (
            _prompt("  Anthropic API Key (recommended)", secret=True) if not non_interactive else ""
        )

    # OpenAI
    existing_openai = os.environ.get("OPENAI_API_KEY", "")
    if existing_openai:
        print(f"  Found existing OPENAI_API_KEY: {existing_openai[:8]}...")
        if not non_interactive and _confirm("  Use existing key?"):
            config["openai_key"] = existing_openai
        else:
            config["openai_key"] = (
                _prompt("  OpenAI API Key", secret=True) if not non_interactive else ""
            )
    else:
        config["openai_key"] = (
            _prompt("  OpenAI API Key", secret=True) if not non_interactive else ""
        )

    # Check we have at least one
    if not config.get("anthropic_key") and not config.get("openai_key"):
        print("\n  Warning: No API keys configured. Aragora requires at least one.")
        if not non_interactive and _confirm("  Continue anyway?", default=False):
            pass
        else:
            print("  Please provide at least one API key.")
            return config

    # Optional: OpenRouter (fallback)
    if not minimal and not non_interactive:
        if _confirm("\n  Configure OpenRouter for fallback? (recommended)"):
            config["openrouter_key"] = _prompt("  OpenRouter API Key", secret=True)

    # Step 2: Test API Keys
    if not skip_test and (config.get("anthropic_key") or config.get("openai_key")):
        _print_step(2, total_steps, "Testing API Keys")

        if config.get("anthropic_key"):
            print("  Testing Anthropic key...", end=" ", flush=True)
            success, msg = _test_api_key("anthropic", config["anthropic_key"])
            print(f"{'OK' if success else 'FAILED'} ({msg})")

        if config.get("openai_key"):
            print("  Testing OpenAI key...", end=" ", flush=True)
            success, msg = _test_api_key("openai", config["openai_key"])
            print(f"{'OK' if success else 'FAILED'} ({msg})")

        if config.get("openrouter_key"):
            print("  Testing OpenRouter key...", end=" ", flush=True)
            success, msg = _test_api_key("openrouter", config["openrouter_key"])
            print(f"{'OK' if success else 'FAILED'} ({msg})")
    else:
        _print_step(2, total_steps, "Skipping API Key Tests")

    # Step 3: Server Configuration
    _print_step(3, total_steps, "Server Configuration")

    if non_interactive:
        config["http_port"] = 8080
        config["ws_port"] = 8765
        config["database_mode"] = "sqlite"
    else:
        config["http_port"] = int(_prompt("  HTTP Port", "8080") or 8080)
        config["ws_port"] = int(_prompt("  WebSocket Port", "8765") or 8765)

        print("\n  Database options:")
        print("    1. SQLite (simple, no setup required)")
        print("    2. PostgreSQL (production-ready, requires setup)")
        db_choice = _prompt("  Select database [1/2]", "1")
        if db_choice == "2":
            config["database_mode"] = "postgres"
            config["database_url"] = _prompt(
                "  PostgreSQL URL", "postgresql://localhost:5432/aragora"
            )
        else:
            config["database_mode"] = "sqlite"

    if not minimal and not non_interactive:
        # Step 4: Integrations (optional)
        _print_step(4, total_steps, "Integrations (Optional)")
        print("  Configure integrations to connect Aragora with external services.\n")

        if _confirm("  Configure Slack integration?", default=False):
            config["slack_token"] = _prompt("    Slack Bot Token", secret=True)

        if _confirm("  Configure GitHub integration?", default=False):
            config["github_token"] = _prompt("    GitHub Token", secret=True)

        if _confirm("  Configure Telegram integration?", default=False):
            config["telegram_token"] = _prompt("    Telegram Bot Token", secret=True)

        # Step 5: Security
        _print_step(5, total_steps, "Security Configuration")

        if _confirm("  Generate encryption key for secrets?", default=True):
            import secrets as secrets_mod

            config["encryption_key"] = secrets_mod.token_hex(32)
            print(f"    Generated key: {config['encryption_key'][:16]}...")

    # Generate .env file
    _print_header("Generating Configuration")

    env_content = _generate_env_content(config)
    target_path = Path(output_path) if output_path else Path.cwd()
    env_file = target_path / ".env"

    # Check for existing file
    if env_file.exists():
        print(f"  Existing .env file found at: {env_file}")
        if non_interactive:
            backup = env_file.with_suffix(".env.backup")
            env_file.rename(backup)
            print(f"  Backed up to: {backup}")
        elif _confirm("  Overwrite existing .env file?", default=False):
            backup = env_file.with_suffix(".env.backup")
            env_file.rename(backup)
            print(f"  Backed up to: {backup}")
        else:
            print("  Skipping .env file generation.")
            env_file = None

    if env_file:
        env_file.write_text(env_content)
        print(f"  Created: {env_file}")

    # Summary
    _print_header("Setup Complete!")

    print("Configuration summary:")
    print(f"  - Anthropic API: {'Configured' if config.get('anthropic_key') else 'Not set'}")
    print(f"  - OpenAI API: {'Configured' if config.get('openai_key') else 'Not set'}")
    print(f"  - OpenRouter: {'Configured' if config.get('openrouter_key') else 'Not set'}")
    print(f"  - Database: {config.get('database_mode', 'sqlite').upper()}")
    print(f"  - HTTP Port: {config.get('http_port', 8080)}")

    integrations = []
    if config.get("slack_token"):
        integrations.append("Slack")
    if config.get("github_token"):
        integrations.append("GitHub")
    if config.get("telegram_token"):
        integrations.append("Telegram")
    if integrations:
        print(f"  - Integrations: {', '.join(integrations)}")

    print("\nNext steps:")
    print("  1. Review .env file and adjust settings if needed")
    print("  2. Start the server: aragora serve")
    print("  3. Run a debate: aragora ask 'Your question here'")
    print("\nFor more help, run: aragora --help")

    return config


def cmd_setup(args) -> None:
    """Handle 'setup' command."""
    run_setup(
        output_path=getattr(args, "output", None),
        minimal=getattr(args, "minimal", False),
        skip_test=getattr(args, "skip_test", False),
        non_interactive=getattr(args, "yes", False),
    )
