// Auto-generated TypeScript types from OpenAPI specification
// Generated by scripts/generate_typescript_sdk.py
// OpenAPI version: 1.0.0
// Do not edit manually - regenerate from OpenAPI spec

/* eslint-disable @typescript-eslint/no-explicit-any */

export interface Error {
  /** Human-readable error message */
  error: string;
  /** Machine-readable error code for programmatic handling */
  code?: "INVALID_JSON" | "MISSING_FIELD" | "INVALID_VALUE" | "AUTH_REQUIRED" | "INVALID_TOKEN" | "FORBIDDEN" | "NOT_OWNER" | "NOT_FOUND" | "QUOTA_EXCEEDED" | "RATE_LIMITED" | "INTERNAL_ERROR" | "SERVICE_UNAVAILABLE" | "AGENT_TIMEOUT" | "CONSENSUS_FAILED";
  /** Unique request ID for debugging and support */
  trace_id?: string;
  /** Name of the field that caused the error (for validation errors) */
  field?: string;
  /** Type of resource involved in the error */
  resource_type?: string;
  /** ID of the resource involved in the error */
  resource_id?: string;
  /** The limit that was exceeded (for quota/rate errors) */
  limit?: number;
  /** Seconds to wait before retrying (for rate limit errors) */
  retry_after?: number;
  /** When the quota/rate limit resets */
  resets_at?: string;
  /** URL to upgrade plan (for quota errors) */
  upgrade_url?: string;
  /** URL for support/issue reporting */
  support_url?: string;
}

export interface PaginatedResponse {
  /** Total items available */
  total?: number;
  /** Current offset */
  offset?: number;
  /** Page size */
  limit?: number;
  /** More items available */
  has_more?: boolean;
}

export interface StandardSuccessResponse {
  success: boolean;
  data?: Record<string, any>;
  message?: string;
}

export interface Agent {
  /** Agent name */
  name?: string;
  /** ELO rating */
  elo?: number;
  /** Total matches played */
  matches?: number;
  /** Total wins */
  wins?: number;
  /** Total losses */
  losses?: number;
  /** Calibration accuracy (0-1) */
  calibration_score?: number;
}

export type DebateStatus = "created" | "starting" | "pending" | "running" | "in_progress" | "completed" | "failed" | "cancelled" | "paused" | "active" | "concluded" | "archived";

export interface ConsensusResult {
  reached?: boolean;
  agreement?: number;
  confidence?: number;
  final_answer?: string;
  conclusion?: string;
  supporting_agents?: string[];
  dissenting_agents?: string[];
}

export interface DebateCreateRequest {
  /** The topic or question for the debate */
  task: string;
  /** Alias for task (deprecated, use task instead) */
  question?: string;
  /** List of agent names to participate. If empty, auto_select is used. */
  agents?: string[];
  /** Maximum number of debate rounds */
  rounds?: number;
  /** Consensus strategy to use */
  consensus?: "majority" | "unanimous" | "weighted" | "semantic";
  /** Additional context or background information */
  context?: string;
  /** Automatically select optimal agents based on topic */
  auto_select?: boolean;
  /** Configuration for auto-selection algorithm */
  auto_select_config?: {
    min_agents?: number;
    max_agents?: number;
    diversity_weight?: number;
    expertise_weight?: number;
  };
  /** Include trending context from news/social media */
  use_trending?: boolean;
  /** Category filter for trending content */
  trending_category?: "tech" | "science" | "politics" | "business" | "health";
}

export interface DebateCreateResponse {
  /** Whether the debate was created successfully */
  success: boolean;
  /** Unique identifier for the created debate */
  debate_id?: string;
  /** Current status of the debate */
  status?: DebateStatus;
  /** The debate topic (echoed back) */
  task?: string;
  /** Agents participating in the debate */
  agents?: string[];
  /** WebSocket URL to stream debate progress */
  websocket_url?: string;
  /** Estimated debate duration in seconds */
  estimated_duration?: number;
  /** Error message if success is false */
  error?: string;
}

export interface Debate {
  debate_id?: string;
  id?: string;
  slug?: string;
  task?: string;
  /** Alias for task */
  topic?: string;
  context?: string;
  status?: DebateStatus;
  outcome?: string;
  final_answer?: string;
  consensus?: ConsensusResult;
  consensus_proof?: Record<string, any>;
  consensus_reached?: boolean;
  confidence?: number;
  rounds_used?: number;
  duration_seconds?: number;
  agents?: string[];
  rounds?: Round[];
  created_at?: string;
  completed_at?: string;
  metadata?: Record<string, any>;
}

export interface Message {
  role?: "system" | "user" | "assistant";
  content?: string;
  agent?: string;
  agent_id?: string;
  round?: number;
  timestamp?: string;
}

export interface HealthCheck {
  status?: "healthy" | "degraded" | "unhealthy";
  version?: string;
  timestamp?: string;
  checks?: Record<string, any>;
  response_time_ms?: number;
}

export interface Consensus {
  reached?: boolean;
  topic?: string;
  verdict?: string;
  confidence?: number;
  participating_agents?: string[];
}

export interface Calibration {
  agent?: string;
  /** Calibration score (0-1) */
  score?: number;
  bucket_stats?: Record<string, any>[];
  overconfidence_index?: number;
}

export interface Relationship {
  agent_a?: string;
  agent_b?: string;
  alliance_score?: number;
  rivalry_score?: number;
  total_interactions?: number;
}

export interface OAuthProvider {
  /** Provider identifier (e.g., 'google', 'github') */
  id: string;
  /** Display name for the provider */
  name: string;
}

export interface OAuthProviders {
  /** List of available OAuth providers */
  providers: OAuthProvider[];
}

export interface Round {
  /** Round number (1-indexed) */
  round_number?: number;
  messages?: Message[];
  /** Agent votes for this round */
  votes?: Record<string, any>;
  /** Round summary */
  summary?: string;
}

export interface Workspace {
  /** Workspace ID */
  id: string;
  /** Parent organization ID */
  organization_id: string;
  /** Workspace name */
  name: string;
  created_at?: string;
  created_by?: string;
  /** Whether workspace data is encrypted */
  encrypted?: boolean;
  /** Data retention period in days */
  retention_days?: number;
  /** Data sensitivity level */
  sensitivity_level?: string;
  document_count?: number;
  storage_bytes?: number;
}

export interface WorkspaceList {
  workspaces: Workspace[];
  total: number;
}

export interface RetentionPolicy {
  id?: string;
  name?: string;
  retention_days?: number;
  data_types?: string[];
  enabled?: boolean;
  created_at?: string;
}

export interface RetentionPolicyList {
  policies?: RetentionPolicy[];
  total?: number;
}

export interface StepDefinition {
  id?: string;
  name?: string;
  type?: string;
  config?: Record<string, any>;
  depends_on?: string[];
}

export interface TransitionRule {
  from_step?: string;
  to_step?: string;
  condition?: string;
}

export interface Workflow {
  id?: string;
  name?: string;
  description?: string;
  version?: string;
  status?: string;
  steps?: StepDefinition[];
  transitions?: TransitionRule[];
  created_at?: string;
  updated_at?: string;
}

export interface WorkflowList {
  workflows?: Workflow[];
  total?: number;
}

export interface WorkflowUpdate {
  name?: string;
  description?: string;
  steps?: StepDefinition[];
  transitions?: TransitionRule[];
}

export interface WorkflowTemplate {
  id?: string;
  name?: string;
  description?: string;
  category?: string;
  steps?: StepDefinition[];
  parameters?: Record<string, any>;
}

export interface WorkflowTemplateList {
  templates?: WorkflowTemplate[];
  total?: number;
}

export interface ExecutionList {
  executions?: Record<string, any>[];
  total?: number;
}

export interface DecisionReceipt {
  /** Receipt ID */
  id: string;
  /** Associated debate ID */
  debate_id: string;
  /** Final verdict */
  verdict: string;
  /** Confidence score (0-1) */
  confidence?: number;
  consensus_reached?: boolean;
  participating_agents?: string[];
  dissenting_agents?: string[];
  evidence?: Record<string, any>[];
  reasoning?: string;
  /** Receipt integrity hash */
  hash?: string;
  created_at?: string;
  metadata?: Record<string, any>;
}

export interface ReceiptList {
  receipts: DecisionReceipt[];
  total: number;
  offset?: number;
  limit?: number;
  has_more?: boolean;
}

export interface RiskHeatmap {
  /** Heatmap ID */
  id: string;
  /** Associated gauntlet ID */
  gauntlet_id?: string;
  /** Risk categories */
  categories: string[];
  /** Risk scores per category */
  scores: number[];
  /** 2D risk matrix */
  matrix?: number[][];
  /** Overall risk score */
  overall_risk?: number;
  created_at?: string;
  metadata?: Record<string, any>;
}

export interface HeatmapList {
  heatmaps: RiskHeatmap[];
  total: number;
  offset?: number;
  limit?: number;
}

export interface PatternTemplate {
  /** Pattern template ID */
  id: string;
  /** Pattern name */
  name: string;
  /** Pattern description */
  description?: string;
  pattern_type: "hive_mind" | "map_reduce" | "review_cycle";
  /** Pattern parameters schema */
  parameters?: Record<string, any>;
  /** Example configuration */
  example_config?: Record<string, any>;
  created_at?: string;
}

export interface PatternTemplateList {
  templates: PatternTemplate[];
  total: number;
}

export interface CheckpointMetadata {
  /** Checkpoint ID */
  id: string;
  /** Associated debate ID */
  debate_id?: string;
  /** Associated workflow ID */
  workflow_id?: string;
  /** Checkpoint name */
  name?: string;
  description?: string;
  /** Checkpoint state data */
  state?: Record<string, any>;
  round_number?: number;
  created_at: string;
  created_by?: string;
  size_bytes?: number;
}

export interface CheckpointList {
  checkpoints: CheckpointMetadata[];
  total: number;
  offset?: number;
  limit?: number;
}

export interface RestoreResult {
  success: boolean;
  checkpoint_id: string;
  debate_id?: string;
  workflow_id?: string;
  restored_at?: string;
  state_restored?: boolean;
  message?: string;
}

export interface DecisionExplanation {
  /** Debate ID */
  debate_id: string;
  /** Natural language narrative */
  narrative: string;
  /** Overall confidence (0-1) */
  confidence?: number;
  /** Contributing factors */
  factors?: {
    name?: string;
    contribution?: number;
    description?: string;
    type?: string;
  }[];
  /** What-if scenarios */
  counterfactuals?: {
    scenario?: string;
    outcome?: string;
    probability?: number;
  }[];
  /** Decision provenance chain */
  provenance?: {
    step?: number;
    action?: string;
    agent?: string;
    confidence?: number;
    timestamp?: string;
  }[];
  generated_at?: string;
}

export interface EvidenceLink {
  id: string;
  content: string;
  source: string;
  relevance_score: number;
  quality_scores?: Record<string, any>;
  cited_by?: string[];
  grounding_type?: string;
  timestamp?: string;
  metadata?: Record<string, any>;
}

export interface EvidenceChain {
  debate_id: string;
  evidence_count: number;
  evidence_quality_score?: number;
  evidence: EvidenceLink[];
}

export interface VotePivot {
  agent: string;
  choice: string;
  confidence: number;
  weight: number;
  reasoning_summary: string;
  influence_score?: number;
  calibration_adjustment?: number;
  elo_rating?: number;
  flip_detected?: boolean;
  metadata?: Record<string, any>;
}

export interface VotePivots {
  debate_id: string;
  total_votes?: number;
  pivotal_votes?: number;
  agent_agreement_score?: number;
  votes: VotePivot[];
}

export interface Counterfactual {
  condition: string;
  outcome_change: string;
  likelihood: number;
  sensitivity: number;
  affected_agents?: string[];
  metadata?: Record<string, any>;
}

export interface Counterfactuals {
  debate_id: string;
  counterfactual_count?: number;
  counterfactuals: Counterfactual[];
}

export interface DebateSummary {
  debate_id: string;
  summary: string;
  confidence?: number;
  consensus_reached?: boolean;
}

export interface ExplainabilityBatch {
  batch_id: string;
  status: string;
  total_debates: number;
  status_url?: string;
  results_url?: string;
}

export interface ExplainabilityBatchStatus {
  batch_id: string;
  status: string;
  total_debates: number;
  processed_count?: number;
  success_count?: number;
  error_count?: number;
  created_at?: number;
  started_at?: number;
  completed_at?: number;
  progress_pct?: number;
}

export interface BatchDebateResult {
  debate_id: string;
  status: string;
  processing_time_ms?: number;
  explanation?: Record<string, any>;
  error?: string;
}

export interface ExplainabilityBatchResults {
  batch_id: string;
  status: string;
  total_debates: number;
  processed_count?: number;
  success_count?: number;
  error_count?: number;
  created_at?: number;
  started_at?: number;
  completed_at?: number;
  progress_pct?: number;
  results: BatchDebateResult[];
  pagination?: {
    offset?: number;
    limit?: number;
    total?: number;
    has_more?: boolean;
  };
}

export interface ControlPlaneAgent {
  agent_id: string;
  capabilities: string[];
  status: string;
  model?: string;
  provider?: string;
  metadata?: Record<string, any>;
  registered_at?: number;
  last_heartbeat?: number;
  current_task_id?: string;
  tasks_completed?: number;
  tasks_failed?: number;
  avg_latency_ms?: number;
  region_id?: string;
  available_regions?: string[];
  region_latency_ms?: Record<string, any>;
  last_heartbeat_by_region?: Record<string, any>;
}

export interface ControlPlaneAgentList {
  agents: ControlPlaneAgent[];
  total: number;
}

export interface ControlPlaneTask {
  id: string;
  task_type: string;
  payload?: Record<string, any>;
  required_capabilities?: string[];
  status: string;
  priority?: string;
  created_at?: number;
  assigned_at?: number;
  started_at?: number;
  completed_at?: number;
  assigned_agent?: string;
  timeout_seconds?: number;
  max_retries?: number;
  retries?: number;
  result?: Record<string, any>;
  error?: string;
  metadata?: Record<string, any>;
  target_region?: string;
  fallback_regions?: string[];
  assigned_region?: string;
  region_routing_mode?: string;
  origin_region?: string;
}

export interface ControlPlaneTaskCreated {
  task_id: string;
}

export interface ControlPlaneTaskClaimResponse {
  task?: any;
}

export interface ControlPlaneQueueJob {
  id?: string;
  type?: string;
  name?: string;
  status?: string;
  progress?: number;
  started_at?: string;
  created_at?: string;
  document_count?: number;
  agents_assigned?: string[];
  priority?: string;
}

export interface ControlPlaneQueue {
  jobs: ControlPlaneQueueJob[];
  total: number;
}

export interface ControlPlaneMetrics {
  active_jobs?: number;
  queued_jobs?: number;
  completed_jobs?: number;
  agents_available?: number;
  agents_busy?: number;
  total_agents?: number;
  documents_processed_today?: number;
  audits_completed_today?: number;
  tokens_used_today?: number;
}

export interface ControlPlaneStats {
  scheduler?: Record<string, any>;
  registry?: Record<string, any>;
}

export interface ControlPlaneHealth {
  status?: string;
  agents?: Record<string, any>;
}

export interface VulnerabilityReference {
  url?: string;
  source?: string;
  tags?: string[];
}

export interface VulnerabilityFinding {
  id?: string;
  title?: string;
  description?: string;
  severity?: string;
  cvss_score?: number;
  package_name?: string;
  package_ecosystem?: string;
  vulnerable_versions?: string[];
  patched_versions?: string[];
  source?: string;
  references?: VulnerabilityReference[];
  cwe_ids?: string[];
  fix_available?: boolean;
  recommended_version?: string;
}

export interface DependencyInfo {
  name?: string;
  version?: string;
  ecosystem?: string;
  direct?: boolean;
  dev_dependency?: boolean;
  license?: string;
  vulnerabilities?: VulnerabilityFinding[];
  has_vulnerabilities?: boolean;
  highest_severity?: string;
}

export interface CodebaseScanSummary {
  total_dependencies?: number;
  vulnerable_dependencies?: number;
  critical_count?: number;
  high_count?: number;
  medium_count?: number;
  low_count?: number;
}

export interface CodebaseScanResult {
  scan_id?: string;
  repository?: string;
  branch?: string;
  commit_sha?: string;
  started_at?: string;
  completed_at?: string;
  status?: string;
  error?: string;
  dependencies?: DependencyInfo[];
  vulnerabilities?: VulnerabilityFinding[];
  summary?: CodebaseScanSummary;
}

export interface CodebaseScanStartResponse {
  success?: boolean;
  scan_id?: string;
  status?: string;
  repository?: string;
}

export interface CodebaseScanResultResponse {
  success?: boolean;
  scan_result?: CodebaseScanResult;
}

export interface CodebaseScanListResponse {
  success?: boolean;
  scans?: Record<string, any>[];
  total?: number;
  limit?: number;
  offset?: number;
}

export interface CodebaseVulnerabilityListResponse {
  success?: boolean;
  vulnerabilities?: VulnerabilityFinding[];
  total?: number;
  limit?: number;
  offset?: number;
  scan_id?: string;
}

export interface CodebasePackageVulnerabilityResponse {
  success?: boolean;
  package?: string;
  ecosystem?: string;
  version?: string;
  vulnerabilities?: VulnerabilityFinding[];
  total?: number;
}

export interface CodebaseCVEResponse {
  success?: boolean;
  vulnerability?: VulnerabilityFinding;
}

export interface CodebaseMetricsStartResponse {
  success?: boolean;
  analysis_id?: string;
  status?: string;
  repository?: string;
}

export interface CodebaseMetricsReportResponse {
  success?: boolean;
  report?: Record<string, any>;
}

export interface CodebaseHotspot {
  file_path?: string;
  function_name?: string;
  class_name?: string;
  start_line?: number;
  end_line?: number;
  complexity?: number;
  lines_of_code?: number;
  risk_score?: number;
}

export interface CodebaseHotspotListResponse {
  success?: boolean;
  hotspots?: CodebaseHotspot[];
  total?: number;
  analysis_id?: string;
}

export interface CodebaseDuplicateListResponse {
  success?: boolean;
  duplicates?: Record<string, any>[];
  total?: number;
  analysis_id?: string;
}

export interface CodebaseFileMetricsResponse {
  success?: boolean;
  file?: Record<string, any>;
  analysis_id?: string;
}

export interface CodebaseMetricsHistoryResponse {
  success?: boolean;
  analyses?: Record<string, any>[];
  total?: number;
  limit?: number;
  offset?: number;
}

export interface DecisionRequest {
  request_id?: string;
  content: string;
  decision_type?: string;
  source?: string;
  response_channels?: Record<string, any>[];
  context?: Record<string, any>;
  config?: Record<string, any>;
  priority?: string;
  attachments?: Record<string, any>[];
  evidence?: Record<string, any>[];
}

export interface DecisionResult {
  request_id: string;
  decision_type: string;
  answer: string;
  confidence: number;
  consensus_reached?: boolean;
  reasoning?: string;
  evidence_used?: Record<string, any>[];
  agent_contributions?: Record<string, any>[];
  duration_seconds?: number;
  completed_at?: string;
  success?: boolean;
  error?: string;
}

export interface DecisionStatus {
  request_id: string;
  status: string;
  completed_at?: string;
}

export interface DecisionSummary {
  request_id: string;
  status?: string;
  completed_at?: string;
}

export interface DecisionList {
  decisions: DecisionSummary[];
  total: number;
}

export interface DeliberationRequest {
  request_id?: string;
  content: string;
  decision_type?: string;
  async?: boolean;
  priority?: string;
  timeout_seconds?: number;
  required_capabilities?: string[];
  response_channels?: Record<string, any>[];
  metadata?: Record<string, any>;
}

export interface DeliberationQueuedResponse {
  task_id: string;
  request_id: string;
  status: string;
}

export interface DeliberationSyncResponse {
  request_id: string;
  status: string;
  decision_type?: string;
  answer?: string;
  confidence?: number;
  consensus_reached?: boolean;
  reasoning?: string;
  evidence_used?: Record<string, any>[];
  duration_seconds?: number;
  error?: string;
}

export interface DeliberationRecord {
  request_id: string;
  status: string;
  result?: DecisionResult;
  completed_at?: string;
  error?: string;
  metrics?: Record<string, any>;
}

export interface DeliberationStatus {
  request_id: string;
  status: string;
  completed_at?: string;
}

export interface GitHubReviewComment {
  id: string;
  file_path: string;
  line: number;
  body: string;
  side?: string;
  suggestion?: string;
  severity?: string;
  category?: string;
}

export interface GitHubPRReviewResult {
  review_id: string;
  pr_number: number;
  repository: string;
  status: string;
  verdict?: string;
  summary?: string;
  comments: GitHubReviewComment[];
  started_at: string;
  completed_at?: string;
  error?: string;
  metrics?: Record<string, any>;
}

export interface GitHubPRDetails {
  number: number;
  title: string;
  body?: string;
  state: string;
  author: string;
  base_branch: string;
  head_branch: string;
  changed_files?: {
    filename?: string;
    status?: string;
    additions?: number;
    deletions?: number;
    patch?: string;
  }[];
  commits?: Record<string, any>[];
  labels?: string[];
  created_at?: string;
  updated_at?: string;
}

export interface GitHubPRReviewTriggerRequest {
  /** owner/repo */
  repository: string;
  pr_number: number;
  review_type?: "comprehensive" | "quick" | "security";
  workspace_id?: string;
}

export interface GitHubPRReviewTriggerResponse {
  success: boolean;
  review_id?: string;
  status?: string;
  pr_number?: number;
  repository?: string;
  error?: string;
}

export interface GitHubPRDetailsResponse {
  success: boolean;
  pr?: GitHubPRDetails;
  error?: string;
}

export interface GitHubPRReviewStatusResponse {
  success: boolean;
  review?: GitHubPRReviewResult;
  error?: string;
}

export interface GitHubPRReviewListResponse {
  success: boolean;
  reviews: GitHubPRReviewResult[];
  total: number;
  error?: string;
}

export interface GitHubPRSubmitReviewRequest {
  /** owner/repo */
  repository: string;
  event: "APPROVE" | "REQUEST_CHANGES" | "COMMENT";
  body?: string;
  comments?: {
    path: string;
    position: number;
    body: string;
  }[];
}

export interface GitHubPRSubmitReviewResponse {
  success: boolean;
  demo?: boolean;
  data?: Record<string, any>;
  error?: string;
}

export interface CostBreakdownItem {
  name?: string;
  cost?: number;
  percentage?: number;
}

export interface CostDailyItem {
  date?: string;
  cost?: number;
  tokens?: number;
}

export interface CostAlert {
  id?: string;
  type?: string;
  message?: string;
  severity?: string;
  timestamp?: string;
}

export interface CostSummaryResponse {
  totalCost?: number;
  budget?: number;
  tokensUsed?: number;
  apiCalls?: number;
  lastUpdated?: string;
  costByProvider?: CostBreakdownItem[];
  costByFeature?: CostBreakdownItem[];
  dailyCosts?: CostDailyItem[];
  alerts?: CostAlert[];
}

export interface CostBreakdownResponse {
  groupBy?: string;
  breakdown?: CostBreakdownItem[];
  total?: number;
}

export interface CostTimelineResponse {
  timeline?: CostDailyItem[];
  total?: number;
  average?: number;
}

export interface CostAlertsResponse {
  alerts?: CostAlert[];
}

export interface CostBudgetRequest {
  budget: number;
  workspace_id?: string;
}

export interface CostBudgetResponse {
  success: boolean;
  budget?: number;
  workspace_id?: string;
}

export interface CostDismissAlertResponse {
  success: boolean;
}

export interface SharedInbox {
  id?: string;
  workspace_id?: string;
  name?: string;
  description?: string;
  email_address?: string;
  connector_type?: string;
  team_members?: string[];
  admins?: string[];
  message_count?: number;
  unread_count?: number;
  settings?: Record<string, any>;
  created_at?: string;
  updated_at?: string;
  created_by?: string;
}

export interface SharedInboxMessage {
  id?: string;
  inbox_id?: string;
  email_id?: string;
  subject?: string;
  from_address?: string;
  to_addresses?: string[];
  snippet?: string;
  received_at?: string;
  status?: string;
  assigned_to?: string;
  tags?: string[];
  priority?: string;
}

export interface SharedInboxResponse {
  success: boolean;
  inbox?: SharedInbox;
  error?: string;
}

export interface SharedInboxListResponse {
  success: boolean;
  inboxes: SharedInbox[];
  total: number;
}

export interface SharedInboxMessageListResponse {
  success: boolean;
  messages: SharedInboxMessage[];
  total: number;
  limit?: number;
  offset?: number;
}

export interface SharedInboxMessageResponse {
  success: boolean;
  message?: SharedInboxMessage;
  error?: string;
}

export interface RoutingRule {
  id?: string;
  workspace_id?: string;
  name?: string;
  conditions?: Record<string, any>[];
  condition_logic?: string;
  actions?: Record<string, any>[];
  priority?: number;
  enabled?: boolean;
  description?: string;
  created_at?: string;
  updated_at?: string;
  created_by?: string;
  stats?: Record<string, any>;
}

export interface RoutingRuleResponse {
  success: boolean;
  rule?: RoutingRule;
  error?: string;
}

export interface RoutingRuleListResponse {
  success: boolean;
  rules: RoutingRule[];
  total: number;
  limit?: number;
  offset?: number;
}

export interface RoutingRuleDeleteResponse {
  success: boolean;
  deleted?: string;
}

export interface RoutingRuleTestResponse {
  success: boolean;
  rule_id?: string;
  match_count?: number;
  rule?: RoutingRule;
  error?: string;
}

export interface SharedInboxCreateRequest {
  workspace_id: string;
  name: string;
  description?: string;
  email_address?: string;
  connector_type?: string;
  team_members?: string[];
  admins?: string[];
  settings?: Record<string, any>;
}

export interface SharedInboxAssignRequest {
  assigned_to: string;
}

export interface SharedInboxStatusRequest {
  status: string;
}

export interface SharedInboxTagRequest {
  tag: string;
}

export interface RoutingRuleCreateRequest {
  workspace_id: string;
  name: string;
  conditions: Record<string, any>[];
  condition_logic?: string;
  actions: Record<string, any>[];
  priority?: number;
  enabled?: boolean;
  description?: string;
}

export interface RoutingRuleUpdateRequest {
  name?: string;
  description?: string;
  conditions?: Record<string, any>[];
  condition_logic?: string;
  actions?: Record<string, any>[];
  priority?: number;
  enabled?: boolean;
}

export interface RoutingRuleTestRequest {
  workspace_id: string;
}

export interface CodebaseDependencyAnalysisRequest {
  repo_path: string;
  include_dev?: boolean;
}

export interface CodebaseDependencyAnalysisResponse {
  status?: string;
  data?: Record<string, any>;
  message?: string;
}

export interface CodebaseDependencyScanRequest {
  repo_path: string;
}

export interface CodebaseDependencyScanResponse {
  status?: string;
  data?: Record<string, any>;
  message?: string;
}

export interface CodebaseLicenseCheckRequest {
  repo_path: string;
  project_license?: string;
}

export interface CodebaseLicenseCheckResponse {
  status?: string;
  data?: Record<string, any>;
  message?: string;
}

export interface CodebaseSBOMRequest {
  repo_path: string;
  format?: string;
  include_vulnerabilities?: boolean;
}

export interface CodebaseSBOMResponse {
  status?: string;
  data?: Record<string, any>;
  message?: string;
}

export interface CodebaseSecretsScanRequest {
  repo_path: string;
  branch?: string;
  commit_sha?: string;
}

export interface CodebaseSecretsScanStartResponse {
  success: boolean;
  scan_id?: string;
  status?: string;
  repository?: string;
  error?: string;
}

export interface CodebaseSecretsScanResultResponse {
  success: boolean;
  scan_result?: Record<string, any>;
  error?: string;
}

export interface CodebaseSecretsListResponse {
  success: boolean;
  secrets?: Record<string, any>[];
  total?: number;
}

export interface CodebaseSecretsScanListResponse {
  success: boolean;
  scans?: Record<string, any>[];
  total?: number;
}

export type BudgetPeriod = "daily" | "weekly" | "monthly" | "quarterly" | "annual" | "unlimited";

export type BudgetStatus = "active" | "warning" | "critical" | "exceeded" | "suspended" | "paused" | "closed";

export type BudgetAction = "notify" | "warn" | "soft_limit" | "hard_limit" | "suspend";

export interface BudgetThreshold {
  /** Threshold percentage (0.0 - 1.0) */
  percentage: number;
  action: BudgetAction;
}

export interface Budget {
  /** Unique budget identifier */
  budget_id: string;
  /** Organization ID */
  org_id: string;
  /** Budget name */
  name: string;
  /** Budget description */
  description?: string;
  /** Budget limit in USD */
  amount_usd: number;
  period?: BudgetPeriod;
  /** Amount spent in current period */
  spent_usd?: number;
  /** Remaining budget */
  remaining_usd?: number;
  /** Current usage as percentage (0.0 - 1.0+) */
  usage_percentage?: number;
  /** Period start timestamp */
  period_start?: number;
  period_start_iso?: string;
  /** Period end timestamp */
  period_end?: number;
  period_end_iso?: string;
  status?: BudgetStatus;
  current_action?: BudgetAction;
  /** Auto-suspend on exceed */
  auto_suspend?: boolean;
  /** Whether budget is exceeded */
  is_exceeded?: boolean;
  thresholds?: BudgetThreshold[];
  /** Creation timestamp */
  created_at?: number;
  /** Last update timestamp */
  updated_at?: number;
}

export interface BudgetCreateRequest {
  /** Budget name */
  name: string;
  /** Budget limit in USD */
  amount_usd: number;
  period?: BudgetPeriod;
  /** Budget description */
  description?: string;
  /** Auto-suspend when exceeded */
  auto_suspend?: boolean;
}

export interface BudgetUpdateRequest {
  name?: string;
  description?: string;
  amount_usd?: number;
  auto_suspend?: boolean;
  status?: BudgetStatus;
}

export interface BudgetListResponse {
  budgets: Budget[];
  count: number;
  org_id?: string;
}

export interface BudgetSummary {
  org_id: string;
  total_budget_usd: number;
  total_spent_usd: number;
  total_remaining_usd?: number;
  overall_usage_percentage?: number;
  active_budgets?: number;
  exceeded_budgets?: number;
  budgets?: Budget[];
}

export interface BudgetCheckRequest {
  /** Estimated operation cost */
  estimated_cost_usd: number;
}

export interface BudgetCheckResponse {
  /** Whether operation is allowed */
  allowed: boolean;
  /** Explanation */
  reason: string;
  /** Required action if any */
  action?: any;
  estimated_cost_usd?: number;
}

export interface BudgetAlert {
  alert_id: string;
  budget_id: string;
  org_id?: string;
  threshold_percentage?: number;
  action?: BudgetAction;
  spent_usd?: number;
  amount_usd?: number;
  usage_percentage?: number;
  message: string;
  created_at?: number;
  created_at_iso?: string;
  acknowledged?: boolean;
  acknowledged_by?: any;
  acknowledged_at?: any;
}

export interface BudgetAlertListResponse {
  alerts: BudgetAlert[];
  count: number;
  budget_id?: string;
}

export interface BudgetOverrideRequest {
  /** User to grant override */
  user_id: string;
  /** Override duration (null for permanent) */
  duration_hours?: any;
}

export interface BudgetOverrideResponse {
  override_added: boolean;
  budget_id: string;
  user_id: string;
  duration_hours?: any;
}

export interface DisagreementStats {
  /** Total debates analyzed */
  total_debates?: number;
  /** Debates with disagreements */
  with_disagreements?: number;
  /** Unanimous debates */
  unanimous?: number;
  /** Count by disagreement type */
  disagreement_types?: Record<string, any>;
}

export interface RoleRotationStats {
  total_rotations?: number;
  by_agent?: Record<string, any>;
}

export interface EarlyStopStats {
  total_early_stops?: number;
  by_reason?: Record<string, any>;
  average_rounds_saved?: number;
}

export interface RankingStats {
  total_agents?: number;
  average_elo?: number;
  highest_elo?: number;
  lowest_elo?: number;
  total_matches?: number;
}

export interface MemoryStats {
  total_entries?: number;
  by_tier?: {
    fast?: number;
    medium?: number;
    slow?: number;
    glacial?: number;
  };
  cache_hit_rate?: number;
}

export interface KnowledgeNode {
  /** Unique node ID */
  id: string;
  /** Node content */
  content: string;
  /** Knowledge source type */
  source?: string;
  /** Confidence score 0-1 */
  confidence?: number;
  created_at?: string;
  updated_at?: string;
  topics?: string[];
  metadata?: Record<string, any>;
}

export interface KnowledgeQueryResult {
  items?: KnowledgeNode[];
  total?: number;
  query?: string;
  relevance_scores?: number[];
}

export interface KnowledgeStoreResult {
  node_id: string;
  success: boolean;
  duplicate?: boolean;
  topics_extracted?: string[];
}

export interface KnowledgeFact {
  id: string;
  statement: string;
  workspace_id?: string;
  confidence?: number;
  validation_status?: string;
  topics?: string[];
  evidence_ids?: string[];
  source_documents?: string[];
  metadata?: Record<string, any>;
  created_at?: string;
  updated_at?: string;
}

export interface KnowledgeFactList {
  facts?: KnowledgeFact[];
  total?: number;
  limit?: number;
  offset?: number;
}

export interface KnowledgeSearchResult {
  id?: string;
  content?: string;
  score?: number;
  metadata?: Record<string, any>;
}

export interface KnowledgeSearchResponse {
  query?: string;
  workspace_id?: string;
  results?: KnowledgeSearchResult[];
  count?: number;
}

export interface KnowledgeStats {
  workspace_id?: string;
  total_facts?: number;
  total_entries?: number;
  sources?: Record<string, any>;
  categories?: Record<string, any>;
  avg_confidence?: number;
  last_updated?: string;
}

export interface KnowledgeQueryResponse {
}

export interface AgentRegistration {
  agent_id: string;
  name: string;
  capabilities?: string[];
  status: "healthy" | "degraded" | "unhealthy";
  last_heartbeat?: string;
  metadata?: Record<string, any>;
}

export interface TaskStatus {
  task_id: string;
  status: "pending" | "running" | "completed" | "failed" | "cancelled";
  progress?: number;
  result?: Record<string, any>;
  error?: string;
  created_at?: string;
  updated_at?: string;
}

export interface PolicyEvaluation {
  allowed: boolean;
  policy_id?: string;
  reason?: string;
  conditions_met?: string[];
  conditions_failed?: string[];
}

export interface PositionFlip {
  debate_id?: string;
  agent?: string;
  round?: number;
  old_position?: string;
  new_position?: string;
  reason?: string;
  conviction_delta?: number;
  timestamp?: string;
}

export interface FlipsRecent {
  flips?: PositionFlip[];
  total?: number;
}

export interface FlipsSummary {
  total_flips?: number;
  by_agent?: Record<string, any>;
  by_debate?: Record<string, any>;
  average_conviction_delta?: number;
  /** Percentage of debates with flips */
  flip_rate?: number;
}

export interface Insight {
  id?: string;
  debate_id?: string;
  content?: string;
  type?: "observation" | "conclusion" | "recommendation";
  confidence?: number;
  supporting_evidence?: string[];
  extracted_at?: string;
}

export interface InsightsRecent {
  insights?: Insight[];
  total?: number;
}

export interface InsightsDetailed {
  insights?: Insight[];
  themes?: string[];
  key_findings?: string[];
  processing_time_ms?: number;
}

export interface DebateMoment {
  id?: string;
  debate_id?: string;
  type?: "breakthrough" | "conflict" | "consensus" | "insight" | "flip";
  round?: number;
  description?: string;
  participants?: string[];
  significance_score?: number;
  timestamp?: string;
}

export interface MomentsSummary {
  total_moments?: number;
  by_type?: Record<string, any>;
  top_debates?: {
    debate_id?: string;
    moment_count?: number;
  }[];
}

export interface MomentsTimeline {
  moments?: DebateMoment[];
  start_time?: string;
  end_time?: string;
}

export interface MomentsTrending {
  moments?: DebateMoment[];
  trending_period_hours?: number;
}

export interface MomentsByType {
  type?: string;
  moments?: DebateMoment[];
  total?: number;
}

export interface UnifiedCampaign {
  /** Platform-specific campaign ID */
  id: string;
  /** Advertising platform name */
  platform: "google_ads" | "meta_ads" | "linkedin_ads" | "microsoft_ads";
  /** Campaign name */
  name: string;
  /** Campaign status */
  status: "ENABLED" | "PAUSED" | "REMOVED";
  /** Campaign objective/goal */
  objective?: string;
  /** Daily budget in account currency */
  daily_budget?: number;
  /** Total campaign budget */
  total_budget?: number;
  /** Campaign start date */
  start_date?: string;
  /** Campaign end date */
  end_date?: string;
  /** When the campaign was created */
  created_at?: string;
  /** When the campaign was last updated */
  updated_at?: string;
}
