"""
Metrics package for Aragora observability.

This package provides Prometheus metrics for monitoring request rates, latencies,
agent performance, and debate statistics.

The metrics module has been refactored into domain-specific submodules:
- base: Shared utilities (NoOpMetric, initialization helpers)
- core: Request, agent, debate, and cache metrics
- bridge: Cross-pollination bridge metrics
- km: Knowledge Mound metrics
- notification: Notification delivery metrics
- stores: Task queue, governance, checkpoint, user mapping metrics
- gauntlet: Gauntlet export and workflow template metrics

For backward compatibility, all metrics and functions are re-exported from
the parent metrics module (aragora.observability.metrics).
"""

from aragora.observability.metrics.base import (
    NoOpMetric,
    get_metrics_enabled,
    ensure_metrics_initialized,
)
from aragora.observability.metrics.core import (
    # Metrics
    REQUEST_COUNT,
    REQUEST_LATENCY,
    AGENT_CALLS,
    AGENT_LATENCY,
    ACTIVE_DEBATES,
    CONSENSUS_RATE,
    MEMORY_OPERATIONS,
    WEBSOCKET_CONNECTIONS,
    DEBATE_DURATION,
    DEBATE_ROUNDS,
    DEBATE_PHASE_DURATION,
    AGENT_PARTICIPATION,
    CACHE_HITS,
    CACHE_MISSES,
    KNOWLEDGE_CACHE_HITS,
    KNOWLEDGE_CACHE_MISSES,
    MEMORY_COORDINATOR_WRITES,
    SELECTION_FEEDBACK_ADJUSTMENTS,
    WORKFLOW_TRIGGERS,
    EVIDENCE_STORED,
    CULTURE_PATTERNS,
    RLM_CACHE_HITS,
    RLM_CACHE_MISSES,
    CALIBRATION_ADJUSTMENTS,
    LEARNING_BONUSES,
    VOTING_ACCURACY_UPDATES,
    ADAPTIVE_ROUND_CHANGES,
    SLOW_DEBATES_TOTAL,
    SLOW_ROUNDS_TOTAL,
    DEBATE_ROUND_LATENCY,
    TTS_SYNTHESIS_TOTAL,
    TTS_SYNTHESIS_LATENCY,
    CONVERGENCE_CHECKS_TOTAL,
    EVIDENCE_CITATION_BONUSES,
    PROCESS_EVALUATION_BONUSES,
    RLM_READY_QUORUM_EVENTS,
    # Functions
    record_request,
    record_agent_call,
    track_debate,
    set_consensus_rate,
    record_memory_operation,
    track_websocket_connection,
    measure_latency,
    measure_async_latency,
    record_debate_completion,
    record_phase_duration,
    record_agent_participation,
    track_phase,
    record_cache_hit,
    record_cache_miss,
    record_knowledge_cache_hit,
    record_knowledge_cache_miss,
    record_memory_coordinator_write,
    record_selection_feedback_adjustment,
    record_workflow_trigger,
    record_evidence_stored,
    record_culture_patterns,
    record_rlm_cache_hit,
    record_rlm_cache_miss,
    record_calibration_adjustment,
    record_learning_bonus,
    record_voting_accuracy_update,
    record_adaptive_round_change,
    record_slow_debate,
    record_slow_round,
    record_round_latency,
    record_tts_synthesis,
    record_tts_latency,
    record_convergence_check,
    record_evidence_citation_bonus,
    record_process_evaluation_bonus,
    record_rlm_ready_quorum,
    start_metrics_server,
    init_core_metrics,
)
from aragora.observability.metrics.bridge import (
    # Metrics
    BRIDGE_SYNCS,
    BRIDGE_SYNC_LATENCY,
    BRIDGE_ERRORS,
    PERFORMANCE_ROUTING_DECISIONS,
    PERFORMANCE_ROUTING_LATENCY,
    OUTCOME_COMPLEXITY_ADJUSTMENTS,
    ANALYTICS_SELECTION_RECOMMENDATIONS,
    NOVELTY_SCORE_CALCULATIONS,
    NOVELTY_PENALTIES,
    ECHO_CHAMBER_DETECTIONS,
    RELATIONSHIP_BIAS_ADJUSTMENTS,
    RLM_SELECTION_RECOMMENDATIONS,
    CALIBRATION_COST_CALCULATIONS,
    BUDGET_FILTERING_EVENTS,
    # Functions
    record_bridge_sync,
    record_bridge_sync_latency,
    record_bridge_error,
    record_performance_routing_decision,
    record_performance_routing_latency,
    record_outcome_complexity_adjustment,
    record_analytics_selection_recommendation,
    record_novelty_score_calculation,
    record_novelty_penalty,
    record_echo_chamber_detection,
    record_relationship_bias_adjustment,
    record_rlm_selection_recommendation,
    record_calibration_cost_calculation,
    record_budget_filtering_event,
    track_bridge_sync,
    init_bridge_metrics,
)
from aragora.observability.metrics.km import (
    # Metrics
    KM_OPERATIONS_TOTAL,
    KM_OPERATION_LATENCY,
    KM_CACHE_HITS_TOTAL,
    KM_CACHE_MISSES_TOTAL,
    KM_HEALTH_STATUS,
    KM_ADAPTER_SYNCS_TOTAL,
    KM_FEDERATED_QUERIES_TOTAL,
    KM_EVENTS_EMITTED_TOTAL,
    KM_ACTIVE_ADAPTERS,
    # Functions
    record_km_operation,
    record_km_cache_access,
    set_km_health_status,
    record_km_adapter_sync,
    record_km_federated_query,
    record_km_event_emitted,
    set_km_active_adapters,
    sync_km_metrics_to_prometheus,
    init_km_metrics,
)
from aragora.observability.metrics.notification import (
    # Metrics
    NOTIFICATION_SENT_TOTAL,
    NOTIFICATION_LATENCY,
    NOTIFICATION_ERRORS_TOTAL,
    NOTIFICATION_QUEUE_SIZE,
    # Functions
    record_notification_sent,
    record_notification_error,
    set_notification_queue_size,
    track_notification_delivery,
    init_notification_metrics,
)
from aragora.observability.metrics.stores import (
    # Task Queue Metrics
    TASK_QUEUE_OPERATIONS_TOTAL,
    TASK_QUEUE_OPERATION_LATENCY,
    TASK_QUEUE_SIZE,
    TASK_QUEUE_RECOVERED_TOTAL,
    TASK_QUEUE_CLEANUP_TOTAL,
    # Governance Metrics
    GOVERNANCE_DECISIONS_TOTAL,
    GOVERNANCE_VERIFICATIONS_TOTAL,
    GOVERNANCE_APPROVALS_TOTAL,
    GOVERNANCE_STORE_LATENCY,
    GOVERNANCE_ARTIFACTS_ACTIVE,
    # User Mapping Metrics
    USER_MAPPING_OPERATIONS_TOTAL,
    USER_MAPPING_CACHE_HITS_TOTAL,
    USER_MAPPING_CACHE_MISSES_TOTAL,
    USER_MAPPINGS_ACTIVE,
    # Checkpoint Metrics
    CHECKPOINT_OPERATIONS,
    CHECKPOINT_OPERATION_LATENCY,
    CHECKPOINT_SIZE,
    CHECKPOINT_RESTORE_RESULTS,
    # Functions
    record_task_queue_operation,
    set_task_queue_size,
    record_task_queue_recovery,
    record_task_queue_cleanup,
    track_task_queue_operation,
    record_governance_decision,
    record_governance_verification,
    record_governance_approval,
    record_governance_store_latency,
    set_governance_artifacts_active,
    track_governance_store_operation,
    record_user_mapping_operation,
    record_user_mapping_cache_hit,
    record_user_mapping_cache_miss,
    set_user_mappings_active,
    record_checkpoint_operation,
    record_checkpoint_restore_result,
    track_checkpoint_operation,
    init_store_metrics,
)
from aragora.observability.metrics.gauntlet import (
    # Gauntlet Metrics
    GAUNTLET_EXPORTS_TOTAL,
    GAUNTLET_EXPORT_LATENCY,
    GAUNTLET_EXPORT_SIZE,
    # Workflow Metrics
    WORKFLOW_TEMPLATES_CREATED,
    WORKFLOW_TEMPLATE_EXECUTIONS,
    WORKFLOW_TEMPLATE_EXECUTION_LATENCY,
    # Consensus Ingestion Metrics
    CONSENSUS_INGESTION_TOTAL,
    CONSENSUS_INGESTION_LATENCY,
    CONSENSUS_INGESTION_CLAIMS,
    CONSENSUS_DISSENT_INGESTED,
    CONSENSUS_EVOLUTION_TRACKED,
    CONSENSUS_EVIDENCE_LINKED,
    CONSENSUS_AGREEMENT_RATIO,
    # Functions
    record_gauntlet_export,
    track_gauntlet_export,
    record_workflow_template_created,
    record_workflow_template_execution,
    track_workflow_template_execution,
    record_consensus_ingestion,
    record_consensus_dissent,
    record_consensus_evolution,
    record_consensus_evidence_linked,
    record_consensus_agreement_ratio,
    record_km_inbound_event,
    init_gauntlet_metrics,
)

__all__ = [
    # Base
    "NoOpMetric",
    "get_metrics_enabled",
    "ensure_metrics_initialized",
    # Core metrics
    "REQUEST_COUNT",
    "REQUEST_LATENCY",
    "AGENT_CALLS",
    "AGENT_LATENCY",
    "ACTIVE_DEBATES",
    "CONSENSUS_RATE",
    "MEMORY_OPERATIONS",
    "WEBSOCKET_CONNECTIONS",
    "DEBATE_DURATION",
    "DEBATE_ROUNDS",
    "DEBATE_PHASE_DURATION",
    "AGENT_PARTICIPATION",
    "CACHE_HITS",
    "CACHE_MISSES",
    "KNOWLEDGE_CACHE_HITS",
    "KNOWLEDGE_CACHE_MISSES",
    "MEMORY_COORDINATOR_WRITES",
    "SELECTION_FEEDBACK_ADJUSTMENTS",
    "WORKFLOW_TRIGGERS",
    "EVIDENCE_STORED",
    "CULTURE_PATTERNS",
    "RLM_CACHE_HITS",
    "RLM_CACHE_MISSES",
    "CALIBRATION_ADJUSTMENTS",
    "LEARNING_BONUSES",
    "VOTING_ACCURACY_UPDATES",
    "ADAPTIVE_ROUND_CHANGES",
    "SLOW_DEBATES_TOTAL",
    "SLOW_ROUNDS_TOTAL",
    "DEBATE_ROUND_LATENCY",
    "TTS_SYNTHESIS_TOTAL",
    "TTS_SYNTHESIS_LATENCY",
    "CONVERGENCE_CHECKS_TOTAL",
    "EVIDENCE_CITATION_BONUSES",
    "PROCESS_EVALUATION_BONUSES",
    "RLM_READY_QUORUM_EVENTS",
    # Core functions
    "record_request",
    "record_agent_call",
    "track_debate",
    "set_consensus_rate",
    "record_memory_operation",
    "track_websocket_connection",
    "measure_latency",
    "measure_async_latency",
    "record_debate_completion",
    "record_phase_duration",
    "record_agent_participation",
    "track_phase",
    "record_cache_hit",
    "record_cache_miss",
    "record_knowledge_cache_hit",
    "record_knowledge_cache_miss",
    "record_memory_coordinator_write",
    "record_selection_feedback_adjustment",
    "record_workflow_trigger",
    "record_evidence_stored",
    "record_culture_patterns",
    "record_rlm_cache_hit",
    "record_rlm_cache_miss",
    "record_calibration_adjustment",
    "record_learning_bonus",
    "record_voting_accuracy_update",
    "record_adaptive_round_change",
    "record_slow_debate",
    "record_slow_round",
    "record_round_latency",
    "record_tts_synthesis",
    "record_tts_latency",
    "record_convergence_check",
    "record_evidence_citation_bonus",
    "record_process_evaluation_bonus",
    "record_rlm_ready_quorum",
    "start_metrics_server",
    "init_core_metrics",
    # Bridge metrics
    "BRIDGE_SYNCS",
    "BRIDGE_SYNC_LATENCY",
    "BRIDGE_ERRORS",
    "PERFORMANCE_ROUTING_DECISIONS",
    "PERFORMANCE_ROUTING_LATENCY",
    "OUTCOME_COMPLEXITY_ADJUSTMENTS",
    "ANALYTICS_SELECTION_RECOMMENDATIONS",
    "NOVELTY_SCORE_CALCULATIONS",
    "NOVELTY_PENALTIES",
    "ECHO_CHAMBER_DETECTIONS",
    "RELATIONSHIP_BIAS_ADJUSTMENTS",
    "RLM_SELECTION_RECOMMENDATIONS",
    "CALIBRATION_COST_CALCULATIONS",
    "BUDGET_FILTERING_EVENTS",
    # Bridge functions
    "record_bridge_sync",
    "record_bridge_sync_latency",
    "record_bridge_error",
    "record_performance_routing_decision",
    "record_performance_routing_latency",
    "record_outcome_complexity_adjustment",
    "record_analytics_selection_recommendation",
    "record_novelty_score_calculation",
    "record_novelty_penalty",
    "record_echo_chamber_detection",
    "record_relationship_bias_adjustment",
    "record_rlm_selection_recommendation",
    "record_calibration_cost_calculation",
    "record_budget_filtering_event",
    "track_bridge_sync",
    "init_bridge_metrics",
    # KM metrics
    "KM_OPERATIONS_TOTAL",
    "KM_OPERATION_LATENCY",
    "KM_CACHE_HITS_TOTAL",
    "KM_CACHE_MISSES_TOTAL",
    "KM_HEALTH_STATUS",
    "KM_ADAPTER_SYNCS_TOTAL",
    "KM_FEDERATED_QUERIES_TOTAL",
    "KM_EVENTS_EMITTED_TOTAL",
    "KM_ACTIVE_ADAPTERS",
    # KM functions
    "record_km_operation",
    "record_km_cache_access",
    "set_km_health_status",
    "record_km_adapter_sync",
    "record_km_federated_query",
    "record_km_event_emitted",
    "set_km_active_adapters",
    "sync_km_metrics_to_prometheus",
    "init_km_metrics",
    # Notification metrics
    "NOTIFICATION_SENT_TOTAL",
    "NOTIFICATION_LATENCY",
    "NOTIFICATION_ERRORS_TOTAL",
    "NOTIFICATION_QUEUE_SIZE",
    # Notification functions
    "record_notification_sent",
    "record_notification_error",
    "set_notification_queue_size",
    "track_notification_delivery",
    "init_notification_metrics",
    # Store metrics
    "TASK_QUEUE_OPERATIONS_TOTAL",
    "TASK_QUEUE_OPERATION_LATENCY",
    "TASK_QUEUE_SIZE",
    "TASK_QUEUE_RECOVERED_TOTAL",
    "TASK_QUEUE_CLEANUP_TOTAL",
    "GOVERNANCE_DECISIONS_TOTAL",
    "GOVERNANCE_VERIFICATIONS_TOTAL",
    "GOVERNANCE_APPROVALS_TOTAL",
    "GOVERNANCE_STORE_LATENCY",
    "GOVERNANCE_ARTIFACTS_ACTIVE",
    "USER_MAPPING_OPERATIONS_TOTAL",
    "USER_MAPPING_CACHE_HITS_TOTAL",
    "USER_MAPPING_CACHE_MISSES_TOTAL",
    "USER_MAPPINGS_ACTIVE",
    "CHECKPOINT_OPERATIONS",
    "CHECKPOINT_OPERATION_LATENCY",
    "CHECKPOINT_SIZE",
    "CHECKPOINT_RESTORE_RESULTS",
    # Store functions
    "record_task_queue_operation",
    "set_task_queue_size",
    "record_task_queue_recovery",
    "record_task_queue_cleanup",
    "track_task_queue_operation",
    "record_governance_decision",
    "record_governance_verification",
    "record_governance_approval",
    "record_governance_store_latency",
    "set_governance_artifacts_active",
    "track_governance_store_operation",
    "record_user_mapping_operation",
    "record_user_mapping_cache_hit",
    "record_user_mapping_cache_miss",
    "set_user_mappings_active",
    "record_checkpoint_operation",
    "record_checkpoint_restore_result",
    "track_checkpoint_operation",
    "init_store_metrics",
    # Gauntlet metrics
    "GAUNTLET_EXPORTS_TOTAL",
    "GAUNTLET_EXPORT_LATENCY",
    "GAUNTLET_EXPORT_SIZE",
    "WORKFLOW_TEMPLATES_CREATED",
    "WORKFLOW_TEMPLATE_EXECUTIONS",
    "WORKFLOW_TEMPLATE_EXECUTION_LATENCY",
    "CONSENSUS_INGESTION_TOTAL",
    "CONSENSUS_INGESTION_LATENCY",
    "CONSENSUS_INGESTION_CLAIMS",
    "CONSENSUS_DISSENT_INGESTED",
    "CONSENSUS_EVOLUTION_TRACKED",
    "CONSENSUS_EVIDENCE_LINKED",
    "CONSENSUS_AGREEMENT_RATIO",
    # Gauntlet functions
    "record_gauntlet_export",
    "track_gauntlet_export",
    "record_workflow_template_created",
    "record_workflow_template_execution",
    "track_workflow_template_execution",
    "record_consensus_ingestion",
    "record_consensus_dissent",
    "record_consensus_evolution",
    "record_consensus_evidence_linked",
    "record_consensus_agreement_ratio",
    "record_km_inbound_event",
    "init_gauntlet_metrics",
]
