"""
Metrics package for Aragora observability.

This package provides Prometheus metrics for monitoring request rates, latencies,
agent performance, and debate statistics.

Submodules:
- base: NoOpMetric class, initialization helpers
- core: Request, agent, debate, cache metrics
- bridge: Cross-pollination bridge metrics
- km: Knowledge Mound metrics
- notification: Notification delivery metrics
- stores: Task queue, governance, checkpoint, user mapping metrics
- gauntlet: Gauntlet export and workflow template metrics
"""

from __future__ import annotations

# Base utilities
from aragora.observability.metrics.base import (
    NoOpMetric,
    get_metrics_enabled,
    ensure_metrics_initialized,
    normalize_endpoint,
)

# Core metrics
from aragora.observability.metrics.core import (
    # Metric instances
    REQUEST_COUNT,
    REQUEST_LATENCY,
    AGENT_CALLS,
    AGENT_LATENCY,
    ACTIVE_DEBATES,
    CONSENSUS_RATE,
    MEMORY_OPERATIONS,
    WEBSOCKET_CONNECTIONS,
    DEBATE_DURATION,
    DEBATE_ROUNDS,
    DEBATE_PHASE_DURATION,
    AGENT_PARTICIPATION,
    CACHE_HITS,
    CACHE_MISSES,
    KNOWLEDGE_CACHE_HITS,
    KNOWLEDGE_CACHE_MISSES,
    MEMORY_COORDINATOR_WRITES,
    SELECTION_FEEDBACK_ADJUSTMENTS,
    WORKFLOW_TRIGGERS,
    EVIDENCE_STORED,
    CULTURE_PATTERNS,
    RLM_CACHE_HITS,
    RLM_CACHE_MISSES,
    CALIBRATION_ADJUSTMENTS,
    LEARNING_BONUSES,
    VOTING_ACCURACY_UPDATES,
    ADAPTIVE_ROUND_CHANGES,
    SLOW_DEBATES_TOTAL,
    SLOW_ROUNDS_TOTAL,
    DEBATE_ROUND_LATENCY,
    TTS_SYNTHESIS_TOTAL,
    TTS_SYNTHESIS_LATENCY,
    CONVERGENCE_DETECTIONS,
    VOTE_BONUS_ADJUSTMENTS,
    PROXY_FALLBACK_COUNT,
    RATE_LIMIT_EVENTS,
    MEMORY_TIER_TRANSITIONS,
    INSIGHT_LEARNING_EVENTS,
    TEAM_COMPOSITION_METRICS,
    DYNAMIC_WEIGHTS_APPLIED,
    BENCHMARK_CYCLES_TOTAL,
    BENCHMARK_CYCLE_LATENCY,
    UNCERTAINTY_ESTIMATES,
    ADAPTIVE_ROUNDS_TRIGGERED,
    PARTICIPANT_VOTES_TOTAL,
    PARTICIPANT_SUGGESTIONS_TOTAL,
    PARTICIPANT_FEEDBACK_LATENCY,
    CIRCUIT_BREAKER_TRIPS,
    CIRCUIT_BREAKER_STATE,
    OBSERVABILITY_HEALTH,
    METRICS_COLLECTION_ERRORS,
    # KM metrics
    KM_OPERATIONS_TOTAL,
    KM_OPERATION_LATENCY,
    KM_CACHE_HITS_TOTAL,
    KM_CACHE_MISSES_TOTAL,
    KM_HEALTH_STATUS,
    KM_ADAPTER_SYNCS_TOTAL,
    KM_FEDERATED_QUERIES_TOTAL,
    KM_EVENTS_EMITTED_TOTAL,
    KM_ACTIVE_ADAPTERS,
    # Recording functions
    record_request,
    record_agent_call,
    record_agent_latency,
    record_debate_started,
    record_debate_completed,
    record_memory_operation,
    record_ws_connection,
    record_ws_disconnection,
    record_debate_phase_duration,
    record_agent_participation,
    record_cache_hit,
    record_cache_miss,
    record_slow_debate,
    record_slow_round,
    record_debate_round_latency,
    record_tts_synthesis,
    record_convergence_detection,
    record_vote_bonus_adjustment,
    record_knowledge_cache_hit,
    record_knowledge_cache_miss,
    record_memory_coordinator_write,
    record_selection_feedback_adjustment,
    record_workflow_trigger,
    record_evidence_stored,
    record_culture_pattern,
    record_rlm_cache_access,
    record_calibration_adjustment,
    record_learning_bonus,
    record_voting_accuracy_update,
    record_adaptive_round_change,
    record_proxy_fallback,
    record_rate_limit_event,
    record_memory_tier_transition,
    record_insight_learning_event,
    record_team_composition,
    record_dynamic_weights,
    record_benchmark_cycle,
    record_uncertainty_estimate,
    record_adaptive_rounds_triggered,
    record_participant_vote,
    record_participant_suggestion,
    record_participant_feedback_latency,
    record_circuit_breaker_trip,
    set_circuit_breaker_state,
    record_observability_health,
    record_metrics_collection_error,
    record_km_operation,
    record_km_cache_access,
    record_km_adapter_sync,
    record_km_federated_query,
    record_km_event_emitted,
    sync_km_metrics_to_prometheus,
    record_km_inbound_event,
    record_km_circuit_breaker_trip,
    record_km_retry,
    record_km_cache_invalidation,
    record_km_integrity_error,
    record_km_integrity_repair,
    # Context managers
    track_request,
    track_agent_call,
    track_debate,
    # Decorators
    track_latency,
    # Init functions
    init_core_metrics,
    start_metrics_server,
    shutdown_metrics_server,
)

# Bridge metrics
from aragora.observability.metrics.bridge import (
    BRIDGE_SYNCS,
    BRIDGE_SYNC_LATENCY,
    BRIDGE_ERRORS,
    PERFORMANCE_ROUTING_DECISIONS,
    PERFORMANCE_ROUTING_LATENCY,
    OUTCOME_COMPLEXITY_ADJUSTMENTS,
    ANALYTICS_SELECTION_RECOMMENDATIONS,
    NOVELTY_SCORE_CALCULATIONS,
    NOVELTY_PENALTIES,
    ECHO_CHAMBER_DETECTIONS,
    RELATIONSHIP_BIAS_ADJUSTMENTS,
    RLM_SELECTION_RECOMMENDATIONS,
    CALIBRATION_COST_CALCULATIONS,
    BUDGET_FILTERING_EVENTS,
    record_bridge_sync,
    record_bridge_sync_latency,
    record_bridge_error,
    record_performance_routing_decision,
    record_performance_routing_latency,
    record_outcome_complexity_adjustment,
    record_analytics_selection_recommendation,
    record_novelty_score_calculation,
    record_novelty_penalty,
    record_echo_chamber_detection,
    record_relationship_bias_adjustment,
    record_rlm_selection_recommendation,
    record_calibration_cost_calculation,
    record_budget_filtering_event,
    track_bridge_sync,
    init_bridge_metrics,
)

# Notification metrics
from aragora.observability.metrics.notification import (
    NOTIFICATION_SENT_TOTAL,
    NOTIFICATION_LATENCY,
    NOTIFICATION_ERRORS_TOTAL,
    NOTIFICATION_QUEUE_SIZE,
    record_notification_sent,
    record_notification_error,
    set_notification_queue_size,
    track_notification_delivery,
    init_notification_metrics,
)

# Store metrics
from aragora.observability.metrics.stores import (
    # Task queue
    TASK_QUEUE_OPERATIONS_TOTAL,
    TASK_QUEUE_OPERATION_LATENCY,
    TASK_QUEUE_SIZE,
    TASK_QUEUE_RECOVERED_TOTAL,
    TASK_QUEUE_CLEANUP_TOTAL,
    record_task_queue_operation,
    set_task_queue_size,
    record_task_recovered,
    record_task_cleanup,
    track_task_queue_operation,
    # Governance
    GOVERNANCE_DECISIONS_TOTAL,
    GOVERNANCE_VERIFICATIONS_TOTAL,
    GOVERNANCE_APPROVALS_TOTAL,
    GOVERNANCE_STORE_LATENCY,
    GOVERNANCE_ARTIFACTS_ACTIVE,
    record_governance_decision,
    record_governance_verification,
    record_governance_approval,
    set_governance_artifacts_active,
    track_governance_operation,
    # User mapping
    USER_MAPPING_OPERATIONS_TOTAL,
    USER_MAPPING_CACHE_HITS_TOTAL,
    USER_MAPPING_CACHE_MISSES_TOTAL,
    USER_MAPPINGS_ACTIVE,
    record_user_mapping_operation,
    record_user_mapping_cache_hit,
    record_user_mapping_cache_miss,
    set_user_mappings_active,
    # Checkpoint
    CHECKPOINT_OPERATIONS,
    CHECKPOINT_OPERATION_LATENCY,
    CHECKPOINT_SIZE,
    CHECKPOINT_RESTORE_RESULTS,
    record_checkpoint_operation,
    record_checkpoint_restore,
    track_checkpoint_operation,
    # Init
    init_store_metrics,
)

# Gauntlet metrics
from aragora.observability.metrics.gauntlet import (
    GAUNTLET_EXPORTS_TOTAL,
    GAUNTLET_EXPORT_LATENCY,
    GAUNTLET_EXPORT_SIZE,
    WORKFLOW_TEMPLATES_CREATED,
    WORKFLOW_TEMPLATE_EXECUTIONS,
    WORKFLOW_TEMPLATE_EXECUTION_LATENCY,
    CONSENSUS_INGESTION_TOTAL,
    CONSENSUS_INGESTION_LATENCY,
    CONSENSUS_INGESTION_CLAIMS,
    CONSENSUS_DISSENT_INGESTED,
    CONSENSUS_EVOLUTION_TRACKED,
    CONSENSUS_EVIDENCE_LINKED,
    CONSENSUS_AGREEMENT_RATIO,
    record_gauntlet_export,
    track_gauntlet_export,
    record_workflow_template_created,
    record_workflow_template_execution,
    track_workflow_template_execution,
    record_consensus_ingestion,
    record_consensus_dissent,
    record_consensus_evolution,
    record_consensus_evidence_linked,
    record_consensus_agreement_ratio,
    init_gauntlet_metrics,
)

# KM metrics (re-exported from km module for explicit imports)
from aragora.observability.metrics.km import (
    init_km_metrics,
    set_km_health_status,
    set_km_active_adapters,
)


# =============================================================================
# Backward Compatibility Shims
# =============================================================================


def _init_metrics() -> bool:
    """Initialize all metrics (backward compatibility shim).

    Returns:
        True if metrics are enabled, False otherwise.
    """
    if not get_metrics_enabled():
        _init_noop_metrics()
        return False

    init_core_metrics()
    init_bridge_metrics()
    init_km_metrics()
    init_notification_metrics()
    init_store_metrics()
    init_gauntlet_metrics()
    return True


def _init_noop_metrics() -> None:
    """Initialize NoOp metrics when prometheus is disabled (backward compatibility shim)."""
    from aragora.observability.metrics.bridge import _init_noop_metrics as _init_bridge_noop
    from aragora.observability.metrics.km import _init_noop_metrics as _init_km_noop
    from aragora.observability.metrics.notification import _init_noop_metrics as _init_notification_noop
    from aragora.observability.metrics.stores import _init_noop_metrics as _init_store_noop
    from aragora.observability.metrics.gauntlet import _init_noop_metrics as _init_gauntlet_noop
    from aragora.observability.metrics.core import _init_noop_metrics as _init_core_noop

    _init_core_noop()
    _init_bridge_noop()
    _init_km_noop()
    _init_notification_noop()
    _init_store_noop()
    _init_gauntlet_noop()


__all__ = [
    # Base
    "NoOpMetric",
    "get_metrics_enabled",
    "ensure_metrics_initialized",
    "normalize_endpoint",
    # Core metrics
    "REQUEST_COUNT",
    "REQUEST_LATENCY",
    "AGENT_CALLS",
    "AGENT_LATENCY",
    "ACTIVE_DEBATES",
    "CONSENSUS_RATE",
    "MEMORY_OPERATIONS",
    "WEBSOCKET_CONNECTIONS",
    "DEBATE_DURATION",
    "DEBATE_ROUNDS",
    "DEBATE_PHASE_DURATION",
    "AGENT_PARTICIPATION",
    "CACHE_HITS",
    "CACHE_MISSES",
    "KNOWLEDGE_CACHE_HITS",
    "KNOWLEDGE_CACHE_MISSES",
    "MEMORY_COORDINATOR_WRITES",
    "SELECTION_FEEDBACK_ADJUSTMENTS",
    "WORKFLOW_TRIGGERS",
    "EVIDENCE_STORED",
    "CULTURE_PATTERNS",
    "RLM_CACHE_HITS",
    "RLM_CACHE_MISSES",
    "CALIBRATION_ADJUSTMENTS",
    "LEARNING_BONUSES",
    "VOTING_ACCURACY_UPDATES",
    "ADAPTIVE_ROUND_CHANGES",
    "SLOW_DEBATES_TOTAL",
    "SLOW_ROUNDS_TOTAL",
    "DEBATE_ROUND_LATENCY",
    "TTS_SYNTHESIS_TOTAL",
    "TTS_SYNTHESIS_LATENCY",
    "CONVERGENCE_DETECTIONS",
    "VOTE_BONUS_ADJUSTMENTS",
    "PROXY_FALLBACK_COUNT",
    "RATE_LIMIT_EVENTS",
    "MEMORY_TIER_TRANSITIONS",
    "INSIGHT_LEARNING_EVENTS",
    "TEAM_COMPOSITION_METRICS",
    "DYNAMIC_WEIGHTS_APPLIED",
    "BENCHMARK_CYCLES_TOTAL",
    "BENCHMARK_CYCLE_LATENCY",
    "UNCERTAINTY_ESTIMATES",
    "ADAPTIVE_ROUNDS_TRIGGERED",
    "PARTICIPANT_VOTES_TOTAL",
    "PARTICIPANT_SUGGESTIONS_TOTAL",
    "PARTICIPANT_FEEDBACK_LATENCY",
    "CIRCUIT_BREAKER_TRIPS",
    "CIRCUIT_BREAKER_STATE",
    "OBSERVABILITY_HEALTH",
    "METRICS_COLLECTION_ERRORS",
    # Core recording functions
    "record_request",
    "record_agent_call",
    "record_agent_latency",
    "record_debate_started",
    "record_debate_completed",
    "record_memory_operation",
    "record_ws_connection",
    "record_ws_disconnection",
    "record_debate_phase_duration",
    "record_agent_participation",
    "record_cache_hit",
    "record_cache_miss",
    "record_slow_debate",
    "record_slow_round",
    "record_debate_round_latency",
    "record_tts_synthesis",
    "record_convergence_detection",
    "record_vote_bonus_adjustment",
    "record_knowledge_cache_hit",
    "record_knowledge_cache_miss",
    "record_memory_coordinator_write",
    "record_selection_feedback_adjustment",
    "record_workflow_trigger",
    "record_evidence_stored",
    "record_culture_pattern",
    "record_rlm_cache_access",
    "record_calibration_adjustment",
    "record_learning_bonus",
    "record_voting_accuracy_update",
    "record_adaptive_round_change",
    "record_proxy_fallback",
    "record_rate_limit_event",
    "record_memory_tier_transition",
    "record_insight_learning_event",
    "record_team_composition",
    "record_dynamic_weights",
    "record_benchmark_cycle",
    "record_uncertainty_estimate",
    "record_adaptive_rounds_triggered",
    "record_participant_vote",
    "record_participant_suggestion",
    "record_participant_feedback_latency",
    "record_circuit_breaker_trip",
    "set_circuit_breaker_state",
    "record_observability_health",
    "record_metrics_collection_error",
    # Core context managers
    "track_request",
    "track_agent_call",
    "track_debate",
    # Core decorators
    "track_latency",
    # Core init
    "init_core_metrics",
    "start_metrics_server",
    "shutdown_metrics_server",
    # Bridge metrics
    "BRIDGE_SYNCS",
    "BRIDGE_SYNC_LATENCY",
    "BRIDGE_ERRORS",
    "PERFORMANCE_ROUTING_DECISIONS",
    "PERFORMANCE_ROUTING_LATENCY",
    "OUTCOME_COMPLEXITY_ADJUSTMENTS",
    "ANALYTICS_SELECTION_RECOMMENDATIONS",
    "NOVELTY_SCORE_CALCULATIONS",
    "NOVELTY_PENALTIES",
    "ECHO_CHAMBER_DETECTIONS",
    "RELATIONSHIP_BIAS_ADJUSTMENTS",
    "RLM_SELECTION_RECOMMENDATIONS",
    "CALIBRATION_COST_CALCULATIONS",
    "BUDGET_FILTERING_EVENTS",
    "record_bridge_sync",
    "record_bridge_sync_latency",
    "record_bridge_error",
    "record_performance_routing_decision",
    "record_performance_routing_latency",
    "record_outcome_complexity_adjustment",
    "record_analytics_selection_recommendation",
    "record_novelty_score_calculation",
    "record_novelty_penalty",
    "record_echo_chamber_detection",
    "record_relationship_bias_adjustment",
    "record_rlm_selection_recommendation",
    "record_calibration_cost_calculation",
    "record_budget_filtering_event",
    "track_bridge_sync",
    "init_bridge_metrics",
    # KM metrics
    "KM_OPERATIONS_TOTAL",
    "KM_OPERATION_LATENCY",
    "KM_CACHE_HITS_TOTAL",
    "KM_CACHE_MISSES_TOTAL",
    "KM_HEALTH_STATUS",
    "KM_ADAPTER_SYNCS_TOTAL",
    "KM_FEDERATED_QUERIES_TOTAL",
    "KM_EVENTS_EMITTED_TOTAL",
    "KM_ACTIVE_ADAPTERS",
    "record_km_operation",
    "record_km_cache_access",
    "record_km_adapter_sync",
    "record_km_federated_query",
    "record_km_event_emitted",
    "sync_km_metrics_to_prometheus",
    "record_km_inbound_event",
    "record_km_circuit_breaker_trip",
    "record_km_retry",
    "record_km_cache_invalidation",
    "record_km_integrity_error",
    "record_km_integrity_repair",
    "init_km_metrics",
    "set_km_health_status",
    "set_km_active_adapters",
    # Notification metrics
    "NOTIFICATION_SENT_TOTAL",
    "NOTIFICATION_LATENCY",
    "NOTIFICATION_ERRORS_TOTAL",
    "NOTIFICATION_QUEUE_SIZE",
    "record_notification_sent",
    "record_notification_error",
    "set_notification_queue_size",
    "track_notification_delivery",
    "init_notification_metrics",
    # Store metrics
    "TASK_QUEUE_OPERATIONS_TOTAL",
    "TASK_QUEUE_OPERATION_LATENCY",
    "TASK_QUEUE_SIZE",
    "TASK_QUEUE_RECOVERED_TOTAL",
    "TASK_QUEUE_CLEANUP_TOTAL",
    "record_task_queue_operation",
    "set_task_queue_size",
    "record_task_recovered",
    "record_task_cleanup",
    "track_task_queue_operation",
    "GOVERNANCE_DECISIONS_TOTAL",
    "GOVERNANCE_VERIFICATIONS_TOTAL",
    "GOVERNANCE_APPROVALS_TOTAL",
    "GOVERNANCE_STORE_LATENCY",
    "GOVERNANCE_ARTIFACTS_ACTIVE",
    "record_governance_decision",
    "record_governance_verification",
    "record_governance_approval",
    "set_governance_artifacts_active",
    "track_governance_operation",
    "USER_MAPPING_OPERATIONS_TOTAL",
    "USER_MAPPING_CACHE_HITS_TOTAL",
    "USER_MAPPING_CACHE_MISSES_TOTAL",
    "USER_MAPPINGS_ACTIVE",
    "record_user_mapping_operation",
    "record_user_mapping_cache_hit",
    "record_user_mapping_cache_miss",
    "set_user_mappings_active",
    "CHECKPOINT_OPERATIONS",
    "CHECKPOINT_OPERATION_LATENCY",
    "CHECKPOINT_SIZE",
    "CHECKPOINT_RESTORE_RESULTS",
    "record_checkpoint_operation",
    "record_checkpoint_restore",
    "track_checkpoint_operation",
    "init_store_metrics",
    # Gauntlet metrics
    "GAUNTLET_EXPORTS_TOTAL",
    "GAUNTLET_EXPORT_LATENCY",
    "GAUNTLET_EXPORT_SIZE",
    "WORKFLOW_TEMPLATES_CREATED",
    "WORKFLOW_TEMPLATE_EXECUTIONS",
    "WORKFLOW_TEMPLATE_EXECUTION_LATENCY",
    "CONSENSUS_INGESTION_TOTAL",
    "CONSENSUS_INGESTION_LATENCY",
    "CONSENSUS_INGESTION_CLAIMS",
    "CONSENSUS_DISSENT_INGESTED",
    "CONSENSUS_EVOLUTION_TRACKED",
    "CONSENSUS_EVIDENCE_LINKED",
    "CONSENSUS_AGREEMENT_RATIO",
    "record_gauntlet_export",
    "track_gauntlet_export",
    "record_workflow_template_created",
    "record_workflow_template_execution",
    "track_workflow_template_execution",
    "record_consensus_ingestion",
    "record_consensus_dissent",
    "record_consensus_evolution",
    "record_consensus_evidence_linked",
    "record_consensus_agreement_ratio",
    "init_gauntlet_metrics",
]
