"""Lazy import mappings for handler modules.

This module provides a mapping of handler names to their module paths,
enabling lazy loading of handlers to reduce import time.
"""

from __future__ import annotations

# Mapping of handler class names to their module paths
# This enables lazy loading - handlers are only imported when accessed
HANDLER_MODULES: dict[str, str] = {
    # admin/ directory
    "AdminHandler": "aragora.server.handlers.admin",
    "SecurityHandler": "aragora.server.handlers.admin",
    "BillingHandler": "aragora.server.handlers.admin",
    "DashboardHandler": "aragora.server.handlers.admin",
    "HealthHandler": "aragora.server.handlers.admin",
    "SystemHandler": "aragora.server.handlers.admin",
    # agents/ directory
    "AgentConfigHandler": "aragora.server.handlers.agents",
    "AgentsHandler": "aragora.server.handlers.agents",
    "CalibrationHandler": "aragora.server.handlers.agents",
    "LeaderboardViewHandler": "aragora.server.handlers.agents",
    "ProbesHandler": "aragora.server.handlers.agents",
    # analytics
    "AnalyticsHandler": "aragora.server.handlers._analytics_impl",
    "AnalyticsDashboardHandler": "aragora.server.handlers.analytics_dashboard",
    "EndpointAnalyticsHandler": "aragora.server.handlers.endpoint_analytics",
    "AnalyticsMetricsHandler": "aragora.server.handlers._analytics_metrics_impl",
    "AnalyticsPerformanceHandler": "aragora.server.handlers.analytics_performance",
    # autonomous/ directory
    "ApprovalHandler": "aragora.server.handlers.autonomous",
    "AlertHandler": "aragora.server.handlers.autonomous",
    "TriggerHandler": "aragora.server.handlers.autonomous",
    "MonitoringHandler": "aragora.server.handlers.autonomous",
    "AudienceSuggestionsHandler": "aragora.server.handlers.audience_suggestions",
    "AutonomousLearningHandler": "aragora.server.handlers.autonomous_learning",
    # approvals inbox
    "UnifiedApprovalsHandler": "aragora.server.handlers.approvals_inbox",
    # bots/ directory
    "DiscordHandler": "aragora.server.handlers.bots",
    "GoogleChatHandler": "aragora.server.handlers.bots",
    "TeamsHandler": "aragora.server.handlers.bots",
    "TelegramHandler": "aragora.server.handlers.bots",
    "WhatsAppHandler": "aragora.server.handlers.bots",
    "ZoomHandler": "aragora.server.handlers.bots",
    # codebase/ directory
    "IntelligenceHandler": "aragora.server.handlers.codebase",
    # debates/ directory
    "DebatesHandler": "aragora.server.handlers.debates",
    "GraphDebatesHandler": "aragora.server.handlers.debates",
    "MatrixDebatesHandler": "aragora.server.handlers.debates",
    # decisions/ directory
    "DecisionExplainHandler": "aragora.server.handlers.decisions",
    "DecisionPipelineHandler": "aragora.server.handlers.decisions",
    # canvas pipeline
    "CanvasPipelineHandler": "aragora.server.handlers.canvas_pipeline",
    # evolution/ directory
    "EvolutionABTestingHandler": "aragora.server.handlers.evolution",
    "EvolutionHandler": "aragora.server.handlers.evolution",
    # features/ directory - many handlers
    "AuditSessionsHandler": "aragora.server.handlers.features",
    "AudioHandler": "aragora.server.handlers.features",
    "BroadcastHandler": "aragora.server.handlers.features",
    "CloudStorageHandler": "aragora.server.handlers.features",
    "CodebaseAuditHandler": "aragora.server.handlers.features",
    "ConnectorsHandler": "aragora.server.handlers.features",
    "CrossPlatformAnalyticsHandler": "aragora.server.handlers.features",
    "DevOpsHandler": "aragora.server.handlers.features",
    "DocumentHandler": "aragora.server.handlers.features",
    "DocumentBatchHandler": "aragora.server.handlers.features",
    "DocumentQueryHandler": "aragora.server.handlers.features",
    "EmailWebhooksHandler": "aragora.server.handlers.features",
    "EvidenceHandler": "aragora.server.handlers.features",
    "EvidenceEnrichmentHandler": "aragora.server.handlers.features",
    "FeaturesHandler": "aragora.server.handlers.features",
    "FindingWorkflowHandler": "aragora.server.handlers.features",
    "FolderUploadHandler": "aragora.server.handlers.features",
    "GmailIngestHandler": "aragora.server.handlers.features",
    "GmailQueryHandler": "aragora.server.handlers.features",
    "IntegrationsHandler": "aragora.server.handlers.features",
    "LegalHandler": "aragora.server.handlers.features",
    "MarketplaceHandler": "aragora.server.handlers.features",
    "PluginsHandler": "aragora.server.handlers.features",
    "PulseHandler": "aragora.server.handlers.features",
    "ReconciliationHandler": "aragora.server.handlers.features",
    "RLMHandler": "aragora.server.handlers.features",
    "RoutingRulesHandler": "aragora.server.handlers.features",
    "SchedulerHandler": "aragora.server.handlers.features",
    "SmartUploadHandler": "aragora.server.handlers.features",
    "UnifiedInboxHandler": "aragora.server.handlers.features",
    "SharedInboxHandler": "aragora.server.handlers.shared_inbox",
    # features/gmail_* modules
    "GmailLabelsHandler": "aragora.server.handlers.features.gmail_labels",
    "GmailThreadsHandler": "aragora.server.handlers.features.gmail_threads",
    # billing/ directory
    "CostDashboardHandler": "aragora.server.handlers.billing",
    # costs/ directory
    "CostHandler": "aragora.server.handlers.costs",
    # Connector platform handlers (from features/)
    "AdvertisingHandler": "aragora.server.handlers.features",
    "AnalyticsPlatformsHandler": "aragora.server.handlers.features",
    "CRMHandler": "aragora.server.handlers.features",
    "SupportHandler": "aragora.server.handlers.features",
    "EcommerceHandler": "aragora.server.handlers.features",
    # knowledge/ directory
    "KMCheckpointHandler": "aragora.server.handlers.knowledge.checkpoints",
    # knowledge_base/ directory
    "KnowledgeHandler": "aragora.server.handlers.knowledge_base",
    "KnowledgeMoundHandler": "aragora.server.handlers.knowledge_base",
    # memory/ directory
    "InsightsHandler": "aragora.server.handlers.memory",
    "LearningHandler": "aragora.server.handlers.memory",
    "MemoryHandler": "aragora.server.handlers.memory",
    "MemoryAnalyticsHandler": "aragora.server.handlers.memory",
    "CoordinatorHandler": "aragora.server.handlers.memory",
    # nomic/ directory
    "NomicHandler": "aragora.server.handlers.nomic",
    # public/ directory
    "StatusPageHandler": "aragora.server.handlers.public",
    # social/ directory
    "RelationshipHandler": "aragora.server.handlers.social",
    "SlackHandler": "aragora.server.handlers.social",
    "SocialMediaHandler": "aragora.server.handlers.social",
    "CollaborationHandlers": "aragora.server.handlers.social",
    "get_collaboration_handlers": "aragora.server.handlers.social",
    # social/teams
    "TeamsIntegrationHandler": "aragora.server.handlers.social.teams",
    # verification/ directory
    "FormalVerificationHandler": "aragora.server.handlers.verification",
    "VerificationHandler": "aragora.server.handlers.verification",
    # Top-level handler modules (single file)
    "A2AHandler": "aragora.server.handlers.a2a",
    "AuditingHandler": "aragora.server.handlers.auditing",
    "SecurityDebateHandler": "aragora.server.handlers.security_debate",
    "AuthHandler": "aragora.server.handlers.auth",
    "BackupHandler": "aragora.server.handlers.backup_handler",
    "BeliefHandler": "aragora.server.handlers.belief",
    "BindingsHandler": "aragora.server.handlers.bindings",
    "BreakpointsHandler": "aragora.server.handlers.breakpoints",
    "BudgetHandler": "aragora.server.handlers.budgets",
    "CanvasHandler": "aragora.server.handlers.canvas",
    "CheckpointHandler": "aragora.server.handlers.checkpoints",
    "CodeReviewHandler": "aragora.server.handlers.code_review",
    "ComplianceHandler": "aragora.server.handlers.compliance_handler",
    "CompositeHandler": "aragora.server.handlers.composite",
    "ComputerUseHandler": "aragora.server.handlers.computer_use_handler",
    "ConsensusHandler": "aragora.server.handlers.consensus",
    "ControlPlaneHandler": "aragora.server.handlers.control_plane",
    "CritiqueHandler": "aragora.server.handlers.critique",
    "DecisionHandler": "aragora.server.handlers.decision",
    "DeliberationsHandler": "aragora.server.handlers.deliberations",
    "DependencyAnalysisHandler": "aragora.server.handlers.dependency_analysis",
    "DeviceHandler": "aragora.server.handlers.devices",
    "DocsHandler": "aragora.server.handlers.docs",
    "EmailHandler": "aragora.server.handlers.email",
    "EmailServicesHandler": "aragora.server.handlers.email_services",
    "ERC8004Handler": "aragora.server.handlers.erc8004",
    "EvaluationHandler": "aragora.server.handlers.evaluation",
    "ExplainabilityHandler": "aragora.server.handlers.explainability",
    "ExpenseHandler": "aragora.server.handlers.expenses",
    "ExternalAgentsHandler": "aragora.server.handlers.external_agents",
    "ExternalIntegrationsHandler": "aragora.server.handlers.external_integrations",
    "GalleryHandler": "aragora.server.handlers.gallery",
    "GatewayAgentsHandler": "aragora.server.handlers.gateway_agents_handler",
    "GatewayCredentialsHandler": "aragora.server.handlers.gateway_credentials_handler",
    "GatewayHandler": "aragora.server.handlers.gateway_handler",
    "GatewayHealthHandler": "aragora.server.handlers.gateway_health_handler",
    "GauntletHandler": "aragora.server.handlers.gauntlet",
    "GenesisHandler": "aragora.server.handlers.genesis",
    "HybridDebateHandler": "aragora.server.handlers.hybrid_debate_handler",
    "IntegrationManagementHandler": "aragora.server.handlers.integration_management",
    "IntrospectionHandler": "aragora.server.handlers.introspection",
    "InvoiceHandler": "aragora.server.handlers.invoices",
    "KnowledgeChatHandler": "aragora.server.handlers.knowledge_chat",
    "LaboratoryHandler": "aragora.server.handlers.laboratory",
    "MetricsHandler": "aragora.server.handlers.metrics",
    "MLHandler": "aragora.server.handlers.ml",
    "MomentsHandler": "aragora.server.handlers.moments",
    "OAuthHandler": "aragora.server.handlers.oauth",
    "OAuthWizardHandler": "aragora.server.handlers.oauth_wizard",
    "OpenClawGatewayHandler": "aragora.server.handlers.openclaw_gateway",
    "OrchestrationHandler": "aragora.server.handlers.orchestration",
    "OrganizationsHandler": "aragora.server.handlers.organizations",
    "PersonaHandler": "aragora.server.handlers.persona",
    "PolicyHandler": "aragora.server.handlers.policy",
    "PrivacyHandler": "aragora.server.handlers.privacy",
    "QueueHandler": "aragora.server.handlers.queue",
    "ReplaysHandler": "aragora.server.handlers.replays",
    "RepositoryHandler": "aragora.server.handlers.repository",
    "ReviewsHandler": "aragora.server.handlers.reviews",
    "RLMContextHandler": "aragora.server.handlers.rlm",
    "RoutingHandler": "aragora.server.handlers.routing",
    "SCIMHandler": "aragora.server.handlers.scim_handler",
    "SelectionHandler": "aragora.server.handlers.selection",
    "SkillsHandler": "aragora.server.handlers.skills",
    "SLOHandler": "aragora.server.handlers.slo",
    "SMEUsageDashboardHandler": "aragora.server.handlers.sme_usage_dashboard",
    "TemplateMarketplaceHandler": "aragora.server.handlers.template_marketplace",
    "TournamentHandler": "aragora.server.handlers.tournaments",
    "TrainingHandler": "aragora.server.handlers.training",
    "TranscriptionHandler": "aragora.server.handlers.transcription",
    "UncertaintyHandler": "aragora.server.handlers.uncertainty",
    "UsageMeteringHandler": "aragora.server.handlers.usage_metering",
    "VerticalsHandler": "aragora.server.handlers.verticals",
    "VoiceHandler": "aragora.server.handlers.voice.handler",
    "WebhookHandler": "aragora.server.handlers.webhooks",
    "WorkflowHandler": "aragora.server.handlers.workflows",
    "WorkspaceHandler": "aragora.server.handlers.workspace",
    # Workflow templates handlers
    "WorkflowTemplatesHandler": "aragora.server.handlers.workflow_templates",
    "WorkflowCategoriesHandler": "aragora.server.handlers.workflow_templates",
    "WorkflowPatternsHandler": "aragora.server.handlers.workflow_templates",
    "WorkflowPatternTemplatesHandler": "aragora.server.handlers.workflow_templates",
    "TemplateRecommendationsHandler": "aragora.server.handlers.workflow_templates",
    # Gauntlet v1 handlers
    "GauntletSchemaHandler": "aragora.server.handlers.gauntlet_v1",
    "GauntletAllSchemasHandler": "aragora.server.handlers.gauntlet_v1",
    "GauntletTemplatesListHandler": "aragora.server.handlers.gauntlet_v1",
    "GauntletTemplateHandler": "aragora.server.handlers.gauntlet_v1",
    "GauntletReceiptExportHandler": "aragora.server.handlers.gauntlet_v1",
    "GauntletHeatmapExportHandler": "aragora.server.handlers.gauntlet_v1",
    "GauntletValidateReceiptHandler": "aragora.server.handlers.gauntlet_v1",
    "GAUNTLET_V1_HANDLERS": "aragora.server.handlers.gauntlet_v1",
    # Cross-pollination handlers
    "CrossPollinationStatsHandler": "aragora.server.handlers.cross_pollination",
    "CrossPollinationSubscribersHandler": "aragora.server.handlers.cross_pollination",
    "CrossPollinationBridgeHandler": "aragora.server.handlers.cross_pollination",
    "CrossPollinationMetricsHandler": "aragora.server.handlers.cross_pollination",
    "CrossPollinationResetHandler": "aragora.server.handlers.cross_pollination",
    "CrossPollinationKMHandler": "aragora.server.handlers.cross_pollination",
    "CrossPollinationKMSyncHandler": "aragora.server.handlers.cross_pollination",
    "CrossPollinationKMStalenessHandler": "aragora.server.handlers.cross_pollination",
    "CrossPollinationKMCultureHandler": "aragora.server.handlers.cross_pollination",
    # Onboarding handlers
    "handle_get_flow": "aragora.server.handlers.onboarding",
    "handle_init_flow": "aragora.server.handlers.onboarding",
    "handle_update_step": "aragora.server.handlers.onboarding",
    "handle_get_templates": "aragora.server.handlers.onboarding",
    "handle_first_debate": "aragora.server.handlers.onboarding",
    "handle_quick_start": "aragora.server.handlers.onboarding",
    "handle_analytics": "aragora.server.handlers.onboarding",
    "get_onboarding_handlers": "aragora.server.handlers.onboarding",
    "OnboardingHandler": "aragora.server.handlers.onboarding",
    # Accounting handlers
    "ARAutomationHandler": "aragora.server.handlers.ar_automation",
    "APAutomationHandler": "aragora.server.handlers.ap_automation",
    # RBAC management
    "RBACHandler": "aragora.server.handlers.rbac",
    # Self-improvement
    "SelfImproveHandler": "aragora.server.handlers.self_improve",
    # Spectate (real-time debate observation)
    "SpectateStreamHandler": "aragora.server.handlers.spectate_ws",
}

# List of all handler class names (in priority order for dispatch)
# More specific handlers should come first
ALL_HANDLER_NAMES: list[str] = [
    "GraphDebatesHandler",
    "MatrixDebatesHandler",
    "CompositeHandler",
    "DebatesHandler",
    "AgentConfigHandler",
    "AgentsHandler",
    "HealthHandler",
    "StatusPageHandler",
    "NomicHandler",
    "DocsHandler",
    "SystemHandler",
    "PulseHandler",
    "AnalyticsHandler",
    "AnalyticsDashboardHandler",
    "AnalyticsMetricsHandler",
    "AnalyticsPerformanceHandler",
    "EndpointAnalyticsHandler",
    "CrossPlatformAnalyticsHandler",
    "MetricsHandler",
    "SLOHandler",
    "CrossPollinationStatsHandler",
    "CrossPollinationSubscribersHandler",
    "CrossPollinationBridgeHandler",
    "CrossPollinationMetricsHandler",
    "CrossPollinationResetHandler",
    "CrossPollinationKMHandler",
    "CrossPollinationKMSyncHandler",
    "CrossPollinationKMStalenessHandler",
    "CrossPollinationKMCultureHandler",
    "ConsensusHandler",
    "BeliefHandler",
    "SkillsHandler",
    "BindingsHandler",
    "DecisionExplainHandler",
    "DecisionHandler",
    "ControlPlaneHandler",
    "DeliberationsHandler",
    "CritiqueHandler",
    "GenesisHandler",
    "ReplaysHandler",
    "TournamentHandler",
    "MemoryHandler",
    "CoordinatorHandler",
    "LeaderboardViewHandler",
    "RelationshipHandler",
    "MomentsHandler",
    "DocumentQueryHandler",
    "DocumentHandler",
    "DocumentBatchHandler",
    "FolderUploadHandler",
    "SmartUploadHandler",
    "CloudStorageHandler",
    "FindingWorkflowHandler",
    "EvidenceEnrichmentHandler",
    "SchedulerHandler",
    "AuditSessionsHandler",
    "VerificationHandler",
    "AuditingHandler",
    "SecurityDebateHandler",
    "DashboardHandler",
    "PersonaHandler",
    "IntrospectionHandler",
    "CalibrationHandler",
    "CheckpointHandler",
    "RoutingHandler",
    "RoutingRulesHandler",
    "MLHandler",
    "RLMContextHandler",
    "RLMHandler",
    "SelectionHandler",
    "EvaluationHandler",
    "EvolutionABTestingHandler",
    "EvolutionHandler",
    "PluginsHandler",
    "AudioHandler",
    "DeviceHandler",
    "TranscriptionHandler",
    "SocialMediaHandler",
    "BroadcastHandler",
    "LaboratoryHandler",
    "ProbesHandler",
    "InsightsHandler",
    "KnowledgeHandler",
    "KnowledgeMoundHandler",
    "KnowledgeChatHandler",
    "KMCheckpointHandler",
    "GalleryHandler",
    "BreakpointsHandler",
    "LearningHandler",
    "AuthHandler",
    "BillingHandler",
    "BudgetHandler",
    "UsageMeteringHandler",
    "SMEUsageDashboardHandler",
    "OrganizationsHandler",
    "OAuthHandler",
    "FeaturesHandler",
    "ConnectorsHandler",
    "TeamsIntegrationHandler",
    "IntegrationsHandler",
    "ExternalIntegrationsHandler",
    "IntegrationManagementHandler",
    "OAuthWizardHandler",
    "GmailIngestHandler",
    "GmailQueryHandler",
    "UnifiedInboxHandler",
    "SharedInboxHandler",
    "EmailWebhooksHandler",
    "MemoryAnalyticsHandler",
    "GauntletSchemaHandler",
    "GauntletAllSchemasHandler",
    "GauntletTemplatesListHandler",
    "GauntletTemplateHandler",
    "GauntletReceiptExportHandler",
    "GauntletHeatmapExportHandler",
    "GauntletValidateReceiptHandler",
    "GauntletHandler",
    "ReviewsHandler",
    "FormalVerificationHandler",
    "SlackHandler",
    "EvidenceHandler",
    "WebhookHandler",
    "CodebaseAuditHandler",
    "AdminHandler",
    "SecurityHandler",
    "PolicyHandler",
    "PrivacyHandler",
    "QueueHandler",
    "RepositoryHandler",
    "UncertaintyHandler",
    "VerticalsHandler",
    "WorkspaceHandler",
    "WorkflowHandler",
    "WorkflowTemplatesHandler",
    "WorkflowCategoriesHandler",
    "WorkflowPatternsHandler",
    "WorkflowPatternTemplatesHandler",
    "TemplateRecommendationsHandler",
    "TemplateMarketplaceHandler",
    "MarketplaceHandler",
    "TrainingHandler",
    "EmailHandler",
    "EmailServicesHandler",
    "DependencyAnalysisHandler",
    "IntelligenceHandler",
    "DiscordHandler",
    "GoogleChatHandler",
    "TeamsHandler",
    "TelegramHandler",
    "WhatsAppHandler",
    "ZoomHandler",
    "ExplainabilityHandler",
    "SCIMHandler",
    "A2AHandler",
    "ApprovalHandler",
    "UnifiedApprovalsHandler",
    "AlertHandler",
    "TriggerHandler",
    "MonitoringHandler",
    "AutonomousLearningHandler",
    "CostDashboardHandler",
    "CostHandler",
    "ExpenseHandler",
    "InvoiceHandler",
    "ARAutomationHandler",
    "APAutomationHandler",
    "ReconciliationHandler",
    "CodeReviewHandler",
    "LegalHandler",
    "DevOpsHandler",
    "AdvertisingHandler",
    "AnalyticsPlatformsHandler",
    "CRMHandler",
    "SupportHandler",
    "EcommerceHandler",
    "ComputerUseHandler",
    "GatewayHandler",
    "OpenClawGatewayHandler",
    "ExternalAgentsHandler",
    "GatewayHealthHandler",
    "GatewayAgentsHandler",
    "GatewayCredentialsHandler",
    "HybridDebateHandler",
    "ERC8004Handler",
    "OnboardingHandler",
    "BackupHandler",
    "GmailLabelsHandler",
    "GmailThreadsHandler",
    "RBACHandler",
    "SelfImproveHandler",
    "SpectateStreamHandler",
    "VoiceHandler",
    "AudienceSuggestionsHandler",
    "CanvasPipelineHandler",
]
