#!/usr/bin/env python3
"""Render the advisory Aragora PR-review comment from review.json."""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any


GITHUB_COMMENT_CHAR_LIMIT = 65_000
TRUNCATION_MARKER = "[truncated - full advisory review is available in the workflow artifacts]"


@dataclass(frozen=True)
class CommentFinding:
    severity: str
    title: str
    body: str
    location: str = ""


def _string(value: Any) -> str:
    return str(value or "").strip()


def _location(item: dict[str, Any]) -> str:
    file_path = _string(item.get("file") or item.get("path"))
    if not file_path:
        return ""
    start = item.get("start_line") or item.get("line") or item.get("start")
    end = item.get("end_line") or item.get("end")
    location = file_path
    if start:
        location += f":{start}"
        if end and end != start:
            location += f"-{end}"
    return location


def _normalize_finding(severity: str, item: Any) -> CommentFinding | None:
    if isinstance(item, dict):
        title = _string(item.get("title") or item.get("summary"))
        body = _string(item.get("body") or item.get("description") or item.get("details"))
        if not title or not body:
            return None
        return CommentFinding(
            severity=severity,
            title=title,
            body=body,
            location=_location(item),
        )

    body = _string(item)
    if not body:
        return None
    title = body.splitlines()[0][:120].strip() or "Finding"
    return CommentFinding(severity=severity, title=title, body=body)


def _findings_from_review(data: dict[str, Any]) -> list[CommentFinding]:
    findings: list[CommentFinding] = []
    for severity in ("critical", "high", "medium", "low"):
        raw_items = data.get(f"{severity}_issues", [])
        if not isinstance(raw_items, list):
            continue
        for item in raw_items:
            finding = _normalize_finding(severity, item)
            if finding is not None:
                findings.append(finding)
    return findings


def _render_finding(finding: CommentFinding) -> str:
    parts = [f"**{finding.title}**"]
    if finding.location:
        parts.append(f"`{finding.location}`")
    parts.append(finding.body)
    return "\n\n".join(parts)


def _truncate_summary(summary: str, *, budget: int) -> str:
    if len(summary) <= budget:
        return summary
    marker = f"\n\n{TRUNCATION_MARKER}"
    available = max(0, budget - len(marker))
    truncated = summary[:available].rstrip()
    return f"{truncated}{marker}" if truncated else TRUNCATION_MARKER


def render_review_comment(
    data: dict[str, Any],
    *,
    max_chars: int = GITHUB_COMMENT_CHAR_LIMIT,
) -> str:
    findings = _findings_from_review(data)
    summary = _string(data.get("summary") or data.get("final_summary"))

    header_lines = [
        "## Aragora Code Review",
        "",
        "Advisory-only review. Findings are surfaced for follow-up and do not fail this workflow.",
        "",
    ]

    footer_lines: list[str] = []
    if findings:
        footer_lines.extend([f"**{len(findings)} finding(s)** across the diff", ""])
        severity_label = {
            "critical": "[CRITICAL]",
            "high": "[HIGH]",
            "medium": "[MEDIUM]",
            "low": "[LOW]",
            "info": "[INFO]",
        }
        for finding in findings:
            label = severity_label.get(finding.severity, "[?]")
            footer_lines.extend([f"### {label} Finding", _render_finding(finding), ""])
    elif not summary:
        footer_lines.extend(["No issues found.", ""])
    else:
        footer_lines.extend(["No structured findings were emitted.", ""])

    footer_lines.extend(
        [
            "---",
            "*Generated by [Aragora](https://aragora.ai) multi-agent code review*",
        ]
    )

    prefix = "\n".join(header_lines)
    suffix = "\n".join(footer_lines) + "\n"
    if summary:
        summary_budget = max_chars - len(prefix) - len(suffix) - 2
        summary = _truncate_summary(summary, budget=summary_budget)
        return f"{prefix}{summary}\n\n{suffix}"
    return f"{prefix}{suffix}"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("review_json", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--max-chars", type=int, default=GITHUB_COMMENT_CHAR_LIMIT)
    args = parser.parse_args()

    try:
        data = json.loads(args.review_json.read_text(encoding="utf-8"))
    except Exception:
        return 0
    if not isinstance(data, dict):
        return 0

    args.output.write_text(
        render_review_comment(data, max_chars=args.max_chars),
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
