"""Governance tests for the advisory-review-workflow header recognition gap.

These tests are the Tier 4 pre-approval regression target for the change
designed in `docs/specs/ADVISORY_REVIEW_RECOGNIZABLE_HEADER.md`. They
exist for two reasons:

1. They *pin* the current state of the gap so the implementation PR has
   a machine-checkable regression floor. The current advisory workflow
   header (``## Aragora Code Review``) MUST resolve to
   ``unknown_model_reviewer``; this proves the silent-quorum-suppression
   bug is real today, and protects against a future regression that
   would reintroduce it.

2. They *demonstrate* that the proposed contract (per-family per-agent
   headers like ``## Claude independent semantic review on head <sha>``)
   already resolves correctly under the *unchanged* recognizer. This is
   the key reason the proposed fix is workflow-only, not recognizer-side.

Per `docs/REVIEW_AUTHORITY_PRINCIPLES.md::Family-additive change
governance`:

  > "Loosening any of these constraints in CI (e.g., counting an
  >  advisory family at Tier 3) requires the same preapproval
  >  discipline as the original addition. ... failing governance tests
  >  in tests/governance/ that pin the current state of the gate so the
  >  implementation has a regression target."

This file IS that pre-approval test surface. The implementation that
satisfies the proposed contract waits for operator preapproval and a
separate implementation PR.
"""

from __future__ import annotations

import pytest

from aragora.cli.commands.review_queue import _infer_model_reviewer_from_text

# ---------------------------------------------------------------------------
# Regression floor: the *current* advisory-review header MUST stay
# recognized as unknown. If a future change makes
# "## Aragora Code Review" parse as some specific family without going
# through the per-agent attribution contract, that is the
# silent-quorum-suppression bug reintroduced as a silent-quorum-
# fabrication bug — strictly worse.
# ---------------------------------------------------------------------------


_CURRENT_ADVISORY_NO_FINDINGS_BODY = (
    "## Aragora Code Review\n\nAdvisory-only review. No issues found.\n"
)

_CURRENT_ADVISORY_WITH_FINDINGS_BODY = (
    "## Aragora Code Review\n\n"
    "Advisory-only review. Findings are surfaced for follow-up and do not "
    "fail this workflow.\n\n"
    "Overall the diff is sound but consider tightening retry semantics.\n\n"
    "**3 finding(s)** across the diff\n\n"
    "### [HIGH] Finding\n"
    "**Tighten retry semantics**\n\n"
    "`aragora/agents/api_agents/openai.py:152`\n\n"
    "The retry block swallows 429s without surfacing the upstream "
    "rate-limit envelope.\n\n"
    "---\n"
    "*Generated by [Aragora](https://aragora.ai) multi-agent code review*\n"
)


@pytest.mark.parametrize(
    "body, label",
    [
        (_CURRENT_ADVISORY_NO_FINDINGS_BODY, "no_findings"),
        (_CURRENT_ADVISORY_WITH_FINDINGS_BODY, "with_findings"),
    ],
)
def test_current_advisory_header_is_unrecognized(body: str, label: str) -> None:
    """REGRESSION FLOOR: today's `## Aragora Code Review` heading is unknown.

    The advisory review workflow at the time this test was written posts
    one of two literal comment shapes (no-findings or with-findings),
    both headed `## Aragora Code Review`. The recognizer's seven-marker
    tuple (`claude/codex/tesla/harvey/factory/grok/gemini`) does NOT
    contain "aragora", so both bodies must resolve to
    `unknown_model_reviewer`.

    If this test ever fails — i.e., a future recognizer change starts
    inferring a family name from "Aragora Code Review" — that change has
    silently widened the quorum without per-agent attribution being
    plumbed through the workflow first. That is the
    silent-quorum-fabrication failure mode described in the design doc;
    fail loudly and require the implementation PR to be reviewed before
    the recognizer can loosen.
    """
    assert _infer_model_reviewer_from_text(body) == "unknown_model_reviewer", (
        f"advisory-workflow header shape {label!r} now appears to resolve to "
        "a recognized family. If the per-agent attribution contract in "
        "docs/specs/ADVISORY_REVIEW_RECOGNIZABLE_HEADER.md has landed, this "
        "test should be removed or inverted as part of THAT PR — not as a "
        "side-effect of a recognizer change."
    )


# ---------------------------------------------------------------------------
# Proposed-contract acceptance: the per-family per-agent headers
# specified in the design doc MUST resolve to the right family under the
# *unchanged* recognizer. This is the proof that the proposed fix is
# workflow-only and does NOT require a recognizer change.
# ---------------------------------------------------------------------------


_PROPOSED_HEAD_SHA = "5a692b5dd54f05f2befe0df7b497c56e3c6ead6f"


@pytest.mark.parametrize(
    "family_marker, expected_family",
    [
        # Western families already in the recognizer's seven-marker tuple.
        ("Claude", "claude"),
        ("Gemini", "gemini"),
        ("Grok", "grok"),
        ("Codex", "codex"),
        # Vendor markers in the existing recognizer; included for
        # completeness even though the advisory workflow does not
        # currently route to them.
        ("Tesla", "tesla"),
        ("Harvey", "harvey"),
        ("Factory", "factory"),
    ],
)
def test_proposed_per_agent_header_resolves(family_marker: str, expected_family: str) -> None:
    """The proposed `## <Family> independent semantic review on head <sha>`
    heading already resolves correctly under the *current* recognizer.

    This is the load-bearing proof for the design doc's claim that the
    implementation PR is workflow-only. If this test fails, the
    recognizer's seven-marker tuple has been narrowed (regression on
    `docs/specs/MODEL_QUORUM_FAMILY_EXPANSION.md`'s regression-floor
    tests in `tests/governance/test_model_quorum_recognizer_gaps.py`).
    """
    body = (
        f"## {family_marker} independent semantic review on head "
        f"{_PROPOSED_HEAD_SHA}\n\n"
        f"Advisory-only — does not bypass the merge-quorum check; counted "
        f"only when the merge-quorum evaluator resolves a recognized "
        f"family marker on the exact head SHA.\n\n"
        f"No issues found by {family_marker} at this head.\n"
    )
    assert _infer_model_reviewer_from_text(body) == expected_family


# ---------------------------------------------------------------------------
# Out-of-contract families: the design doc explicitly orders the
# recognizer expansion (PR #7450) AFTER the workflow-side per-agent
# attribution. Until #7450 lands, an `OpenAI` header is correctly
# emitted but correctly stays unknown — because the recognizer does not
# know "openai" yet. This test pins that ordering.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "family_marker, pending_pr",
    [
        ("OpenAI", "#7450"),
        ("Anthropic", "#7450"),  # accepted by normalizer but not recognizer
        ("Mistral", "#7450"),
        ("DeepSeek", "#7450"),
        ("Qwen", "#7450"),
        ("Kimi", "#7450"),
    ],
)
def test_pending_families_emit_but_do_not_count_until_recognizer_expands(
    family_marker: str, pending_pr: str
) -> None:
    """Per-agent comments for not-yet-recognized families post but don't count.

    The design's "ordering matters" claim is that the workflow can
    safely emit per-agent comments for families like OpenAI today —
    because those comments will simply resolve to
    `unknown_model_reviewer` until PR #7450 expands the recognizer.
    Visibility is preserved (the review still posts and is readable);
    quorum counting is correctly gated on the recognizer expansion that
    has its own preapproval discipline.

    Note: "Anthropic" includes the substring "anthropic" which the
    recognizer does NOT scan for (the recognizer scans for
    "claude/codex/tesla/harvey/factory/grok/gemini"; the broader
    `_normalize_model_reviewer_id` table that DOES accept "anthropic"
    runs at a different layer and is not invoked by
    `_infer_model_reviewer_from_text`). So an `## Anthropic …` heading
    correctly resolves to unknown today, despite Anthropic being a
    well-known family — exactly because the recognizer is intentionally
    narrow.
    """
    body = (
        f"## {family_marker} independent semantic review on head "
        f"{_PROPOSED_HEAD_SHA}\n\nNo findings.\n"
    )
    assert _infer_model_reviewer_from_text(body) == "unknown_model_reviewer", (
        f"Family {family_marker!r} now appears to count under the recognizer. "
        f"If PR {pending_pr} has landed, this test must be moved to the "
        "positive-recognition suite, not the workflow-attribution suite — "
        "the two changes have independent Tier 4 preapproval discipline."
    )


# ---------------------------------------------------------------------------
# Safety floors: the recognizer must NOT be loosened by this design.
# ---------------------------------------------------------------------------


def test_recognizer_only_scans_first_heading() -> None:
    """Subheadings cannot displace the first heading's resolution.

    The recognizer scans the FIRST line that starts with ``#``, uses its
    text as the sole candidate, and only falls back to the first 200
    characters of the body when *no* ``#`` heading exists in the body
    at all. Subheadings (``###``) are not re-scanned. This is a stronger
    guarantee than the design doc's risk-row 3 mitigation needs.

    Concretely: a comment whose first heading is the unrecognized
    advisory header ``## Aragora Code Review`` resolves to
    ``unknown_model_reviewer`` regardless of how many ``### Claude
    findings`` subheadings appear in the body. This protects against an
    implementation that tries to claim family attribution via
    subheadings instead of per-comment first headings — the design
    requires per-COMMENT first-heading attribution, and the recognizer
    enforces that requirement.
    """
    body_with_subheading_only = (
        "## Aragora Code Review\n\n"
        "Multi-model review aggregated below.\n\n"
        "### Claude findings\n"
        "Looks fine.\n\n"
        "### Gemini findings\n"
        "Looks fine.\n"
    )
    assert _infer_model_reviewer_from_text(body_with_subheading_only) == "unknown_model_reviewer", (
        "Subheading-based attribution must NOT be picked up. The "
        "recognizer only scans the first markdown heading line; if a "
        "future recognizer change starts walking subheadings, the "
        "design doc's per-comment attribution contract is violated and "
        "any 'aggregated comment with per-family subheadings' "
        "implementation would silently bypass the per-COMMENT structure "
        "the design relies on."
    )


def test_arbitrary_prose_stays_unknown() -> None:
    """Bodies without any recognizable marker stay unknown."""
    inputs = [
        "Looking at this PR, my analysis says it should land.",
        "Some unidentified reviewer agent looked at this on head abc1234.",
        "",
        "## Some Unknown Reviewer\n\nLooks fine.\n",
    ]
    for body in inputs:
        assert _infer_model_reviewer_from_text(body) == "unknown_model_reviewer", (
            f"prose {body!r} should not produce a counted reviewer family"
        )


def test_diff_text_containing_family_name_in_body_does_not_resolve() -> None:
    """Diff text quoted in a comment body must not falsely attribute.

    Risk row 3 in the design doc claims diff text cannot displace the
    structured first heading. This test pins that claim: when the first
    heading is the structured advisory header, no amount of family-name
    text in the body (e.g., a quoted diff line containing 'claude')
    causes mis-attribution.
    """
    body = (
        "## Aragora Code Review\n\n"
        "Advisory-only review. No issues found.\n\n"
        "```diff\n"
        "+from aragora.agents.api_agents.anthropic import claude_client\n"
        "+claude_client.invoke(prompt='gemini-style chain of thought')\n"
        "```\n"
    )
    assert _infer_model_reviewer_from_text(body) == "unknown_model_reviewer", (
        "Diff-quoted family names inside a body whose first heading is "
        "the unrecognized advisory header MUST stay unknown. Otherwise "
        "the recognizer is reading review *input* (the diff) as review "
        "*output* (the model's attestation)."
    )
