"""
Customer Support Platform Connectors.

Integrations for customer support and helpdesk platforms:
- Zendesk (tickets, users, organizations)
- Freshdesk (tickets, contacts, companies)
- Intercom (conversations, contacts, companies)
- Help Scout (conversations, customers, mailboxes)
"""

from aragora.connectors.support.zendesk import (
    ZendeskConnector,
    ZendeskCredentials,
    ZendeskUser,
    Ticket,
    TicketComment,
    Organization,
    View,
    ZendeskError,
    TicketStatus,
    TicketPriority,
    TicketType,
    UserRole,
    get_mock_ticket,
    get_mock_user,
)
from aragora.connectors.support.freshdesk import (
    FreshdeskConnector,
    FreshdeskCredentials,
    FreshdeskTicket,
    Contact as FreshdeskContact,
    Company as FreshdeskCompany,
    Conversation as FreshdeskConversation,
    Agent as FreshdeskAgent,
    FreshdeskError,
    TicketStatus as FreshdeskTicketStatus,
    TicketPriority as FreshdeskTicketPriority,
    TicketSource,
    get_mock_ticket as get_mock_freshdesk_ticket,
    get_mock_contact as get_mock_freshdesk_contact,
)
from aragora.connectors.support.intercom import (
    IntercomConnector,
    IntercomCredentials,
    IntercomContact,
    IntercomCompany,
    Conversation as IntercomConversation,
    ConversationPart,
    Admin,
    Article,
    IntercomError,
    ConversationState,
    ContactRole,
    MessageType,
    get_mock_conversation as get_mock_intercom_conversation,
    get_mock_contact as get_mock_intercom_contact,
)
from aragora.connectors.support.helpscout import (
    HelpScoutConnector,
    HelpScoutCredentials,
    HelpScoutCustomer,
    Conversation as HelpScoutConversation,
    Thread,
    User as HelpScoutUser,
    Mailbox,
    Folder,
    HelpScoutError,
    ConversationStatus,
    ConversationType,
    ThreadType,
    ThreadStatus,
    get_mock_conversation as get_mock_helpscout_conversation,
    get_mock_customer as get_mock_helpscout_customer,
)

__all__ = [
    # Zendesk
    "ZendeskConnector",
    "ZendeskCredentials",
    "ZendeskUser",
    "Ticket",
    "TicketComment",
    "Organization",
    "View",
    "ZendeskError",
    "TicketStatus",
    "TicketPriority",
    "TicketType",
    "UserRole",
    "get_mock_ticket",
    "get_mock_user",
    # Freshdesk
    "FreshdeskConnector",
    "FreshdeskCredentials",
    "FreshdeskTicket",
    "FreshdeskContact",
    "FreshdeskCompany",
    "FreshdeskConversation",
    "FreshdeskAgent",
    "FreshdeskError",
    "FreshdeskTicketStatus",
    "FreshdeskTicketPriority",
    "TicketSource",
    "get_mock_freshdesk_ticket",
    "get_mock_freshdesk_contact",
    # Intercom
    "IntercomConnector",
    "IntercomCredentials",
    "IntercomContact",
    "IntercomCompany",
    "IntercomConversation",
    "ConversationPart",
    "Admin",
    "Article",
    "IntercomError",
    "ConversationState",
    "ContactRole",
    "MessageType",
    "get_mock_intercom_conversation",
    "get_mock_intercom_contact",
    # Help Scout
    "HelpScoutConnector",
    "HelpScoutCredentials",
    "HelpScoutCustomer",
    "HelpScoutConversation",
    "Thread",
    "HelpScoutUser",
    "Mailbox",
    "Folder",
    "HelpScoutError",
    "ConversationStatus",
    "ConversationType",
    "ThreadType",
    "ThreadStatus",
    "get_mock_helpscout_conversation",
    "get_mock_helpscout_customer",
]
