"""
Debate orchestration module.
"""

from __future__ import annotations

import importlib
from typing import Any

_EXPORT_MAP = {
    "AdaptiveComplexityGovernor": (
        "aragora.debate.complexity_governor",
        "AdaptiveComplexityGovernor",
    ),
    "AgentHealthState": ("aragora.debate.immune_system", "AgentHealthState"),
    "AgentPool": ("aragora.debate.agent_pool", "AgentPool"),
    "AgentState": ("aragora.debate.checkpoint", "AgentState"),
    "AgentStatus": ("aragora.debate.immune_system", "AgentStatus"),
    "Arena": ("aragora.debate.orchestrator", "Arena"),
    "ArenaBuilder": ("aragora.debate.arena_builder", "ArenaBuilder"),
    "ArenaConfig": ("aragora.debate.arena_config", "ArenaConfig"),
    "ArenaExtensions": ("aragora.debate.extensions", "ArenaExtensions"),
    "ArenaKnowledgeManager": ("aragora.debate.knowledge_manager", "ArenaKnowledgeManager"),
    "ExtensionsConfig": ("aragora.debate.extensions", "ExtensionsConfig"),
    "SubsystemCoordinator": ("aragora.debate.subsystem_coordinator", "SubsystemCoordinator"),
    "SubsystemConfig": ("aragora.debate.subsystem_coordinator", "SubsystemConfig"),
    "DebateHooks": ("aragora.debate.debate_hooks", "DebateHooks"),
    "HooksConfig": ("aragora.debate.debate_hooks", "HooksConfig"),
    "InitPhase": ("aragora.debate.arena_builder", "InitPhase"),
    "BlackboxEvent": ("aragora.debate.blackbox", "BlackboxEvent"),
    "BlackboxRecorder": ("aragora.debate.blackbox", "BlackboxRecorder"),
    "BlackboxSnapshot": ("aragora.debate.blackbox", "BlackboxSnapshot"),
    "Branch": ("aragora.debate.graph", "Branch"),
    "BranchComparison": ("aragora.debate.counterfactual", "BranchComparison"),
    "BranchPolicy": ("aragora.debate.graph", "BranchPolicy"),
    "BranchReason": ("aragora.debate.graph", "BranchReason"),
    "CalibrationBucket": ("aragora.debate.outcome_tracker", "CalibrationBucket"),
    "ChaosDirector": ("aragora.debate.chaos_theater", "ChaosDirector"),
    "CheckpointConfig": ("aragora.debate.checkpoint", "CheckpointConfig"),
    "CheckpointManager": ("aragora.debate.checkpoint", "CheckpointManager"),
    "CheckpointStatus": ("aragora.debate.checkpoint", "CheckpointStatus"),
    "CheckpointStore": ("aragora.debate.checkpoint", "CheckpointStore"),
    "CheckpointWebhook": ("aragora.debate.checkpoint", "CheckpointWebhook"),
    "ClaimAnalysis": ("aragora.debate.evidence_linker", "ClaimAnalysis"),
    "CognitiveBudget": ("aragora.debate.cognitive_limiter", "CognitiveBudget"),
    "CognitiveLoadLimiter": ("aragora.debate.cognitive_limiter", "CognitiveLoadLimiter"),
    "RLMCognitiveLoadLimiter": ("aragora.debate.cognitive_limiter_rlm", "RLMCognitiveLoadLimiter"),
    "create_rlm_limiter": ("aragora.debate.cognitive_limiter_rlm", "create_rlm_limiter"),
    "RLMCognitiveBudget": ("aragora.debate.cognitive_limiter_rlm", "RLMCognitiveBudget"),
    "CompressedContext": ("aragora.debate.cognitive_limiter_rlm", "CompressedContext"),
    "ConditionalConsensus": ("aragora.debate.counterfactual", "ConditionalConsensus"),
    "ConsensusOutcome": ("aragora.debate.outcome_tracker", "ConsensusOutcome"),
    "Contradiction": ("aragora.debate.cross_proposal_analyzer", "Contradiction"),
    "ConvergenceScorer": ("aragora.debate.graph", "ConvergenceScorer"),
    "CounterfactualBranch": ("aragora.debate.counterfactual", "CounterfactualBranch"),
    "CounterfactualIntegration": ("aragora.debate.counterfactual", "CounterfactualIntegration"),
    "CounterfactualOrchestrator": ("aragora.debate.counterfactual", "CounterfactualOrchestrator"),
    "CounterfactualStatus": ("aragora.debate.counterfactual", "CounterfactualStatus"),
    "CrossProposalAnalysis": ("aragora.debate.cross_proposal_analyzer", "CrossProposalAnalysis"),
    "CrossProposalAnalyzer": ("aragora.debate.cross_proposal_analyzer", "CrossProposalAnalyzer"),
    "DebateCheckpoint": ("aragora.debate.checkpoint", "DebateCheckpoint"),
    "DebateGraph": ("aragora.debate.graph", "DebateGraph"),
    "DebateNode": ("aragora.debate.graph", "DebateNode"),
    "DebateProtocol": ("aragora.debate.orchestrator", "DebateProtocol"),
    "DramaLevel": ("aragora.debate.chaos_theater", "DramaLevel"),
    "EvidenceClaimLinker": ("aragora.debate.evidence_linker", "EvidenceClaimLinker"),
    "EvidenceCoverageResult": ("aragora.debate.evidence_linker", "EvidenceCoverageResult"),
    "EventBus": ("aragora.debate.event_bus", "EventBus"),
    "EvidenceGap": ("aragora.debate.cross_proposal_analyzer", "EvidenceGap"),
    "EvidenceLink": ("aragora.debate.evidence_linker", "EvidenceLink"),
    "ExecutionResult": ("aragora.debate.phase_executor", "ExecutionResult"),
    "FailureType": ("aragora.debate.chaos_theater", "FailureType"),
    "FileCheckpointStore": ("aragora.debate.checkpoint", "FileCheckpointStore"),
    "GitCheckpointStore": ("aragora.debate.checkpoint", "GitCheckpointStore"),
    "GovernorConstraints": ("aragora.debate.complexity_governor", "GovernorConstraints"),
    "GraphDebateOrchestrator": ("aragora.debate.graph", "GraphDebateOrchestrator"),
    "GraphReplayBuilder": ("aragora.debate.graph", "GraphReplayBuilder"),
    "HealthEvent": ("aragora.debate.immune_system", "HealthEvent"),
    "HealthStatus": ("aragora.debate.immune_system", "HealthStatus"),
    "ImpactDetector": ("aragora.debate.counterfactual", "ImpactDetector"),
    "JudgePanel": ("aragora.debate.judge_selector", "JudgePanel"),
    "JudgeSelector": ("aragora.debate.judge_selector", "JudgeSelector"),
    "JudgeVote": ("aragora.debate.judge_selector", "JudgeVote"),
    "JudgeVoteRecord": ("aragora.debate.judge_selector", "JudgeVoteRecord"),
    "JudgingResult": ("aragora.debate.judge_selector", "JudgingResult"),
    "JudgingStrategy": ("aragora.debate.judge_selector", "JudgingStrategy"),
    "create_judge_panel": ("aragora.debate.judge_selector", "create_judge_panel"),
    "MatrixDebateRunner": ("aragora.debate.scenarios", "MatrixDebateRunner"),
    "MatrixResult": ("aragora.debate.scenarios", "MatrixResult"),
    "MergeResult": ("aragora.debate.graph", "MergeResult"),
    "MergeStrategy": ("aragora.debate.graph", "MergeStrategy"),
    "NodeType": ("aragora.debate.graph", "NodeType"),
    "OutcomeCategory": ("aragora.debate.scenarios", "OutcomeCategory"),
    "OutcomeTracker": ("aragora.debate.outcome_tracker", "OutcomeTracker"),
    "PhaseExecutor": ("aragora.debate.phase_executor", "PhaseExecutor"),
    "PivotClaim": ("aragora.debate.counterfactual", "PivotClaim"),
    "RecoveryNarrative": ("aragora.debate.recovery_narrator", "RecoveryNarrative"),
    "RecoveryNarrator": ("aragora.debate.recovery_narrator", "RecoveryNarrator"),
    "ResumedDebate": ("aragora.debate.checkpoint", "ResumedDebate"),
    "RhetoricalAnalysisObserver": (
        "aragora.debate.rhetorical_observer",
        "RhetoricalAnalysisObserver",
    ),
    "RhetoricalObservation": ("aragora.debate.rhetorical_observer", "RhetoricalObservation"),
    "RhetoricalPattern": ("aragora.debate.rhetorical_observer", "RhetoricalPattern"),
    "S3CheckpointStore": ("aragora.debate.checkpoint", "S3CheckpointStore"),
    "STRESS_BUDGETS": ("aragora.debate.cognitive_limiter", "STRESS_BUDGETS"),
    "Scenario": ("aragora.debate.scenarios", "Scenario"),
    "ScenarioComparator": ("aragora.debate.scenarios", "ScenarioComparator"),
    "ScenarioMatrix": ("aragora.debate.scenarios", "ScenarioMatrix"),
    "ScenarioResult": ("aragora.debate.scenarios", "ScenarioResult"),
    "ScenarioType": ("aragora.debate.scenarios", "ScenarioType"),
    "SharedEvidence": ("aragora.debate.cross_proposal_analyzer", "SharedEvidence"),
    "StressLevel": ("aragora.debate.complexity_governor", "StressLevel"),
    "TheaterResponse": ("aragora.debate.chaos_theater", "TheaterResponse"),
    "TransparentImmuneSystem": ("aragora.debate.immune_system", "TransparentImmuneSystem"),
    "WisdomInjection": ("aragora.debate.wisdom_injector", "WisdomInjection"),
    "WisdomInjector": ("aragora.debate.wisdom_injector", "WisdomInjector"),
    "WisdomSubmission": ("aragora.debate.wisdom_injector", "WisdomSubmission"),
    "checkpoint_debate": ("aragora.debate.checkpoint", "checkpoint_debate"),
    "close_blackbox": ("aragora.debate.blackbox", "close_blackbox"),
    "close_wisdom_injector": ("aragora.debate.wisdom_injector", "close_wisdom_injector"),
    "create_risk_scenarios": ("aragora.debate.scenarios", "create_risk_scenarios"),
    "create_scale_scenarios": ("aragora.debate.scenarios", "create_scale_scenarios"),
    "create_time_horizon_scenarios": ("aragora.debate.scenarios", "create_time_horizon_scenarios"),
    "explore_counterfactual": ("aragora.debate.counterfactual", "explore_counterfactual"),
    "get_blackbox": ("aragora.debate.blackbox", "get_blackbox"),
    "get_chaos_director": ("aragora.debate.chaos_theater", "get_chaos_director"),
    "get_complexity_governor": ("aragora.debate.complexity_governor", "get_complexity_governor"),
    "get_immune_system": ("aragora.debate.immune_system", "get_immune_system"),
    "get_narrator": ("aragora.debate.recovery_narrator", "get_narrator"),
    "get_rhetorical_observer": ("aragora.debate.rhetorical_observer", "get_rhetorical_observer"),
    "get_wisdom_injector": ("aragora.debate.wisdom_injector", "get_wisdom_injector"),
    "limit_debate_context": ("aragora.debate.cognitive_limiter", "limit_debate_context"),
    "reset_complexity_governor": (
        "aragora.debate.complexity_governor",
        "reset_complexity_governor",
    ),
    "reset_immune_system": ("aragora.debate.immune_system", "reset_immune_system"),
    "reset_narrator": ("aragora.debate.recovery_narrator", "reset_narrator"),
    "reset_rhetorical_observer": (
        "aragora.debate.rhetorical_observer",
        "reset_rhetorical_observer",
    ),
    "setup_narrator_with_immune_system": (
        "aragora.debate.recovery_narrator",
        "setup_narrator_with_immune_system",
    ),
    "theatrical_error": ("aragora.debate.chaos_theater", "theatrical_error"),
    "theatrical_timeout": ("aragora.debate.chaos_theater", "theatrical_timeout"),
    # Translation / Multilingual
    "Language": ("aragora.debate.translation", "Language"),
    "TranslationResult": ("aragora.debate.translation", "TranslationResult"),
    "TranslationService": ("aragora.debate.translation", "TranslationService"),
    "MultilingualDebateConfig": ("aragora.debate.translation", "MultilingualDebateConfig"),
    "MultilingualDebateManager": ("aragora.debate.translation", "MultilingualDebateManager"),
    "get_translation_service": ("aragora.debate.translation", "get_translation_service"),
    "get_multilingual_manager": ("aragora.debate.translation", "get_multilingual_manager"),
    # Extended Hooks System
    "HookManager": ("aragora.debate.hooks", "HookManager"),
    "HookPriority": ("aragora.debate.hooks", "HookPriority"),
    "HookType": ("aragora.debate.hooks", "HookType"),
    "create_hook_manager": ("aragora.debate.hooks", "create_hook_manager"),
    # Cancellation
    "CancellationToken": ("aragora.debate.cancellation", "CancellationToken"),
    "CancellationScope": ("aragora.debate.cancellation", "CancellationScope"),
    "CancellationReason": ("aragora.debate.cancellation", "CancellationReason"),
    "DebateCancelled": ("aragora.debate.cancellation", "DebateCancelled"),
    "create_linked_token": ("aragora.debate.cancellation", "create_linked_token"),
    # Session Management
    "DebateSession": ("aragora.debate.session", "DebateSession"),
    "DebateSessionState": ("aragora.debate.session", "DebateSessionState"),
    "SessionManager": ("aragora.debate.session", "SessionManager"),
    # Topology
    "TopologySelector": ("aragora.debate.topology", "TopologySelector"),
    "AdaptiveSelector": ("aragora.debate.topology", "AdaptiveSelector"),
    "TopologyConfig": ("aragora.debate.topology", "TopologyConfig"),
    # Delegation Strategies
    "DelegationStrategy": ("aragora.debate.delegation", "DelegationStrategy"),
    "ContentBasedDelegation": ("aragora.debate.delegation", "ContentBasedDelegation"),
    "LoadBalancedDelegation": ("aragora.debate.delegation", "LoadBalancedDelegation"),
    "ExpertiseDelegation": ("aragora.debate.delegation", "ExpertiseDelegation"),
    "HybridDelegation": ("aragora.debate.delegation", "HybridDelegation"),
    "RoundRobinDelegation": ("aragora.debate.delegation", "RoundRobinDelegation"),
    "create_default_delegation": ("aragora.debate.delegation", "create_default_delegation"),
    # Byzantine Consensus
    "ByzantineConsensus": ("aragora.debate.byzantine", "ByzantineConsensus"),
    "ByzantineConsensusConfig": ("aragora.debate.byzantine", "ByzantineConsensusConfig"),
    "ByzantineConsensusResult": ("aragora.debate.byzantine", "ByzantineConsensusResult"),
    "ByzantinePhase": ("aragora.debate.byzantine", "ByzantinePhase"),
    "verify_with_byzantine_consensus": (
        "aragora.debate.byzantine",
        "verify_with_byzantine_consensus",
    ),
    # Stream Chaining
    "StreamChain": ("aragora.debate.stream_chain", "StreamChain"),
    "StreamBuffer": ("aragora.debate.stream_chain", "StreamBuffer"),
    "StreamMessage": ("aragora.debate.stream_chain", "StreamMessage"),
    "ChainedDebate": ("aragora.debate.stream_chain", "ChainedDebate"),
    "create_chain_from_topology": ("aragora.debate.stream_chain", "create_chain_from_topology"),
    # High-Level Debate Service
    "DebateService": ("aragora.debate.service", "DebateService"),
    "DebateOptions": ("aragora.debate.service", "DebateOptions"),
    "get_debate_service": ("aragora.debate.service", "get_debate_service"),
    "reset_debate_service": ("aragora.debate.service", "reset_debate_service"),
}


def __getattr__(name: str) -> Any:
    """Lazily import debate symbols to avoid heavy import side effects."""
    try:
        module_name, attr_name = _EXPORT_MAP[name]
    except KeyError as exc:
        raise AttributeError(f"module 'aragora.debate' has no attribute {name!r}") from exc
    module = importlib.import_module(module_name)
    value = getattr(module, attr_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))


__all__ = [
    "Arena",
    "ArenaBuilder",
    "ArenaConfig",
    "ArenaExtensions",
    "ArenaKnowledgeManager",
    "ExtensionsConfig",
    "SubsystemCoordinator",
    "SubsystemConfig",
    "DebateHooks",
    "HooksConfig",
    "InitPhase",
    "DebateProtocol",
    # Core Services (extracted from Arena)
    "EventBus",
    "AgentPool",
    "PhaseExecutor",
    "ExecutionResult",
    # Judge Selection
    "JudgeSelector",
    "JudgePanel",
    "JudgingStrategy",
    "JudgeVote",
    "JudgeVoteRecord",
    "JudgingResult",
    "create_judge_panel",
    # Graph-based debates
    "DebateGraph",
    "DebateNode",
    "Branch",
    "BranchPolicy",
    "BranchReason",
    "MergeStrategy",
    "MergeResult",
    "ConvergenceScorer",
    "GraphReplayBuilder",
    "GraphDebateOrchestrator",
    "NodeType",
    # Scenario Matrix
    "ScenarioMatrix",
    "Scenario",
    "ScenarioType",
    "ScenarioResult",
    "MatrixResult",
    "MatrixDebateRunner",
    "ScenarioComparator",
    "OutcomeCategory",
    "create_scale_scenarios",
    "create_risk_scenarios",
    "create_time_horizon_scenarios",
    # Counterfactual Branching
    "CounterfactualOrchestrator",
    "CounterfactualBranch",
    "ConditionalConsensus",
    "PivotClaim",
    "ImpactDetector",
    "CounterfactualIntegration",
    "CounterfactualStatus",
    "BranchComparison",
    "explore_counterfactual",
    # Checkpointing
    "CheckpointManager",
    "DebateCheckpoint",
    "CheckpointStore",
    "FileCheckpointStore",
    "S3CheckpointStore",
    "GitCheckpointStore",
    "CheckpointConfig",
    "CheckpointStatus",
    "ResumedDebate",
    "AgentState",
    "CheckpointWebhook",
    "checkpoint_debate",
    # Blackbox Protocol
    "BlackboxRecorder",
    "BlackboxEvent",
    "BlackboxSnapshot",
    "get_blackbox",
    "close_blackbox",
    # Transparent Immune System
    "TransparentImmuneSystem",
    "HealthEvent",
    "HealthStatus",
    "AgentStatus",
    "AgentHealthState",
    "get_immune_system",
    "reset_immune_system",
    # Wisdom Injector
    "WisdomInjector",
    "WisdomSubmission",
    "WisdomInjection",
    "get_wisdom_injector",
    "close_wisdom_injector",
    # Complexity Governor
    "AdaptiveComplexityGovernor",
    "GovernorConstraints",
    "StressLevel",
    "get_complexity_governor",
    "reset_complexity_governor",
    # Cognitive Load Limiter
    "CognitiveLoadLimiter",
    "CognitiveBudget",
    "limit_debate_context",
    # RLM-Enhanced Cognitive Load Limiter
    "RLMCognitiveLoadLimiter",
    "RLMCognitiveBudget",
    "CompressedContext",
    "create_rlm_limiter",
    "STRESS_BUDGETS",
    # Recovery Narrator
    "RecoveryNarrator",
    "RecoveryNarrative",
    "get_narrator",
    "reset_narrator",
    "setup_narrator_with_immune_system",
    # Rhetorical Observer
    "RhetoricalAnalysisObserver",
    "RhetoricalObservation",
    "RhetoricalPattern",
    "get_rhetorical_observer",
    "reset_rhetorical_observer",
    # Chaos Theater
    "ChaosDirector",
    "TheaterResponse",
    "FailureType",
    "DramaLevel",
    "get_chaos_director",
    "theatrical_timeout",
    "theatrical_error",
    # Outcome Tracker
    "OutcomeTracker",
    "ConsensusOutcome",
    "CalibrationBucket",
    # Evidence-Claim Linker
    "EvidenceClaimLinker",
    "EvidenceLink",
    "ClaimAnalysis",
    "EvidenceCoverageResult",
    # Cross-Proposal Analyzer
    "CrossProposalAnalyzer",
    "CrossProposalAnalysis",
    "SharedEvidence",
    "Contradiction",
    "EvidenceGap",
    # Translation / Multilingual
    "Language",
    "TranslationResult",
    "TranslationService",
    "MultilingualDebateConfig",
    "MultilingualDebateManager",
    "get_translation_service",
    "get_multilingual_manager",
    # Extended Hooks System
    "HookManager",
    "HookPriority",
    "HookType",
    "create_hook_manager",
    # Cancellation
    "CancellationToken",
    "CancellationScope",
    "CancellationReason",
    "DebateCancelled",
    "create_linked_token",
    # Session Management
    "DebateSession",
    "DebateSessionState",
    "SessionManager",
    # Topology
    "TopologySelector",
    "AdaptiveSelector",
    "TopologyConfig",
    # Delegation Strategies
    "DelegationStrategy",
    "ContentBasedDelegation",
    "LoadBalancedDelegation",
    "ExpertiseDelegation",
    "HybridDelegation",
    "RoundRobinDelegation",
    "create_default_delegation",
    # Byzantine Consensus
    "ByzantineConsensus",
    "ByzantineConsensusConfig",
    "ByzantineConsensusResult",
    "ByzantinePhase",
    "verify_with_byzantine_consensus",
    # Stream Chaining
    "StreamChain",
    "StreamBuffer",
    "StreamMessage",
    "ChainedDebate",
    "create_chain_from_topology",
    # High-Level Debate Service
    "DebateService",
    "DebateOptions",
    "get_debate_service",
    "reset_debate_service",
]
