from __future__ import annotations

from pathlib import Path

import scripts.generate_openapi as generate_openapi
from aragora.server.handlers.openapi_decorator import (
    api_endpoint,
    clear_registry,
    get_registered_endpoints,
)


def test_ast_extract_endpoints_cleans_docstrings(tmp_path, monkeypatch) -> None:
    monkeypatch.setattr(generate_openapi, "PROJECT_ROOT", tmp_path)
    handler_path = tmp_path / "example_handler.py"
    handler_path.write_text(
        """
from aragora.server.handlers.openapi_decorator import api_endpoint


class ExampleHandler:
    @api_endpoint(path="/api/example", method="GET", summary="Example")
    def handle(self):
        \"\"\"Example summary.

        Details line.
            Preserved nested indentation.
        \"\"\"
        return None
""".strip()
        + "\n",
        encoding="utf-8",
    )

    endpoints = generate_openapi._ast_extract_endpoints_from_file(handler_path)

    assert len(endpoints) == 1
    assert endpoints[0]["description"] == (
        "Example summary.\n\nDetails line.\n    Preserved nested indentation."
    )


def test_api_endpoint_cleans_docstrings() -> None:
    clear_registry()

    @api_endpoint(path="/api/example", method="GET", summary="Example")
    def handle() -> None:
        """Example summary.

        Details line.
            Preserved nested indentation.
        """

    try:
        endpoints = get_registered_endpoints()
        assert endpoints[-1].description == (
            "Example summary.\n\nDetails line.\n    Preserved nested indentation."
        )
    finally:
        clear_registry()


def test_merge_paths_prefers_metadata_over_autogenerated_placeholders() -> None:
    merged = {
        "/api/v1/decision-analytics/example": {
            "get": {
                "summary": "Autogenerated placeholder (spec pending)",
                "x-autogenerated": True,
            }
        }
    }
    incoming = {
        "/api/v1/decision-analytics/example": {
            "get": {
                "summary": "Rich endpoint metadata",
                "operationId": "handle_example",
            }
        }
    }

    generate_openapi._merge_paths_prefer_metadata(merged, incoming)

    operation = merged["/api/v1/decision-analytics/example"]["get"]
    assert operation["summary"] == "Rich endpoint metadata"
    assert operation["operationId"] == "handle_example"
    assert operation.get("x-autogenerated") is not True


def test_merge_paths_preserves_unrelated_autogenerated_placeholders() -> None:
    merged = {
        "/api/v1/example": {
            "get": {
                "summary": "Autogenerated placeholder (spec pending)",
                "x-autogenerated": True,
            }
        }
    }
    incoming = {
        "/api/v1/example": {
            "get": {
                "summary": "Rich endpoint metadata",
                "operationId": "handle_example",
            }
        }
    }

    generate_openapi._merge_paths_prefer_metadata(merged, incoming)

    operation = merged["/api/v1/example"]["get"]
    assert operation["summary"] == "Autogenerated placeholder (spec pending)"
    assert operation.get("x-autogenerated") is True


def test_route_to_spec_path_converts_wildcards_and_version() -> None:
    assert (
        generate_openapi._route_to_spec_path("/api/v1/rbac/roles/*")
        == "/api/v1/rbac/roles/{role_id}"
    )
    assert generate_openapi._route_to_spec_path("/api/runs") == "/api/v1/runs"
    assert (
        generate_openapi._route_to_spec_path("/api/v1/ideas/*/edges/*")
        == "/api/v1/ideas/{idea_id}/edges/{edge_id}"
    )
    assert (
        generate_openapi._route_to_spec_path("POST /api/v1/canvas/pipeline/run")
        == "/api/v1/canvas/pipeline/run"
    )
    # /api/v2 must not be rewritten to /api/v1
    assert generate_openapi._route_to_spec_path("/api/v2/tasks/*") == "/api/v2/tasks/{task_id}"


def test_handler_routes_supplement_adds_uncovered_routes(monkeypatch) -> None:
    import sys
    import types

    class DummyHandler:
        """Dummy handler for supplement tests."""

        ROUTES = [
            "/api/v1/dummy/things",
            "/api/v1/dummy/things/*",
            "/api/v1/dummy/execute",
            "/api/v1/control-plane/internal-only",
        ]
        POST_ROUTES = ["/api/v1/dummy/submit"]

    fake_registry = types.SimpleNamespace(HANDLER_REGISTRY=[("_dummy", DummyHandler)])
    monkeypatch.setitem(sys.modules, "aragora.server.handler_registry", fake_registry)

    existing = {"/api/v1/dummy/things": {"get": {"summary": "documented"}}}
    supplement = generate_openapi._collect_handler_routes_supplement(existing)

    # Covered path is skipped; wildcard becomes a named param
    assert "/api/v1/dummy/things" not in supplement
    assert "/api/v1/dummy/things/{thing_id}" in supplement
    # Internal prefix families are never published
    assert not any(p.startswith("/api/v1/control-plane/") for p in supplement)
    # Action-verb segment infers POST; plain segments infer GET
    assert "post" in supplement["/api/v1/dummy/execute"]
    assert supplement["/api/v1/dummy/execute"]["post"]["x-method-inferred"] is True
    # Method-specific *_ROUTES carry their declared method
    assert "post" in supplement["/api/v1/dummy/submit"]
    assert supplement["/api/v1/dummy/submit"]["post"]["x-method-inferred"] is False
    # Every supplement operation is marked autogenerated + experimental
    for methods in supplement.values():
        for op in methods.values():
            assert op["x-autogenerated"] is True
            assert op["x-aragora-stability"] == "experimental"


def test_handler_routes_supplement_merges_multiple_methods(monkeypatch) -> None:
    import sys
    import types

    class DummyHandler:
        GET_ROUTES = ["/api/v1/dummy/item"]
        DELETE_ROUTES = ["/api/v1/dummy/item"]

    fake_registry = types.SimpleNamespace(HANDLER_REGISTRY=[("_dummy", DummyHandler)])
    monkeypatch.setitem(sys.modules, "aragora.server.handler_registry", fake_registry)

    supplement = generate_openapi._collect_handler_routes_supplement({})

    assert set(supplement["/api/v1/dummy/item"]) == {"get", "delete"}
