/**
 * OpenAPI Namespace API (autogenerated)
 *
 * Provides request helpers for every non-deprecated OpenAPI endpoint.
 */

type OpenApiRequestOptions = { params?: Record<string, unknown>; body?: unknown };
interface OpenApiClientInterface { request<T>(method: string, path: string, options?: OpenApiRequestOptions): Promise<T>; }

export class OpenApiAPI {
  constructor(private client: OpenApiClientInterface) {}

  async getSpec(): Promise<Record<string, unknown>> {
    return this.client.request('GET', '/api/v1/openapi');
  }

  async requestGet_wellKnownAgent_json(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/.well-known/agent.json', { params });
  }

  async requestGetApiV1A2a_wellKnownAgent_json(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/a2a/.well-known/agent.json', { params });
  }

  async requestGetApiV1A2aAgents(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/a2a/agents', { params });
  }

  async requestGetApiV1A2aAgentsByName(name: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/a2a/agents/${encodeURIComponent(name)}`, { params });
  }

  async requestGetApiV1A2aOpenapi_json(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/a2a/openapi.json', { params });
  }

  async requestPostApiV1A2aTasks(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/a2a/tasks', { body, params });
  }

  async requestGetApiV1A2aTasksByTaskId(task_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/a2a/tasks/${encodeURIComponent(task_id)}`, { params });
  }

  async requestDeleteApiV1A2aTasksByTaskId(task_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('DELETE', `/api/v1/a2a/tasks/${encodeURIComponent(task_id)}`, { params });
  }

  async requestPostApiV1A2aTasksByTaskIdStream(task_id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/a2a/tasks/${encodeURIComponent(task_id)}/stream`, { body, params });
  }

  async requestPostApiV1AdminImpersonateByUserId(user_id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/admin/impersonate/${encodeURIComponent(user_id)}`, { body, params });
  }

  async requestGetApiV1AdminNomicCircuitBreakers(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/admin/nomic/circuit-breakers', { params });
  }

  async requestPostApiV1AdminNomicCircuitBreakersReset(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/admin/nomic/circuit-breakers/reset', { body, params });
  }

  async requestPostApiV1AdminNomicPause(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/admin/nomic/pause', { body, params });
  }

  async requestPostApiV1AdminNomicReset(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/admin/nomic/reset', { body, params });
  }

  async requestPostApiV1AdminNomicResume(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/admin/nomic/resume', { body, params });
  }

  async requestGetApiV1AdminNomicStatus(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/admin/nomic/status', { params });
  }

  async requestGetApiV1AdminOrganizations(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/admin/organizations', { params });
  }

  async requestGetApiV1AdminRevenue(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/admin/revenue', { params });
  }

  async requestGetApiV1AdminSecurityHealth(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/admin/security/health', { params });
  }

  async requestGetApiV1AdminSecurityKeys(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/admin/security/keys', { params });
  }

  async requestPostApiV1AdminSecurityRotateKey(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/admin/security/rotate-key', { body, params });
  }

  async requestGetApiV1AdminSecurityStatus(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/admin/security/status', { params });
  }

  async requestGetApiV1AdminStats(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/admin/stats', { params });
  }

  async requestGetApiV1AdminSystemMetrics(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/admin/system/metrics', { params });
  }

  async requestGetApiV1AdminUsers(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/admin/users', { params });
  }

  async requestPostApiV1AdvertisingAnalyze(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/advertising/analyze', { body, params });
  }

  async requestGetApiV1AdvertisingBudgetRecommendations(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/advertising/budget-recommendations', { params });
  }

  async requestGetApiV1AdvertisingCampaigns(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/advertising/campaigns', { params });
  }

  async requestPostApiV1AdvertisingConnect(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/advertising/connect', { body, params });
  }

  async requestGetApiV1AdvertisingPerformance(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/advertising/performance', { params });
  }

  async requestGetApiV1AdvertisingPlatforms(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/advertising/platforms', { params });
  }

  async requestDeleteApiV1AdvertisingByPlatform(platform: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('DELETE', `/api/v1/advertising/${encodeURIComponent(platform)}`, { params });
  }

  async requestGetApiV1AdvertisingByPlatformCampaigns(platform: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/advertising/${encodeURIComponent(platform)}/campaigns`, { params });
  }

  async requestPostApiV1AdvertisingByPlatformCampaigns(platform: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/advertising/${encodeURIComponent(platform)}/campaigns`, { body, params });
  }

  async requestGetApiV1AdvertisingByPlatformCampaignsByCampaignId(platform: string, campaign_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/advertising/${encodeURIComponent(platform)}/campaigns/${encodeURIComponent(campaign_id)}`, { params });
  }

  async requestPutApiV1AdvertisingByPlatformCampaignsByCampaignId(platform: string, campaign_id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('PUT', `/api/v1/advertising/${encodeURIComponent(platform)}/campaigns/${encodeURIComponent(campaign_id)}`, { body, params });
  }

  async requestGetApiV1AdvertisingByPlatformPerformance(platform: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/advertising/${encodeURIComponent(platform)}/performance`, { params });
  }

  async requestGetApiV1AgentCompare(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/agent/compare', { params });
  }

  async requestGetApiV1AgentByNameAccuracy(name: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/agent/${encodeURIComponent(name)}/accuracy`, { params });
  }

  async requestGetApiV1AgentByNameAllies(name: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/agent/${encodeURIComponent(name)}/allies`, { params });
  }

  async requestGetApiV1AgentByNameCalibration(name: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/agent/${encodeURIComponent(name)}/calibration`, { params });
  }

  async requestGetApiV1AgentByNameCalibrationCurve(name: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/agent/${encodeURIComponent(name)}/calibration-curve`, { params });
  }

  async requestGetApiV1AgentByNameCalibrationSummary(name: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/agent/${encodeURIComponent(name)}/calibration-summary`, { params });
  }

  async requestGetApiV1AgentByNameConsistency(name: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/agent/${encodeURIComponent(name)}/consistency`, { params });
  }

  async requestGetApiV1AgentByNameDomains(name: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/agent/${encodeURIComponent(name)}/domains`, { params });
  }

  async requestGetApiV1AgentByNameFlips(name: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/agent/${encodeURIComponent(name)}/flips`, { params });
  }

  async requestGetApiV1AgentByNameGroundedPersona(name: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/agent/${encodeURIComponent(name)}/grounded-persona`, { params });
  }

  async requestGetApiV1AgentByNameHistory(name: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/agent/${encodeURIComponent(name)}/history`, { params });
  }

  async requestGetApiV1AgentByNameIdentityPrompt(name: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/agent/${encodeURIComponent(name)}/identity-prompt`, { params });
  }

  async requestGetApiV1AgentByNameMoments(name: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/agent/${encodeURIComponent(name)}/moments`, { params });
  }

  async requestGetApiV1AgentByNameNetwork(name: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/agent/${encodeURIComponent(name)}/network`, { params });
  }

  async requestGetApiV1AgentByNamePerformance(name: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/agent/${encodeURIComponent(name)}/performance`, { params });
  }

  async requestGetApiV1AgentByNamePersona(name: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/agent/${encodeURIComponent(name)}/persona`, { params });
  }

  async requestGetApiV1AgentByNameProfile(name: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/agent/${encodeURIComponent(name)}/profile`, { params });
  }

  async requestGetApiV1AgentByNameReputation(name: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/agent/${encodeURIComponent(name)}/reputation`, { params });
  }

  async requestGetApiV1AgentByNameRivals(name: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/agent/${encodeURIComponent(name)}/rivals`, { params });
  }

  async requestGetApiV1Agents(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/agents', { params });
  }

  async requestGetApiV1AgentsAvailability(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/agents/availability', { params });
  }

  async requestGetApiV1AgentsHealth(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/agents/health', { params });
  }

  async requestGetApiV1AgentsLocal(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/agents/local', { params });
  }

  async requestGetApiV1AgentsLocalStatus(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/agents/local/status', { params });
  }

  async requestGetApiV1AnalyticsDisagreements(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/analytics/disagreements', { params });
  }

  async requestGetApiV1AnalyticsEarlyStops(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/analytics/early-stops', { params });
  }

  async requestGetApiV1AnalyticsRoleRotation(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/analytics/role-rotation', { params });
  }

  async requestGetApiV1AuditEntries(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/audit/entries', { params });
  }

  async requestGetApiV1AuditReport(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/audit/report', { params });
  }

  async requestGetApiV1AuditSessions(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/audit/sessions', { params });
  }

  async requestPostApiV1AuditSessions(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/audit/sessions', { body, params });
  }

  async requestGetApiV1AuditSessionsBySessionId(session_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/audit/sessions/${encodeURIComponent(session_id)}`, { params });
  }

  async requestDeleteApiV1AuditSessionsBySessionId(session_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('DELETE', `/api/v1/audit/sessions/${encodeURIComponent(session_id)}`, { params });
  }

  async requestPostApiV1AuditSessionsBySessionIdCancel(session_id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/audit/sessions/${encodeURIComponent(session_id)}/cancel`, { body, params });
  }

  async requestGetApiV1AuditSessionsBySessionIdEvents(session_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/audit/sessions/${encodeURIComponent(session_id)}/events`, { params });
  }

  async requestGetApiV1AuditSessionsBySessionIdFindings(session_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/audit/sessions/${encodeURIComponent(session_id)}/findings`, { params });
  }

  async requestPostApiV1AuditSessionsBySessionIdIntervene(session_id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/audit/sessions/${encodeURIComponent(session_id)}/intervene`, { body, params });
  }

  async requestPostApiV1AuditSessionsBySessionIdPause(session_id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/audit/sessions/${encodeURIComponent(session_id)}/pause`, { body, params });
  }

  async requestGetApiV1AuditSessionsBySessionIdReport(session_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/audit/sessions/${encodeURIComponent(session_id)}/report`, { params });
  }

  async requestPostApiV1AuditSessionsBySessionIdResume(session_id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/audit/sessions/${encodeURIComponent(session_id)}/resume`, { body, params });
  }

  async requestPostApiV1AuditSessionsBySessionIdStart(session_id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/audit/sessions/${encodeURIComponent(session_id)}/start`, { body, params });
  }

  async requestGetApiV1AuditVerify(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/audit/verify', { params });
  }

  async requestGetApiV1AuthApiKey(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/auth/api-key', { params });
  }

  async requestPostApiV1AuthApiKey(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/auth/api-key', { body, params });
  }

  async requestDeleteApiV1AuthApiKey(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('DELETE', '/api/v1/auth/api-key', { params });
  }

  async requestPostApiV1AuthLogin(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/auth/login', { body, params });
  }

  async requestPostApiV1AuthLogout(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/auth/logout', { body, params });
  }

  async requestPostApiV1AuthLogoutAll(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/auth/logout-all', { body, params });
  }

  async requestGetApiV1AuthMe(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/auth/me', { params });
  }

  async requestPutApiV1AuthMe(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('PUT', '/api/v1/auth/me', { body, params });
  }

  async requestPostApiV1AuthMfaBackupCodes(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/auth/mfa/backup-codes', { body, params });
  }

  async requestPostApiV1AuthMfaDisable(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/auth/mfa/disable', { body, params });
  }

  async requestPostApiV1AuthMfaEnable(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/auth/mfa/enable', { body, params });
  }

  async requestPostApiV1AuthMfaSetup(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/auth/mfa/setup', { body, params });
  }

  async requestPostApiV1AuthMfaVerify(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/auth/mfa/verify', { body, params });
  }

  async requestGetApiV1AuthOauthGithub(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/auth/oauth/github', { params });
  }

  async requestGetApiV1AuthOauthGithubCallback(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/auth/oauth/github/callback', { params });
  }

  async requestGetApiV1AuthOauthGoogle(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/auth/oauth/google', { params });
  }

  async requestGetApiV1AuthOauthGoogleCallback(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/auth/oauth/google/callback', { params });
  }

  async requestPostApiV1AuthOauthLink(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/auth/oauth/link', { body, params });
  }

  async requestGetApiV1AuthOauthProviders(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/auth/oauth/providers', { params });
  }

  async requestDeleteApiV1AuthOauthUnlink(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('DELETE', '/api/v1/auth/oauth/unlink', { params });
  }

  async requestPostApiV1AuthPassword(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/auth/password', { body, params });
  }

  async requestPostApiV1AuthRefresh(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/auth/refresh', { body, params });
  }

  async requestPostApiV1AuthRegister(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/auth/register', { body, params });
  }

  async requestPostApiV1AuthRevoke(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/auth/revoke', { body, params });
  }

  async requestGetApiV1AuthSessions(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/auth/sessions', { params });
  }

  async requestDeleteApiV1AuthSessionsBySessionId(session_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('DELETE', `/api/v1/auth/sessions/${encodeURIComponent(session_id)}`, { params });
  }

  async requestGetApiV1BeliefNetworkByDebateIdCruxes(debate_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/belief-network/${encodeURIComponent(debate_id)}/cruxes`, { params });
  }

  async requestGetApiV1BeliefNetworkByDebateIdLoadBearingClaims(debate_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/belief-network/${encodeURIComponent(debate_id)}/load-bearing-claims`, { params });
  }

  async requestPostApiV1BotsDiscordInteractions(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/bots/discord/interactions', { body, params });
  }

  async requestGetApiV1BotsDiscordStatus(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/bots/discord/status', { params });
  }

  async requestGetApiV1BotsGoogleChatStatus(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/bots/google-chat/status', { params });
  }

  async requestPostApiV1BotsGoogleChatWebhook(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/bots/google-chat/webhook', { body, params });
  }

  async requestPostApiV1BotsTeamsMessages(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/bots/teams/messages', { body, params });
  }

  async requestGetApiV1BotsTeamsStatus(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/bots/teams/status', { params });
  }

  async requestGetApiV1BotsTelegramStatus(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/bots/telegram/status', { params });
  }

  async requestPostApiV1BotsTelegramWebhook(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/bots/telegram/webhook', { body, params });
  }

  async requestPostApiV1BotsTelegramWebhookByToken(token: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/bots/telegram/webhook/${encodeURIComponent(token)}`, { body, params });
  }

  async requestGetApiV1BotsWhatsappStatus(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/bots/whatsapp/status', { params });
  }

  async requestPostApiV1BotsWhatsappWebhook(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/bots/whatsapp/webhook', { body, params });
  }

  async requestGetApiV1BotsWhatsappWebhook(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/bots/whatsapp/webhook', { params });
  }

  async requestPostApiV1BotsZoomEvents(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/bots/zoom/events', { body, params });
  }

  async requestGetApiV1BotsZoomStatus(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/bots/zoom/status', { params });
  }

  async requestGetApiV1Budgets(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/budgets', { params });
  }

  async requestPostApiV1Budgets(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/budgets', { body, params });
  }

  async requestPostApiV1BudgetsCheck(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/budgets/check', { body, params });
  }

  async requestGetApiV1BudgetsSummary(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/budgets/summary', { params });
  }

  async requestGetApiV1BudgetsByBudgetId(budget_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/budgets/${encodeURIComponent(budget_id)}`, { params });
  }

  async requestPatchApiV1BudgetsByBudgetId(budget_id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('PATCH', `/api/v1/budgets/${encodeURIComponent(budget_id)}`, { body, params });
  }

  async requestDeleteApiV1BudgetsByBudgetId(budget_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('DELETE', `/api/v1/budgets/${encodeURIComponent(budget_id)}`, { params });
  }

  async requestGetApiV1BudgetsByBudgetIdAlerts(budget_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/budgets/${encodeURIComponent(budget_id)}/alerts`, { params });
  }

  async requestPostApiV1BudgetsByBudgetIdAlertsByAlertIdAcknowledge(budget_id: string, alert_id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/budgets/${encodeURIComponent(budget_id)}/alerts/${encodeURIComponent(alert_id)}/acknowledge`, { body, params });
  }

  async requestPostApiV1BudgetsByBudgetIdOverride(budget_id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/budgets/${encodeURIComponent(budget_id)}/override`, { body, params });
  }

  async requestDeleteApiV1BudgetsByBudgetIdOverrideByUserId(budget_id: string, user_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('DELETE', `/api/v1/budgets/${encodeURIComponent(budget_id)}/override/${encodeURIComponent(user_id)}`, { params });
  }

  async requestPostApiV1BudgetsByBudgetIdReset(budget_id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/budgets/${encodeURIComponent(budget_id)}/reset`, { body, params });
  }

  async requestGetApiV1CalibrationLeaderboard(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/calibration/leaderboard', { params });
  }

  async requestGetApiV1ChatKnowledgeChannelByChannelIdSummary(channel_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/chat/knowledge/channel/${encodeURIComponent(channel_id)}/summary`, { params });
  }

  async requestPostApiV1ChatKnowledgeInject(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/chat/knowledge/inject', { body, params });
  }

  async requestPostApiV1ChatKnowledgeSearch(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/chat/knowledge/search', { body, params });
  }

  async requestPostApiV1ChatKnowledgeStore(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/chat/knowledge/store', { body, params });
  }

  async requestPostApiV1Classify(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/classify', { body, params });
  }

  async requestGetApiV1ClassifyPolicyByLevel(level: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/classify/policy/${encodeURIComponent(level)}`, { params });
  }

  async requestPostApiV1CodebaseAnalyzeDependencies(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/codebase/analyze-dependencies', { body, params });
  }

  async requestPostApiV1CodebaseCheckLicenses(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/codebase/check-licenses', { body, params });
  }

  async requestPostApiV1CodebaseClearCache(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/codebase/clear-cache', { body, params });
  }

  async requestPostApiV1CodebaseSbom(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/codebase/sbom', { body, params });
  }

  async requestPostApiV1CodebaseScanVulnerabilities(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/codebase/scan-vulnerabilities', { body, params });
  }

  async requestPostApiV1CodebaseByRepoAnalyze(repo: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/codebase/${encodeURIComponent(repo)}/analyze`, { body, params });
  }

  async requestPostApiV1CodebaseByRepoAudit(repo: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/codebase/${encodeURIComponent(repo)}/audit`, { body, params });
  }

  async requestGetApiV1CodebaseByRepoAuditByAuditId(repo: string, audit_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/codebase/${encodeURIComponent(repo)}/audit/${encodeURIComponent(audit_id)}`, { params });
  }

  async requestGetApiV1CodebaseByRepoCallgraph(repo: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/codebase/${encodeURIComponent(repo)}/callgraph`, { params });
  }

  async requestGetApiV1CodebaseByRepoDeadcode(repo: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/codebase/${encodeURIComponent(repo)}/deadcode`, { params });
  }

  async requestGetApiV1CodebaseByRepoDuplicates(repo: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/codebase/${encodeURIComponent(repo)}/duplicates`, { params });
  }

  async requestGetApiV1CodebaseByRepoHotspots(repo: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/codebase/${encodeURIComponent(repo)}/hotspots`, { params });
  }

  async requestPostApiV1CodebaseByRepoImpact(repo: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/codebase/${encodeURIComponent(repo)}/impact`, { body, params });
  }

  async requestGetApiV1CodebaseByRepoMetrics(repo: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/codebase/${encodeURIComponent(repo)}/metrics`, { params });
  }

  async requestPostApiV1CodebaseByRepoMetricsAnalyze(repo: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/codebase/${encodeURIComponent(repo)}/metrics/analyze`, { body, params });
  }

  async requestGetApiV1CodebaseByRepoMetricsFileByFilePath(repo: string, file_path: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/codebase/${encodeURIComponent(repo)}/metrics/file/${encodeURIComponent(file_path)}`, { params });
  }

  async requestGetApiV1CodebaseByRepoMetricsHistory(repo: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/codebase/${encodeURIComponent(repo)}/metrics/history`, { params });
  }

  async requestGetApiV1CodebaseByRepoMetricsByAnalysisId(repo: string, analysis_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/codebase/${encodeURIComponent(repo)}/metrics/${encodeURIComponent(analysis_id)}`, { params });
  }

  async requestGetApiV1CodebaseByRepoSastFindings(repo: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/codebase/${encodeURIComponent(repo)}/sast/findings`, { params });
  }

  async requestGetApiV1CodebaseByRepoSastOwaspSummary(repo: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/codebase/${encodeURIComponent(repo)}/sast/owasp-summary`, { params });
  }

  async requestPostApiV1CodebaseByRepoScan(repo: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/codebase/${encodeURIComponent(repo)}/scan`, { body, params });
  }

  async requestGetApiV1CodebaseByRepoScanLatest(repo: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/codebase/${encodeURIComponent(repo)}/scan/latest`, { params });
  }

  async requestPostApiV1CodebaseByRepoScanSast(repo: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/codebase/${encodeURIComponent(repo)}/scan/sast`, { body, params });
  }

  async requestGetApiV1CodebaseByRepoScanSastByScanId(repo: string, scan_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/codebase/${encodeURIComponent(repo)}/scan/sast/${encodeURIComponent(scan_id)}`, { params });
  }

  async requestPostApiV1CodebaseByRepoScanSecrets(repo: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/codebase/${encodeURIComponent(repo)}/scan/secrets`, { body, params });
  }

  async requestGetApiV1CodebaseByRepoScanSecretsLatest(repo: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/codebase/${encodeURIComponent(repo)}/scan/secrets/latest`, { params });
  }

  async requestGetApiV1CodebaseByRepoScanSecretsByScanId(repo: string, scan_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/codebase/${encodeURIComponent(repo)}/scan/secrets/${encodeURIComponent(scan_id)}`, { params });
  }

  async requestGetApiV1CodebaseByRepoScanByScanId(repo: string, scan_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/codebase/${encodeURIComponent(repo)}/scan/${encodeURIComponent(scan_id)}`, { params });
  }

  async requestGetApiV1CodebaseByRepoScans(repo: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/codebase/${encodeURIComponent(repo)}/scans`, { params });
  }

  async requestGetApiV1CodebaseByRepoScansSecrets(repo: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/codebase/${encodeURIComponent(repo)}/scans/secrets`, { params });
  }

  async requestGetApiV1CodebaseByRepoSecrets(repo: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/codebase/${encodeURIComponent(repo)}/secrets`, { params });
  }

  async requestGetApiV1CodebaseByRepoSymbols(repo: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/codebase/${encodeURIComponent(repo)}/symbols`, { params });
  }

  async requestPostApiV1CodebaseByRepoUnderstand(repo: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/codebase/${encodeURIComponent(repo)}/understand`, { body, params });
  }

  async requestGetApiV1CodebaseByRepoVulnerabilities(repo: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/codebase/${encodeURIComponent(repo)}/vulnerabilities`, { params });
  }

  async requestGetApiV1ConsensusContrarianViews(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/consensus/contrarian-views', { params });
  }

  async requestGetApiV1ConsensusDissents(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/consensus/dissents', { params });
  }

  async requestGetApiV1ConsensusDomainByDomain(domain: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/consensus/domain/${encodeURIComponent(domain)}`, { params });
  }

  async requestGetApiV1ConsensusRiskWarnings(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/consensus/risk-warnings', { params });
  }

  async requestGetApiV1ConsensusSettled(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/consensus/settled', { params });
  }

  async requestGetApiV1ConsensusSimilar(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/consensus/similar', { params });
  }

  async requestGetApiV1ConsensusStats(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/consensus/stats', { params });
  }

  async requestGetApiV1CritiquesArchive(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/critiques/archive', { params });
  }

  async requestGetApiV1CritiquesPatterns(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/critiques/patterns', { params });
  }

  async requestGetApiV1CrossPollinationBridge(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/cross-pollination/bridge', { params });
  }

  async requestGetApiV1CrossPollinationKm(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/cross-pollination/km', { params });
  }

  async requestGetApiV1CrossPollinationKmCulture(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/cross-pollination/km/culture', { params });
  }

  async requestGetApiV1CrossPollinationKmStalenessCheck(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/cross-pollination/km/staleness-check', { params });
  }

  async requestPostApiV1CrossPollinationKmSync(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/cross-pollination/km/sync', { body, params });
  }

  async requestGetApiV1CrossPollinationMetrics(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/cross-pollination/metrics', { params });
  }

  async requestPostApiV1CrossPollinationReset(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/cross-pollination/reset', { body, params });
  }

  async requestGetApiV1CrossPollinationStats(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/cross-pollination/stats', { params });
  }

  async requestGetApiV1CrossPollinationSubscribers(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/cross-pollination/subscribers', { params });
  }

  async requestGetApiV1DashboardDebates(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/dashboard/debates', { params });
  }

  async requestGetApiV1DebateByDebateIdGraphStats(debate_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/debate/${encodeURIComponent(debate_id)}/graph-stats`, { params });
  }

  async requestGetApiV1Debates(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/debates', { params });
  }

  async requestPostApiV1Debates(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/debates', { body, params });
  }

  async requestPostApiV1DebatesCapabilityProbe(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/debates/capability-probe', { body, params });
  }

  async requestPostApiV1DebatesDeepAudit(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/debates/deep-audit', { body, params });
  }

  async requestGetApiV1DebatesSlugBySlug(slug: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/debates/slug/${encodeURIComponent(slug)}`, { params });
  }

  async requestGetApiV1DebatesByDebateIdCounterfactuals(debate_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/debates/${encodeURIComponent(debate_id)}/counterfactuals`, { params });
  }

  async requestGetApiV1DebatesByDebateIdEvidence(debate_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/debates/${encodeURIComponent(debate_id)}/evidence`, { params });
  }

  async requestGetApiV1DebatesByDebateIdExplanation(debate_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/debates/${encodeURIComponent(debate_id)}/explanation`, { params });
  }

  async requestGetApiV1DebatesByDebateIdSummary(debate_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/debates/${encodeURIComponent(debate_id)}/summary`, { params });
  }

  async requestGetApiV1DebatesByDebateIdVotesPivots(debate_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/debates/${encodeURIComponent(debate_id)}/votes/pivots`, { params });
  }

  async requestGetApiV1DebatesById(id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/debates/${encodeURIComponent(id)}`, { params });
  }

  async requestPostApiV1DebatesByIdBroadcast(id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/debates/${encodeURIComponent(id)}/broadcast`, { body, params });
  }

  async requestGetApiV1DebatesByIdCitations(id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/debates/${encodeURIComponent(id)}/citations`, { params });
  }

  async requestGetApiV1DebatesByIdConvergence(id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/debates/${encodeURIComponent(id)}/convergence`, { params });
  }

  async requestGetApiV1DebatesByIdEvidence(id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/debates/${encodeURIComponent(id)}/evidence`, { params });
  }

  async requestGetApiV1DebatesByIdExportByFormat(id: string, format: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/debates/${encodeURIComponent(id)}/export/${encodeURIComponent(format)}`, { params });
  }

  async requestPostApiV1DebatesByIdFork(id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/debates/${encodeURIComponent(id)}/fork`, { body, params });
  }

  async requestGetApiV1DebatesByIdGraphStats(id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/debates/${encodeURIComponent(id)}/graph/stats`, { params });
  }

  async requestGetApiV1DebatesByIdImpasse(id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/debates/${encodeURIComponent(id)}/impasse`, { params });
  }

  async requestGetApiV1DebatesByIdMessages(id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/debates/${encodeURIComponent(id)}/messages`, { params });
  }

  async requestGetApiV1DebatesByIdMetaCritique(id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/debates/${encodeURIComponent(id)}/meta-critique`, { params });
  }

  async requestPostApiV1DebatesByIdPublishTwitter(id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/debates/${encodeURIComponent(id)}/publish/twitter`, { body, params });
  }

  async requestPostApiV1DebatesByIdPublishYoutube(id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/debates/${encodeURIComponent(id)}/publish/youtube`, { body, params });
  }

  async requestGetApiV1DebatesByIdRedTeam(id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/debates/${encodeURIComponent(id)}/red-team`, { params });
  }

  async requestGetApiV1Decisions(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/decisions', { params });
  }

  async requestPostApiV1Decisions(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/decisions', { body, params });
  }

  async requestGetApiV1DecisionsByRequestId(request_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/decisions/${encodeURIComponent(request_id)}`, { params });
  }

  async requestGetApiV1DecisionsByRequestIdExplain(request_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/decisions/${encodeURIComponent(request_id)}/explain`, { params });
  }

  async requestGetApiV1DecisionsByRequestIdStatus(request_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/decisions/${encodeURIComponent(request_id)}/status`, { params });
  }

  async requestGetApiV1DeliberationsActive(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/deliberations/active', { params });
  }

  async requestGetApiV1DeliberationsStats(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/deliberations/stats', { params });
  }

  async requestGetApiV1DeliberationsStream(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/deliberations/stream', { params });
  }

  async requestGetApiV1DeliberationsByDeliberationId(deliberation_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/deliberations/${encodeURIComponent(deliberation_id)}`, { params });
  }

  async requestGetApiV1Devices(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/devices', { params });
  }

  async requestPostApiV1DevicesAlexaWebhook(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/devices/alexa/webhook', { body, params });
  }

  async requestPostApiV1DevicesGoogleWebhook(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/devices/google/webhook', { body, params });
  }

  async requestGetApiV1DevicesHealth(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/devices/health', { params });
  }

  async requestPostApiV1DevicesRegister(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/devices/register', { body, params });
  }

  async requestGetApiV1DevicesByDeviceId(device_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/devices/${encodeURIComponent(device_id)}`, { params });
  }

  async requestDeleteApiV1DevicesByDeviceId(device_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('DELETE', `/api/v1/devices/${encodeURIComponent(device_id)}`, { params });
  }

  async requestGetApiV1Documents(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/documents', { params });
  }

  async requestGetApiV1DocumentsFormats(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/documents/formats', { params });
  }

  async requestPostApiV1DocumentsUpload(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/documents/upload', { body, params });
  }

  async requestGetApiV1EvolutionByAgentHistory(agent: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/evolution/${encodeURIComponent(agent)}/history`, { params });
  }

  async requestPostApiV1ExplainabilityBatch(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/explainability/batch', { body, params });
  }

  async requestGetApiV1ExplainabilityBatchByBatchIdResults(batch_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/explainability/batch/${encodeURIComponent(batch_id)}/results`, { params });
  }

  async requestGetApiV1ExplainabilityBatchByBatchIdStatus(batch_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/explainability/batch/${encodeURIComponent(batch_id)}/status`, { params });
  }

  async requestGetApiV1FlipsRecent(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/flips/recent', { params });
  }

  async requestGetApiV1FlipsSummary(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/flips/summary', { params });
  }

  async requestGetApiV1GauntletHeatmaps(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/gauntlet/heatmaps', { params });
  }

  async requestGetApiV1GauntletHeatmapsByHeatmapId(heatmap_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/gauntlet/heatmaps/${encodeURIComponent(heatmap_id)}`, { params });
  }

  async requestGetApiV1GauntletHeatmapsByHeatmapIdExport(heatmap_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/gauntlet/heatmaps/${encodeURIComponent(heatmap_id)}/export`, { params });
  }

  async requestGetApiV1GauntletReceipts(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/gauntlet/receipts', { params });
  }

  async requestPostApiV1GauntletReceiptsExportBundle(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/gauntlet/receipts/export/bundle', { body, params });
  }

  async requestGetApiV1GauntletReceiptsByReceiptId(receipt_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/gauntlet/receipts/${encodeURIComponent(receipt_id)}`, { params });
  }

  async requestGetApiV1GauntletReceiptsByReceiptIdExport(receipt_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/gauntlet/receipts/${encodeURIComponent(receipt_id)}/export`, { params });
  }

  async requestGetApiV1GauntletReceiptsByReceiptIdStream(receipt_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/gauntlet/receipts/${encodeURIComponent(receipt_id)}/stream`, { params });
  }

  async requestGetApiV1GenesisEvents(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/genesis/events', { params });
  }

  async requestGetApiV1GenesisLineageByAgent(agent: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/genesis/lineage/${encodeURIComponent(agent)}`, { params });
  }

  async requestGetApiV1GenesisStats(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/genesis/stats', { params });
  }

  async requestGetApiV1GenesisTreeByAgent(agent: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/genesis/tree/${encodeURIComponent(agent)}`, { params });
  }

  async requestPostApiV1GmailMessagesByMessageIdArchive(message_id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/gmail/messages/${encodeURIComponent(message_id)}/archive`, { body, params });
  }

  async requestGetApiV1GmailMessagesByMessageIdAttachmentsByAttachmentId(message_id: string, attachment_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/gmail/messages/${encodeURIComponent(message_id)}/attachments/${encodeURIComponent(attachment_id)}`, { params });
  }

  async requestPostApiV1GmailMessagesByMessageIdLabels(message_id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/gmail/messages/${encodeURIComponent(message_id)}/labels`, { body, params });
  }

  async requestPostApiV1GmailMessagesByMessageIdRead(message_id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/gmail/messages/${encodeURIComponent(message_id)}/read`, { body, params });
  }

  async requestPostApiV1GmailMessagesByMessageIdStar(message_id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/gmail/messages/${encodeURIComponent(message_id)}/star`, { body, params });
  }

  async requestPostApiV1GmailMessagesByMessageIdTrash(message_id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/gmail/messages/${encodeURIComponent(message_id)}/trash`, { body, params });
  }

  async requestGetApiV1Health(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/health', { params });
  }

  async requestGetApiV1HealthDetailed(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/health/detailed', { params });
  }

  async requestGetApiV1HistoryCycles(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/history/cycles', { params });
  }

  async requestGetApiV1HistoryDebates(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/history/debates', { params });
  }

  async requestGetApiV1HistoryEvents(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/history/events', { params });
  }

  async requestGetApiV1HistorySummary(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/history/summary', { params });
  }

  async requestPostApiV1InsightsExtractDetailed(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/insights/extract-detailed', { body, params });
  }

  async requestGetApiV1InsightsRecent(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/insights/recent', { params });
  }

  async requestPostApiV1IntegrationsTeamsCommands(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/integrations/teams/commands', { body, params });
  }

  async requestPostApiV1IntegrationsTeamsInteractive(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/integrations/teams/interactive', { body, params });
  }

  async requestPostApiV1IntegrationsTeamsNotify(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/integrations/teams/notify', { body, params });
  }

  async requestGetApiV1IntegrationsTeamsStatus(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/integrations/teams/status', { params });
  }

  async requestGetApiV1IntegrationsByType(type: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/integrations/${encodeURIComponent(type)}`, { params });
  }

  async requestPutApiV1IntegrationsByType(type: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('PUT', `/api/v1/integrations/${encodeURIComponent(type)}`, { body, params });
  }

  async requestPatchApiV1IntegrationsByType(type: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('PATCH', `/api/v1/integrations/${encodeURIComponent(type)}`, { body, params });
  }

  async requestDeleteApiV1IntegrationsByType(type: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('DELETE', `/api/v1/integrations/${encodeURIComponent(type)}`, { params });
  }

  async requestPostApiV1IntegrationsByTypeTest(type: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/integrations/${encodeURIComponent(type)}/test`, { body, params });
  }

  async requestGetApiV1IntrospectionAgents(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/introspection/agents', { params });
  }

  async requestGetApiV1IntrospectionAgentsByName(name: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/introspection/agents/${encodeURIComponent(name)}`, { params });
  }

  async requestGetApiV1IntrospectionAll(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/introspection/all', { params });
  }

  async requestGetApiV1IntrospectionLeaderboard(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/introspection/leaderboard', { params });
  }

  async requestGetApiV1KnowledgeFacts(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/knowledge/facts', { params });
  }

  async requestPostApiV1KnowledgeFacts(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/knowledge/facts', { body, params });
  }

  async requestPostApiV1KnowledgeFactsRelations(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/knowledge/facts/relations', { body, params });
  }

  async requestGetApiV1KnowledgeFactsByFactId(fact_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/knowledge/facts/${encodeURIComponent(fact_id)}`, { params });
  }

  async requestPutApiV1KnowledgeFactsByFactId(fact_id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('PUT', `/api/v1/knowledge/facts/${encodeURIComponent(fact_id)}`, { body, params });
  }

  async requestDeleteApiV1KnowledgeFactsByFactId(fact_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('DELETE', `/api/v1/knowledge/facts/${encodeURIComponent(fact_id)}`, { params });
  }

  async requestGetApiV1KnowledgeFactsByFactIdContradictions(fact_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/knowledge/facts/${encodeURIComponent(fact_id)}/contradictions`, { params });
  }

  async requestGetApiV1KnowledgeFactsByFactIdRelations(fact_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/knowledge/facts/${encodeURIComponent(fact_id)}/relations`, { params });
  }

  async requestPostApiV1KnowledgeFactsByFactIdRelations(fact_id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/knowledge/facts/${encodeURIComponent(fact_id)}/relations`, { body, params });
  }

  async requestPostApiV1KnowledgeFactsByFactIdVerify(fact_id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/knowledge/facts/${encodeURIComponent(fact_id)}/verify`, { body, params });
  }

  async requestGetApiV1KnowledgeMoundGovernanceAudit(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/knowledge/mound/governance/audit', { params });
  }

  async requestGetApiV1KnowledgeMoundGovernanceAuditUserByUserId(user_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/knowledge/mound/governance/audit/user/${encodeURIComponent(user_id)}`, { params });
  }

  async requestPostApiV1KnowledgeMoundGovernancePermissionsCheck(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/knowledge/mound/governance/permissions/check', { body, params });
  }

  async requestGetApiV1KnowledgeMoundGovernancePermissionsByUserId(user_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/knowledge/mound/governance/permissions/${encodeURIComponent(user_id)}`, { params });
  }

  async requestPostApiV1KnowledgeMoundGovernanceRoles(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/knowledge/mound/governance/roles', { body, params });
  }

  async requestPostApiV1KnowledgeMoundGovernanceRolesAssign(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/knowledge/mound/governance/roles/assign', { body, params });
  }

  async requestPostApiV1KnowledgeMoundGovernanceRolesRevoke(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/knowledge/mound/governance/roles/revoke', { body, params });
  }

  async requestGetApiV1KnowledgeMoundGovernanceStats(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/knowledge/mound/governance/stats', { params });
  }

  async requestPostApiV1KnowledgeQuery(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/knowledge/query', { body, params });
  }

  async requestGetApiV1KnowledgeSearch(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/knowledge/search', { params });
  }

  async requestGetApiV1KnowledgeStats(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/knowledge/stats', { params });
  }

  async requestGetApiV1LaboratoryCrossPollinationsSuggest(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/laboratory/cross-pollinations/suggest', { params });
  }

  async requestGetApiV1LaboratoryEmergentTraits(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/laboratory/emergent-traits', { params });
  }

  async requestGetApiV1Leaderboard(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/leaderboard', { params });
  }

  async requestGetApiV1LeaderboardView(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/leaderboard-view', { params });
  }

  async requestGetApiV1LearningEvolution(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/learning/evolution', { params });
  }

  async requestGetApiV1MatchesRecent(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/matches/recent', { params });
  }

  async requestGetApiV1MemoryArchiveStats(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/memory/archive-stats', { params });
  }

  async requestPostApiV1MemoryContinuumCleanup(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/memory/continuum/cleanup', { body, params });
  }

  async requestPostApiV1MemoryContinuumConsolidate(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/memory/continuum/consolidate', { body, params });
  }

  async requestGetApiV1MemoryContinuumRetrieve(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/memory/continuum/retrieve', { params });
  }

  async requestGetApiV1MemoryStats(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/memory/stats', { params });
  }

  async requestGetApiV1MemoryTierStats(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/memory/tier-stats', { params });
  }

  async requestGetApiV1MetaLearningStats(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/meta-learning/stats', { params });
  }

  async requestGetApiV1Metrics(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/metrics', { params });
  }

  async requestGetApiV1MetricsCache(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/metrics/cache', { params });
  }

  async requestGetApiV1MetricsHealth(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/metrics/health', { params });
  }

  async requestGetApiV1MetricsSystem(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/metrics/system', { params });
  }

  async requestGetApiV1Modes(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/modes', { params });
  }

  async requestGetApiV1MomentsByTypeByType(type: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/moments/by-type/${encodeURIComponent(type)}`, { params });
  }

  async requestGetApiV1MomentsSummary(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/moments/summary', { params });
  }

  async requestGetApiV1MomentsTimeline(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/moments/timeline', { params });
  }

  async requestGetApiV1MomentsTrending(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/moments/trending', { params });
  }

  async requestPostApiV1NomicControlPause(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/nomic/control/pause', { body, params });
  }

  async requestPostApiV1NomicControlResume(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/nomic/control/resume', { body, params });
  }

  async requestPostApiV1NomicControlSkipPhase(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/nomic/control/skip-phase', { body, params });
  }

  async requestPostApiV1NomicControlStart(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/nomic/control/start', { body, params });
  }

  async requestPostApiV1NomicControlStop(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/nomic/control/stop', { body, params });
  }

  async requestGetApiV1NomicHealth(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/nomic/health', { params });
  }

  async requestGetApiV1NomicLog(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/nomic/log', { params });
  }

  async requestGetApiV1NomicMayorCurrent(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/nomic/mayor/current', { params });
  }

  async requestGetApiV1NomicMetrics(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/nomic/metrics', { params });
  }

  async requestGetApiV1NomicProposals(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/nomic/proposals', { params });
  }

  async requestPostApiV1NomicProposalsApprove(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/nomic/proposals/approve', { body, params });
  }

  async requestPostApiV1NomicProposalsReject(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/nomic/proposals/reject', { body, params });
  }

  async requestPostApiV1NomicProposalsById(id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/nomic/proposals/${encodeURIComponent(id)}`, { body, params });
  }

  async requestGetApiV1NomicRiskRegister(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/nomic/risk-register', { params });
  }

  async requestGetApiV1NomicState(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/nomic/state', { params });
  }

  async requestGetApiV1NomicWitnessStatus(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/nomic/witness/status', { params });
  }

  async requestGetApiV1Openapi(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/openapi', { params });
  }

  async requestGetApiV1Personas(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/personas', { params });
  }

  async requestGetApiV1Plugins(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/plugins', { params });
  }

  async requestGetApiV1PluginsInstalled(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/plugins/installed', { params });
  }

  async requestGetApiV1PluginsMarketplace(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/plugins/marketplace', { params });
  }

  async requestGetApiV1PluginsSubmissions(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/plugins/submissions', { params });
  }

  async requestPostApiV1PluginsSubmit(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/plugins/submit', { body, params });
  }

  async requestGetApiV1PluginsByName(name: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/plugins/${encodeURIComponent(name)}`, { params });
  }

  async requestPostApiV1PluginsByNameInstall(name: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/plugins/${encodeURIComponent(name)}/install`, { body, params });
  }

  async requestDeleteApiV1PluginsByNameInstall(name: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('DELETE', `/api/v1/plugins/${encodeURIComponent(name)}/install`, { params });
  }

  async requestPostApiV1PluginsByNameRun(name: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/plugins/${encodeURIComponent(name)}/run`, { body, params });
  }

  async requestGetApiV1PodcastEpisodes(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/podcast/episodes', { params });
  }

  async requestGetApiV1PodcastFeed_xml(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/podcast/feed.xml', { params });
  }

  async requestPostApiV1ProbesCapability(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/probes/capability', { body, params });
  }

  async requestGetApiV1PulseSuggest(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/pulse/suggest', { params });
  }

  async requestGetApiV1PulseTrending(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/pulse/trending', { params });
  }

  async requestPostApiV1QueueCleanup(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/queue/cleanup', { body, params });
  }

  async requestGetApiV1QueueDlq(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/queue/dlq', { params });
  }

  async requestPostApiV1QueueDlqRequeue(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/queue/dlq/requeue', { body, params });
  }

  async requestGetApiV1QueueJobs(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/queue/jobs', { params });
  }

  async requestPostApiV1QueueJobs(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/queue/jobs', { body, params });
  }

  async requestGetApiV1QueueJobsByJobId(job_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/queue/jobs/${encodeURIComponent(job_id)}`, { params });
  }

  async requestDeleteApiV1QueueJobsByJobId(job_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('DELETE', `/api/v1/queue/jobs/${encodeURIComponent(job_id)}`, { params });
  }

  async requestPostApiV1QueueJobsByJobIdRetry(job_id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/queue/jobs/${encodeURIComponent(job_id)}/retry`, { body, params });
  }

  async requestGetApiV1QueueStale(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/queue/stale', { params });
  }

  async requestGetApiV1QueueStats(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/queue/stats', { params });
  }

  async requestGetApiV1QueueWorkers(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/queue/workers', { params });
  }

  async requestGetApiV1RankingStats(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/ranking/stats', { params });
  }

  async requestGetApiV1Rankings(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/rankings', { params });
  }

  async requestGetApiV1RelationshipByAgentAByAgentB(agent_a: string, agent_b: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/relationship/${encodeURIComponent(agent_a)}/${encodeURIComponent(agent_b)}`, { params });
  }

  async requestGetApiV1RelationshipsGraph(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/relationships/graph', { params });
  }

  async requestGetApiV1RelationshipsStats(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/relationships/stats', { params });
  }

  async requestGetApiV1RelationshipsSummary(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/relationships/summary', { params });
  }

  async requestGetApiV1Replays(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/replays', { params });
  }

  async requestGetApiV1ReplaysById(id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/replays/${encodeURIComponent(id)}`, { params });
  }

  async requestGetApiV1ReputationAll(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/reputation/all', { params });
  }

  async requestGetApiV1RetentionExpiring(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/retention/expiring', { params });
  }

  async requestGetApiV1RetentionPolicies(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/retention/policies', { params });
  }

  async requestPostApiV1RetentionPolicies(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/retention/policies', { body, params });
  }

  async requestPostApiV1RetentionPoliciesByPolicyIdExecute(policy_id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/retention/policies/${encodeURIComponent(policy_id)}/execute`, { body, params });
  }

  async requestGetApiV1RoutingBestTeams(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/routing/best-teams', { params });
  }

  async requestPostApiV1RoutingRecommendations(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/routing/recommendations', { body, params });
  }

  async requestGetApiV1Search(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/search', { params });
  }

  async requestGetApiV1SystemMaintenance(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/system/maintenance', { params });
  }

  async requestGetApiV1Tournaments(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/tournaments', { params });
  }

  async requestGetApiV1TournamentsByIdStandings(id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/tournaments/${encodeURIComponent(id)}/standings`, { params });
  }

  async requestGetApiV1UserOauthProviders(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/user/oauth-providers', { params });
  }

  async requestPostApiV1VerificationFormalVerify(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/verification/formal-verify', { body, params });
  }

  async requestGetApiV1VerificationStatus(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/verification/status', { params });
  }

  async requestGetApiV1Webhooks(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/webhooks', { params });
  }

  async requestPostApiV1Webhooks(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/webhooks', { body, params });
  }

  async requestGetApiV1WebhooksDeadLetter(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/webhooks/dead-letter', { params });
  }

  async requestGetApiV1WebhooksDeadLetterById(id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/webhooks/dead-letter/${encodeURIComponent(id)}`, { params });
  }

  async requestDeleteApiV1WebhooksDeadLetterById(id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('DELETE', `/api/v1/webhooks/dead-letter/${encodeURIComponent(id)}`, { params });
  }

  async requestPostApiV1WebhooksDeadLetterByIdRetry(id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/webhooks/dead-letter/${encodeURIComponent(id)}/retry`, { body, params });
  }

  async requestGetApiV1WebhooksEvents(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/webhooks/events', { params });
  }

  async requestGetApiV1WebhooksQueueStats(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/webhooks/queue/stats', { params });
  }

  async requestGetApiV1WebhooksSloStatus(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/webhooks/slo/status', { params });
  }

  async requestPostApiV1WebhooksSloTest(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/webhooks/slo/test', { body, params });
  }

  async requestGetApiV1WebhooksById(id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/webhooks/${encodeURIComponent(id)}`, { params });
  }

  async requestPatchApiV1WebhooksById(id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('PATCH', `/api/v1/webhooks/${encodeURIComponent(id)}`, { body, params });
  }

  async requestDeleteApiV1WebhooksById(id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('DELETE', `/api/v1/webhooks/${encodeURIComponent(id)}`, { params });
  }

  async requestPostApiV1WebhooksByIdTest(id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/webhooks/${encodeURIComponent(id)}/test`, { body, params });
  }

  async requestGetApiV1WorkflowApprovals(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/workflow-approvals', { params });
  }

  async requestPostApiV1WorkflowApprovalsByApprovalId(approval_id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/workflow-approvals/${encodeURIComponent(approval_id)}`, { body, params });
  }

  async requestGetApiV1WorkflowExecutions(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/workflow-executions', { params });
  }

  async requestGetApiV1WorkflowExecutionsByExecutionId(execution_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/workflow-executions/${encodeURIComponent(execution_id)}`, { params });
  }

  async requestDeleteApiV1WorkflowExecutionsByExecutionId(execution_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('DELETE', `/api/v1/workflow-executions/${encodeURIComponent(execution_id)}`, { params });
  }

  async requestGetApiV1WorkflowDashTemplates(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/workflow-templates', { params });
  }

  async requestGetApiV1WorkflowDashTemplatesByTemplateId(template_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/workflow-templates/${encodeURIComponent(template_id)}`, { params });
  }

  async requestGetApiV1WorkflowCategories(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/workflow/categories', { params });
  }

  async requestGetApiV1WorkflowPatterns(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/workflow/patterns', { params });
  }

  async requestPostApiV1WorkflowPatternsByPatternIdInstantiate(pattern_id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/workflow/patterns/${encodeURIComponent(pattern_id)}/instantiate`, { body, params });
  }

  async requestGetApiV1WorkflowTemplates(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/workflow/templates', { params });
  }

  async requestGetApiV1WorkflowTemplatesByTemplateId(template_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/workflow/templates/${encodeURIComponent(template_id)}`, { params });
  }

  async requestGetApiV1WorkflowTemplatesByTemplateIdPackage(template_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/workflow/templates/${encodeURIComponent(template_id)}/package`, { params });
  }

  async requestPostApiV1WorkflowTemplatesByTemplateIdRun(template_id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/workflow/templates/${encodeURIComponent(template_id)}/run`, { body, params });
  }

  async requestGetApiV1Workflows(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/workflows', { params });
  }

  async requestPostApiV1Workflows(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/workflows', { body, params });
  }

  async requestGetApiV1WorkflowsByWorkflowId(workflow_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/workflows/${encodeURIComponent(workflow_id)}`, { params });
  }

  async requestPutApiV1WorkflowsByWorkflowId(workflow_id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('PUT', `/api/v1/workflows/${encodeURIComponent(workflow_id)}`, { body, params });
  }

  async requestDeleteApiV1WorkflowsByWorkflowId(workflow_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('DELETE', `/api/v1/workflows/${encodeURIComponent(workflow_id)}`, { params });
  }

  async requestPostApiV1WorkflowsByWorkflowIdExecute(workflow_id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/workflows/${encodeURIComponent(workflow_id)}/execute`, { body, params });
  }

  async requestGetApiV1WorkflowsByWorkflowIdVersions(workflow_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/workflows/${encodeURIComponent(workflow_id)}/versions`, { params });
  }

  async requestGetApiV1Workspaces(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/workspaces', { params });
  }

  async requestPostApiV1Workspaces(body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', '/api/v1/workspaces', { body, params });
  }

  async requestGetApiV1WorkspacesProfiles(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/workspaces/profiles', { params });
  }

  async requestGetApiV1WorkspacesByWorkspaceId(workspace_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/workspaces/${encodeURIComponent(workspace_id)}`, { params });
  }

  async requestDeleteApiV1WorkspacesByWorkspaceId(workspace_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('DELETE', `/api/v1/workspaces/${encodeURIComponent(workspace_id)}`, { params });
  }

  async requestPostApiV1WorkspacesByWorkspaceIdMembers(workspace_id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v1/workspaces/${encodeURIComponent(workspace_id)}/members`, { body, params });
  }

  async requestPutApiV1WorkspacesByWorkspaceIdMembersByUserIdRole(workspace_id: string, user_id: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('PUT', `/api/v1/workspaces/${encodeURIComponent(workspace_id)}/members/${encodeURIComponent(user_id)}/role`, { body, params });
  }

  async requestGetApiV1WorkspacesByWorkspaceIdRoles(workspace_id: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v1/workspaces/${encodeURIComponent(workspace_id)}/roles`, { params });
  }

  async requestGetApiV1YoutubeAuth(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/youtube/auth', { params });
  }

  async requestGetApiV1YoutubeCallback(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/youtube/callback', { params });
  }

  async requestGetApiV1YoutubeStatus(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v1/youtube/status', { params });
  }

  async requestGetApiV2Integrations(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/api/v2/integrations', { params });
  }

  async requestGetApiV2IntegrationsByType(type: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v2/integrations/${encodeURIComponent(type)}`, { params });
  }

  async requestDeleteApiV2IntegrationsByType(type: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('DELETE', `/api/v2/integrations/${encodeURIComponent(type)}`, { params });
  }

  async requestGetApiV2IntegrationsByTypeHealth(type: string, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', `/api/v2/integrations/${encodeURIComponent(type)}/health`, { params });
  }

  async requestPostApiV2IntegrationsByTypeTest(type: string, body?: unknown, params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('POST', `/api/v2/integrations/${encodeURIComponent(type)}/test`, { body, params });
  }

  async requestGetMetrics(params?: Record<string, unknown>): Promise<unknown> {
    return this.client.request('GET', '/metrics', { params });
  }

}
